### ISSUE TITLE
Connect 'mechanism' is hardcoded to 'PLAIN'

### ISSUE THREAD

**Issue by utestmig** [squaremo/amqp.node#105]
Our rabbit installation isn't configured for 'PLAIN' and IT does not want to use plain. We authenticate via SSL certs. However, the connection code has it hardcoded to 'PLAIN' and there isn't a way to pass in a different mechanism setting type.

**Comment by torvitas** [comment]
Could someone hint me to the documentation of this behaviour please?

**Comment by anngo23** [comment]
10 years later, still adding a ton of value here with this fix. Thanks! 😂
