### ISSUE TITLE
Failover scenarios

### ISSUE THREAD

**Issue by andronat** [squaremo/amqp.node#128]
Hello, I would like to know if it possible to include an example that demonstrates a failover scenario between multiple Message Queues.

Or someone write some comments on how can this be done?

**Comment by squaremo** [comment]
Hi there,

There's no explicit support in amqplib for failover, but it doesn't prevent you using RabbitMQ's clustering and mirrored queues (http://www.rabbitmq.com/ha.html) and so on, either.

In general, there's no one recommended approach to failover.

If you want to do it in Node.JS code a simple way would be to keep a list of nodes, and when your connection is dropped, try to connect to the next node in the list.

People sometimes use HAProxy to direct connections to "live" nodes, in which case all you need to do in your app would be to attempt to reconnect (and possibly re-assert queues and so on).
