### ISSUE TITLE
Allow channel.reject without closing channel. 

### ISSUE THREAD

**Issue by mateodelnorte** [squaremo/amqp.node#130]
I'm trying to use domains to encapsulate the runtime behavior for individual messages:
```
function reject (msg, err) {
  if (err.stack) log.error(err.stack);
  else if (err.message) log.error(err.message);
  else console.trace();
  log.warn('rejecting message');
  msg.handle.reject();
}
...
bus.listen(topic, { ack: true, log: log.debug }, function (msg) {
        var handler = handlers[msg.data.command];
        var d = domain.create();

        d.once('error', function (err) {
          if (err.stack) log.error(err.stack);
          else if (err.message) log.error(err.message);
          else log.error(err.toString());
          // console.log('market not null: ', !!marketRepository.market)
          if (marketRepository.market) {
            var market = marketRepository.market;
            marketRepository.market = null;
            marketRepository.sagaTimeout = null;
            // console.log('unlocking')
            market.emit('unlocked');
          }
          log.warn('rejecting message');
          msg.handle.reject();
          // d.dispose();
        });

        var fn = d.bind(handler);

        fn(marketId, msg, function (err) {
          if (err) return reject(msg, err);      
```
The above is https://github.com/mateodelnorte/servicebus code which wraps a channel.consume(). It appears that after rejecting an error, my code goes on processing as it should, but if it happens a second time I start to get strange errors like: 
```
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 311"
      at Channel.C.accept (/Users/matt/development/electronifie/electronifie/market-svc/node_modules/servicebus/node_modules/amqplib/lib/channel.js:399:24)
      at Connection.mainAccept [as accept] (/Users/matt/development/electronifie/electronifie/market-svc/node_modules/servicebus/node_modules/amqplib/lib/connection.js:62:33)
      at Socket.go (/Users/matt/development/electronifie/electronifie/market-svc/node_modules/servicebus/node_modules/amqplib/lib/connection.js:459:48)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```
Is it possible to ensure that errors bubble up to a domain instead of uncaughtException in a way that allows open channels to continue to be used? 

The retry logic I'm currently using is shown here: https://github.com/mateodelnorte/servicebus/blob/master/bus/middleware/retry.js (assuming { localOnly: true }.

Is there something I should be doing differently to get this going? 

Thanks.

**Comment by squaremo** [comment]
On the surface, that should work as expected; and it seems like the domain is doing its job in that it turns any exception into an error event, and the channel is still alive at that point.

Is it possible that a message is made available to another part of the code which might acknowledge or reject it? (a way to check this would be to put a check in `msg.handle.{ack,reject}` that only one gets called, once)

**Comment by mateodelnorte** [comment]
That does appear to be the issue, but I can't figure out how the second reject is occurring...

I updated the retry middleware to have the following guard:
```
function retryLocal (channel, message, options, next) {

  var calledByMethod, stack;
  function onlyOnce (method) {

    if (calledByMethod !== undefined) {
      throw new Error(util.format('message type: %s cid: %s handle already called with %s', message.content.type, message.content.cid, calledByMethod));
    } else {
      calledByMethod = method; 
    }
    
  }

  if (options && options.ack) {

    message.content.handle = {
      ack: function () { 
        onlyOnce('ack');
        channel.ack(message);  
      },
      acknowledge: function () {
        onlyOnce('ack');
        channel.ack(message);  
      },
      reject: function () {
        onlyOnce('reject');
```
...which does end up throwing. I ran a few times capturing stack info in order to see where the additional rejects come from, but they originate from the same domain.on('error', fn) event. When I remove the above guard and let the additional reject take place, I get the following:
```
20:35:25.978Z  WARN node: rejecting message (correlationId=silver-wood-7k5_SDcXH)
20:35:25.984Z ERROR node: (correlationId=silver-wood-7k5_SDcXH)
    Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 159"
      at Channel.C.accept (/Users/matt/development/servicebus/node_modules/amqplib/lib/channel.js:399:24)
      at Connection.mainAccept [as accept] (/Users/matt/development/servicebus/node_modules/amqplib/lib/connection.js:62:33)
      at Socket.go (/Users/matt/development/servicebus/node_modules/amqplib/lib/connection.js:451:48)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      at emitReadable (_stream_readable.js:423:5)
      at readableAddChunk (_stream_readable.js:166:9)
      at Socket.Readable.push (_stream_readable.js:128:10)
      at TCP.onread (net.js:529:21)
```
I'm not supplying any [upTo] values on acking or rejecting, so I wouldn't expect it to be an ordering issue. 

It only appears to happen after the 3rd retry, when lots of messages are going over the bus. So, single messages which throw errors are correctly rejecting x times, with requeue, then rejecting and sending to an error queue. With multiple messages, it seems to get confused and every once in a while a message things it's already been rejected on the 3rd reject/retry attempt. 

Any ideas? 

Thanks for the help.

**Comment by mateodelnorte** [comment]
Posting to share, because this one was a doozy. 

We've got a repository pattern module that internally uses the async.queue function (https://github.com/caolan/async#queueworker-concurrency) to act as a gatekeeper on resources the repository provides. Basically, requests get processed once previous requests signal they're done via a callback. K. Let's continue...

We've decided failed messages in certain services shouldn't bounce the service just because of SLA conditions. Trade offs. So, we're using domains to see that incoming messages bubble errors to domains: https://github.com/mateodelnorte/servicebus/blob/master/bus/middleware/messageDomain.js

The above two items are important together because if the async.queue waits for some time before processing an incoming message, another message could have come through the messageDomain middleware, creating a new domain. Because of however Node is going about entering and exiting domains, and setting process.domain, during process.nextTick continuation - we were seeing that messages which were being rejected were actually associated with *previous* messages' domains. The correlation ids you see added in the middleware were off. 

By first glance, it simply looked like acking or rejecting a message once was causing an error to be throw, but actually it was because an an old domain's handler was catching a new message's error and rejecting an already acked or rejected message. 

The solution was to ensure that callbacks passed in to async.queue were explicitly bound to domains ala:
```
q.push({ params: 1, cb: process.domain.bind(cb) });
```
You can then execute the tasks in your queue like: 
```
async.queue(function (task, next) {
    self._fetch.call(self, task.id, function (err, market) {
      market.once('unlocked', next);
      task.cb(err, market); 
    });
  });
```
and task.cb will still be within the correct domain's context. 

Cheers. ;)

**Comment by squaremo** [comment]
Ouch -- well done on tracking that one down!
