### ISSUE TITLE
Example for prefetch count

### ISSUE THREAD

**Issue by s888** [squaremo/amqp.node#131]
Is there an example that demonstrates RabbitMQ's prefetch count ? I am not able to find it.

**Comment by michaelklishin** [comment]
[There is](https://github.com/squaremo/amqp.node/blob/master/examples/tutorials/worker.js#L10) (the code example is a port of RabbitMQ tutorial 2). It may be quite a good idea direct your questions to the rabbitmq-users mailing list. Many maintainers consider GitHub issues to be for bugs and feature requests, not questions.

**Comment by s888** [comment]
@michaelklishin thanku.

**Comment by squaremo** [comment]
(I don't mind having questions here but what @michaelklishin says is indeed often the case)

**Comment by s888** [comment]
I posted the question over here since I couldn't find how it could be done in node.js using this library. May be I should have searched more for it in the tutorials before posting..

**Comment by squaremo** [comment]
@s888 Did you find the information you needed? Can we close this?
