### ISSUE TITLE
Relax package.json "engine" dependencies

### ISSUE THREAD

**Issue by nicholaswyoung** [squaremo/amqp.node#133]
When installing with io.js, npm says:

```
npm WARN engine amqplib@0.2.1: wanted: {"node":"0.8 || 0.9 || 0.10 || 0.11"} (current: {"node":"1.1.0","npm":"2.4.1"})
```
Could you safely relax this requirement to quiet npm's warning?

**Comment by squaremo** [comment]
Yes, looks like it -- it passes tests on 0.12, 1.0, and 1.1. I'll roll another release soon so you get the benefit.

**Comment by nicholaswyoung** [comment]
@squaremo Awesome. Thanks!

**Comment by squaremo** [comment]
Release 0.3.1 says it supports engines v0.8 through v0.12, v1.0 and v1.1. Does this tick the box?

**Comment by nicholaswyoung** [comment]
io.js is now at 1.5.1 (and I'm on the edge), so it's close. I'm not seeing any issues, but silencing the warning would be helpful.

**Comment by squaremo** [comment]
> io.js is now at 1.5.1

Whaaaaaa ..? I'm sure it was only at 1.1 when I did that release. What are they playing at!

**Comment by nicholaswyoung** [comment]
I think they're cutting releases fast until they're sure everything is stable. Which I think they are now. 

V8 in Chrome production build is now the same as io 1.5.1, so I expect it slow down.

**Comment by squaremo** [comment]
PR #146 fixed this, or at least postponed difficulties significantly.
