### ISSUE TITLE
npm package publish?

### ISSUE THREAD

**Issue by robraux** [squaremo/amqp.node#137]
The last published package in npm is from Oct 21, 2014 -- coming up on 4 months. There are a number of bug fixes which I'd love to make use of, without needing to subscribe to a commit from master.

Are there plans to publish another release soon?

**Comment by squaremo** [comment]
Good point, yes -- and I've promised elsewhere to roll another release. Next time I have some spare time (next few days)!

**Comment by robraux** [comment]
That's terrific, thank you kindly!

**Comment by robraux** [comment]
v0.3.1 released, closing.
