### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by richzw** [squaremo/amqp.node#138]
Currently I create one `Sender` class which can send message to amqp, and reconnect to amqp. Here are the codes [https://gist.github.com/richzw/e39237aa1fe31c15a587](https://gist.github.com/richzw/e39237aa1fe31c15a587)

Then I test it with amqp failure recover, 

```javascript
var Sender = require('./sender.js');
var sender = new Sender( amqpAddress, 2000, 3, sendMessageCallback );

function sendMessageCallback( ) {
	console.error('Message can NOT be sent due to MessageBus error');
}

// send message every 5 seconds
var CronJob = require('cron').CronJob;
var send_message_job = new CronJob({
    cronTime: '*/5 * * * * *',
    onTick: function(){
         sender.deliverMessage( key, msg );
    },
    start: true,
});

send_message_job.start();
```

Then I try to stop and start amqp service randomly. The first time restart amqp service, the sender can continue to send messages normally. However, when I try to stop the service at the **second time**, the following error comes up.

`Error: read ECONNRESET at errnoException (net.js:905:11) at TCP.onread (net.js:559:19)`

I try to test it several times, the above error always comes up at the **second time**. Why? 
Can anyone help me figure out how to handle it?

**Comment by michaelklishin** [comment]
What is in RabbitMQ log files?

**Comment by richzw** [comment]
=WARNING REPORT==== 12-Feb-2015::15:56:25 ===
closing AMQP connection <0.397.0> (127.0.0.1:8273 -> 127.0.0.1:5672):
connection_closed_abruptly

=WARNING REPORT==== 12-Feb-2015::15:56:25 ===
closing AMQP connection <0.458.0> (127.0.0.1:8278 -> 127.0.0.1:5672):
connection_closed_abruptly


=SUPERVISOR REPORT==== 12-Feb-2015::13:47:54 ===
     Supervisor: {<0.443.0>,rabbit_channel_sup_sup}
     Context:    shutdown_error
     Reason:     shutdown
     Offender:   [{nb_children,1},
                  {name,channel_sup},
                  {mfargs,{rabbit_channel_sup,start_link,[]}},
                  {restart_type,temporary},
                  {shutdown,infinity},
                  {child_type,supervisor}]


=SUPERVISOR REPORT==== 12-Feb-2015::14:25:24 ===
     Supervisor: {<0.432.0>,rabbit_channel_sup_sup}
     Context:    shutdown_error
     Reason:     shutdown
     Offender:   [{nb_children,1},
                  {name,channel_sup},
                  {mfargs,{rabbit_channel_sup,start_link,[]}},
                  {restart_type,temporary},
                  {shutdown,infinity},
                  {child_type,supervisor}]

**Comment by michaelklishin** [comment]
This is from 2 log files, regular and SASL?

What happened around `12-Feb-2015::15:56:25` suggests the client opened a TCP connection, then abruptly closed it.

The supervisor report in the SASL log may be a red herring (although I'm curious what RabbitMQ version do you use?)

**Comment by richzw** [comment]
Yes, they are from two log files, regular and SASL. And the version of RabbitMQ is 3.4.3.

At `12-Feb-2015::15:56:25`, I just stop the RabbitMQ service manually.

**Comment by michaelklishin** [comment]
When RabbitMQ is shut down, it notifies clients about connection closure. Clients should respond instead of simply closing TCP connection (there is no harm in doing the latter but that's not what the protocol says they should do). So something is off in the client.

**Comment by richzw** [comment]
@michaelklishin, thanks for your information.

The error ECONNRESET can be caught in `connection.on('error', function(e){})`.

There is one error in my codes, after fixing it. This exception can be caught now.
