### ISSUE TITLE
Trying to connect with a username and password

### ISSUE THREAD

**Issue by toymachiner62** [squaremo/amqp.node#140]
I'm very new to message queues and I was given a server name, queue name, username and password and i'm trying to figure out how to connect based on your examples and the api doc for connect. I noticed in the api docs for connect http://www.squaremobius.net/amqp.node/doc/channel_api.html that there is this example connection string `amqp://guest:guest@localhost:5672` but I can't make out what is the server name, what is the queue name and where the password is.

**Comment by michaelklishin** [comment]
You do not connect to queues, you connect to nodes (well, a vhost on a node), so queue name is not present in connection URIs.

In `amqp://guest:guest@localhost:5672`, `amqp` is the schema, `guest` before the colon is username, `guest` after the colon is password, `localhost` is node hostname, and `5672` is the port, very much like in other URLs.

[URI spec reference](http://www.rabbitmq.com/uri-spec.html). I also highly recommend [introduction to AMQP 0-9-1 concepts](http://www.rabbitmq.com/tutorials/amqp-concepts.html).

**Comment by toymachiner62** [comment]
Ah thanks for this.
