### ISSUE TITLE
In callback API, Channel#ack and #nack should accept a callback

### ISSUE THREAD

**Issue by timoch** [squaremo/amqp.node#143]
Channel#ack and Channel#nack do not currently have a callback to indicate they are done.

If you call Connection#close immediately after Channel#ack, the ACK is not sent and RabbitMQ keeps the message to be redelivered.

My current workaround is to wait a few hundred ms before calling Connection#close

I noticed during unit tests but I can see real world scenarios where this can be an issue.
Does the promise API exhibit the same ?

Thanks,

**Comment by squaremo** [comment]
> Channel#ack and Channel#nack do not currently have a callback to indicate they are done.

These aren't RPCs in AMQP, so there's no indication from the server that they have been received or processed. 

The reason that Connection.close prevents the ack from being sent is that it closes the connection immediately -- any frames on channels that have not been sent are discarded.

The standard way to deal with this is to synchronise with an RPC on the channel afterwards; if you're shutting down, then you could send `channel.close()` for example, and close the connection when that completes.

Yes, the promise API has the analogous situation.

**Comment by timoch** [comment]
Sounds legit ;-)
Thanks
