### ISSUE TITLE
how to authenticate to rabbitmq ?

### ISSUE THREAD

**Issue by mlmarius** [squaremo/amqp.node#152]
Hi.
Can't find anywhere in the docs of the api or examples how to authenticate to my rabbitmq with my username and password. Can someone help ?

**Comment by darrellodonnell** [comment]
amqp[s]://[user:password@]hostname[:port][/vhost]

It's in the main readme.

**Comment by mlmarius** [comment]
Thanks !

**Comment by squaremo** [comment]
Thanks @darrellodonnell.

For reference, the connection URL follows this specification: http://www.rabbitmq.com/uri-spec.html
