### ISSUE TITLE
How do you connect to a RabbitMQ cluster with this library?

### ISSUE THREAD

**Issue by damianof** [squaremo/amqp.node#155]

**Comment by PritamUpadhyay** [comment]
+1

**Comment by carlhoerberg** [comment]
Just follow the README. Do you experience any problem in particular?

**Comment by carlhoerberg** [comment]
Or is you question if you can specify an array of hostname/ip:s to multiple nodes?

**Comment by michaelklishin** [comment]
Every client is only connected to a single node. Is your question about automatic connection recovery and list host support, something that several other clients have?

**Comment by damianof** [comment]
Ok so I was able to connect to a cluster by setting 'host' option to an array of hosts like ['127.0.0.1:5672', '127.0.0.1:5673'].

However, looking at the code I see it randomly picks one when you connect. But like michaelklishin mention, does this library also support automatic failover if one of them goes down? Or do I have to implement my own connection recovery?

**Comment by rusintez** [comment]
+1

**Comment by ralcini** [comment]
i'm searching into documentation about connecting to a cluster of brokers, but without success.
@damianof : where do you found documentation about "host" option?

**Comment by zweifisch** [comment]
automatic failover/connection recovery is not supported

**Comment by squaremo** [comment]
> automatic failover/connection recovery is not supported

That's right -- and there's no form of connect that accepts an array of hosts (perhaps you were thinking of node-amqp, @damianof ?)

I have resisted adding reconnection/failover so far -- see #25 for the most extensive discussion.

**Comment by jwalton** [comment]
@damianof See if https://github.com/benbria/node-amqp-connection-manager works for your use case.

**Comment by cressie176** [comment]
[Rascal](https://github.com/guidesmiths/rascal) (built on top of amqp.node) might also be of some use. It accepts a list of hosts and will attempt to connect / reconnect to one of them at random, or until all hosts have failed.

**Comment by michaelklishin** [comment]
@cressie176 please announce it on rabbitmq-users?

**Comment by cressie176** [comment]
@michaelklishin done. Thanks for the suggestion.
