### ISSUE TITLE
checkQueue catch exception issue

### ISSUE THREAD

**Issue by guillaumepotier** [squaremo/amqp.node#156]
Hi there,

I'm using your lib to consume a RabbitMQ queue for messages to be broadcasted through socket.io. I'm trying to detect if the configured queue does exist before consuming it with `checkQueue`, all is good when queue exist, but when there is a problem, I'm unable to catch the exception and do something in my code, it just crash the thread and make my supervisor going crazy. Do you have a clue why I can't catch exception like I'm able to do for other methods like `connect`?

```javascript
[..]
    connect: function () {
        amqp.connect(config.amqp.host, function (err, conn) {
            if (null !== err) {
                logger.warn('[AMQP] Connexion: an error occured: "' + err.code + '"');
                return this.reconnect();
            }

            conn.createChannel(function (err, channel) {
                if (null !== err) {
                    logger.warn('[AMQP] Channel: an error occured: "' + err.code + '"');
                    return this.reconnect();
                }

                channel.checkQueue(config.amqp.queue, function (err, ok) {
                    if (null !== err) {
                        logger.warn('[AMQP] CheckQueue: an error occured: "' + err.code + '"');
                        return this.reconnect();
                    }

                    this.consume(channel, config.amqp.queue);
                }.bind(this));
            }.bind(this));
        }.bind(this));
    },
[..]
```

```javascript
DEBUG: Starting child process with 'node bin/server.js'
2015-05-23T09:57:07.222Z - info: Using the memory adapter
2015-05-23T09:57:07.224Z - info: The server has started. Let the awesomeness begin!
2015-05-23T09:57:07.224Z - info: Using AMQP consumer
2015-05-23T09:57:07.244Z - warn: [AMQP] CheckQueue: an error occured: "undefined"
2015-05-23T09:57:07.244Z - info: [AMQP] Trying to reconnect in 5000 ms...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'push_events' in vhost '/'"
    at Channel.C.accept (/Users/guillaumepotier/Sites/BalloonPushServer/node_modules/amqplib/lib/channel.js:403:24)
    at Connection.mainAccept [as accept] (/Users/guillaumepotier/Sites/BalloonPushServer/node_modules/amqplib/lib/connection.js:62:33)
    at Socket.go (/Users/guillaumepotier/Sites/BalloonPushServer/node_modules/amqplib/lib/connection.js:465:48)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
DEBUG: Program node bin/server.js exited with code 8
```

Thanks for your help.

Best

**Comment by connec** [comment]
See [the docs](http://www.squaremobius.net/amqp.node/doc/channel_api.html#toc_30): "This will bork the channel if the named queue doesn't exist".  Therefore you would have to handle the error on `channel` instead.

**Comment by guillaumepotier** [comment]
Hi @connec, thanks for the prompt answer! I've seen that yes, but this is just reading your comment I realize I have to play with `channel.on('error', [..]);`;

Sorry for that.

Best

**Comment by mikalai-silivonik** [comment]
Thanks for the thread @guillaumepotier ! Had the same issue too - never through I had to additionally catch the error on a channel...

**Comment by cage1618** [comment]
Has any way to prevent channel close if a queue does not exist when I us checkQueue? thanks

**Comment by michaelklishin** [comment]
Attempting to use a non-existent queue is a channel-level exception in the protocol.

**Comment by cage1618** [comment]
@michaelklishin,  Shoud I create an new channel for every request or not? thanks!

**Comment by michaelklishin** [comment]
Channels are [supposed to be long-lived](http://www.rabbitmq.com/tutorials/amqp-concepts.html) and re-opened only when there's real need for it or a channel-level exception occurs.

**Comment by jeremyvergnas** [comment]
Just to be clear...

Is there a proper way to check whether a given queue exists or not without breaking the channel in case the queue actually does not exist?

Thanks

**Comment by bijaykanshinew** [comment]
Use the catch statement in promise in following manner 
var done = chnl.checkQueue(queue_name);
 done.then(function(ok) {
      //its getting called when queue exist
}).catch(function (error) {
    //this one will be called when queue doesn't exist
})

**Comment by jeremyvergnas** [comment]
@bijaykanshinew Thanks, but the channel will still be broken in that case. 

But I managed to fix my issue without using `checkQueue` after all.

**Comment by bijaykanshinew** [comment]
i think there is no other method to check existence of queue except checkQueue. you can re-connect the channel from catch block.

**Comment by mateuspiresl** [comment]
@jeremyvergnas How did you do without using `checkQueue`? I'm stuck. =/

**Comment by cyrilchapon** [comment]
> Attempting to use a non-existent queue is a channel-level exception in the protocol.

Trying to `checkQueue` is precisely an attempt not to "use a non-existent queue".

How does one check a queue existence without borking the channel ?

**Comment by cressie176** [comment]
> How does one check a queue existence without borking the channel

It isn't possible to check the existence of a missing queue without breaking the channel using amqp 0.9.1 protocol. 

Instead I usually redeclare all queues when my applications start. Providing the parameters are identical to those that were used originally there while be no side effects.

**Comment by Recodify** [comment]
If you're using Rabbitmq, another alternative is use the http api to check if the queue exists first, step around ampq, and then do what you need to amqp. Below is a quick example doing this in typescript. Only dep is `node-fetch`

```
export interface BasicQueueDetails {
    state: string;
    type: string;
    vhost: string;
    name: string;
    arguments: {
        'x-dead-letter-exchange': string;
        'x-max-length': number;
    };
}

export interface RabbitApiOptions {
    host: string;
    port: number;
    user: string;
    password: string;
}

async function getQueue(queueName: string, vhostName: string, options: RabbitApiOptions): Promise<BasicQueueDetails|null> {
    // Http encode / for default vhost, if required
    const vhostUri = !vhostName || vhostName === '/' ? '%2F' : vhostName;

    // Build url
    const baseUri = `http://${options.user}:${options.password}@${options.host}:${options.port}/api`;
    const url = `${baseUri}/queues/${vhostUri}/${queueName}`;

    // Get the queue
    const fetch = require('node-fetch');
    const res = await fetch(url, {
        method: 'GET'
    });

    // Doesn't exist
    if (res.status === 404){
        return null;
    }

    // Does exist
    return res.json();
}

getQueue('myqueuename', '/', { host: 'localhost',  port: 15672, user: 'elonmusk', password: 'secret'}).then(x => {
    if (x){
        console.log('queue exists');
    } else {
        console.log('queue does not exist');
    }
});
```
