### ISSUE TITLE
Publish does not return promise or callback.

### ISSUE THREAD

**Issue by s84** [squaremo/amqp.node#161]
I can see how there might be a good reason why this is not possible, but if it is possible, then let's implement it because the alternative is `setTimeout` :(

**Comment by michaelklishin** [comment]
When publisher confirms are enabled, this makes sense.

**Comment by s84** [comment]
@michaelklishin Thanks for the fast reply!

To be clear, by `publish confirms` we mean RabbitMQ expects an acknowledgement to be sent by the consuming party?

Is that correct?

**Comment by michaelklishin** [comment]
See [Publisher Confirms](http://www.rabbitmq.com/confirms.html).

**Comment by carlhoerberg** [comment]
Why not use the socket.write callback? then at least we know the data is out the door of the client. We don't know that it has reached the server but it's better then nothing..

**Comment by s84** [comment]
@michaelklishin guide me if I'm total wrong ;)

After looking over publish confirms it looks like I need to create a channel with `createConfirmChannel ` and then publish will return with a promise or callback respectively.

Am I on the right track?

**Comment by michaelklishin** [comment]
> then at least we know the data is out the door of the client. We don't know that it has reached the server but it's better then nothing

Is it?

amqp gem has had a callback for `AMQP::Channel#publish` for a long time. Most people believe it is called when their data is safe, some even believe it is when messages reach consumers. No amount
of warnings in the docs help with that.

A lot of people have next to no clue about distributed systems and network programming. Libraries that offer "at least something" will only help them get in trouble faster. I don't know how valuable that is.

When publisher confirms are disabled, perhaps using a socket write callback is the best we can do but the docs must make it very clear what's going on and link to relevant rabbitmq.com guides.

**Comment by michaelklishin** [comment]
@s84 [this example](https://github.com/squaremo/amqp.node/blob/master/examples/waitForConfirms.js#L13) suggests you are on the right track. Note that `waitForConfirms` is not the only way to use publisher confirms, just the easiest (and the most paranoid, and offering poor throughput).

**Comment by s84** [comment]
@michaelklishin Yup, this worked. +1 for paranoid.

Bye bye `setTimeout` :)

Thanks for the help!

**Comment by s84** [comment]
I was only able implement `publish` on a `confirmChannel` with callbacks. `waitForConfirms` works with promises but `publish().then()` errors with no then method. Any ideas?

**Comment by squaremo** [comment]
> but publish().then() errors with no method .then.

In both the callback and promise APIs, publish takes a _callback_ for the confirmation. This is because I want to keep the return value from publish to indicate flow control status (i.e., whether the write buffer is full or not).
