### ISSUE TITLE
Add priority support 

### ISSUE THREAD

**Issue by akainz** [squaremo/amqp.node#162]
As RabbitMQ supports priority priority queues natively it would be great if that support was added to the client. As far as I can tell, only the queue option needs to be added to the client
 
lib/api_args.js | 3 ++-

@@ -57,6 +57,7 @@ Args.assertQueue = function(queue, options) {
   setIfDefined(argt, 'x-dead-letter-routing-key',
                options.deadLetterRoutingKey);
   setIfDefined(argt, 'x-max-length', options.maxLength);
\+  setIfDefined(argt, 'x-max-priority', options.priority);

**Comment by jcready** [comment]
Do you really need this change? The max-priority can already be defined by setting `x-max-priority` in the `options.arguments` object [as mentioned in the docs](http://www.squaremobius.net/amqp.node/doc/channel_api.html#toc_27).

```js
channel.assetQueue('myQueue', { arguments : { 'x-max-priority' : 2 } });
```

**Comment by akainz** [comment]
Hi Wyatt, a case of RTFM on my side, sorry. Thanks for the info, that is sufficient.
