### ISSUE TITLE
Create queues with some x-max-priority values fails

### ISSUE THREAD

**Issue by ezequielgarcia88** [squaremo/amqp.node#165]
If if create a queue with x-max-priority at 255 it fails with the following error:
```console
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - invalid arg 'x-max-priority' for queue 'tasks' in vhost '/': {value_negative,-1}"
```

This is my example code:
```javascript
require('amqplib').connect('amqp://guest:guest@localhost:5672').then(function(conn) {
	return conn.createChannel().then(function(ch) {
		return ch.assertExchange('tasks-ex', 'fanout').then(function() {
			return ch.assertQueue('tasks', {
				arguments : {
					'x-max-priority' : 255
				}
			}).then(function (qok) {
				return ch.bindQueue(qok.queue, 'tasks-ex', '').then(function () {
					return qok.queue;
				});
			}).then(function (queue) {
				return ch.consume(queue, function (msg) {
					if (msg !== null) {
						console.log(' [x] Received "%s"', msg.content.toString());
						ch.ack(msg);
					}
				},{
					noAck : false
				});
			});
		});
	});
}).then(null, console.warn);
```

Do you know why this happens?

**Comment by michaelklishin** [comment]
The message says what the problem is: you already have a queue named `tasks` and it has different attributes (headers, in this case). Delete it and declare it again with the headers you want.

**Comment by ezequielgarcia88** [comment]
Hi, thanks for the quick answer. I don't have the queue created in RabbitMQ, and also the example code works by only changing the x-max-priority to 256.

This is the error I get if the queue was already created with different attributes:
```console
Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue 'tasks' in vhost '/': received '258' but current is '256'"
```

**Comment by michaelklishin** [comment]
@ezequielgarcia88 

````
inequivalent arg 'x-max-priority' for queue 'tasks' in vhost '/': received '258' but current is '256'"
```

suggests that you do have that queue in vhost `/`. In an unrelated note, 256 priorities is excessive and will introduce a lot of unnecessary overhead. 5-10 should be sufficient for most use cases.

**Comment by squaremo** [comment]
In the first example, the error was `invalid arg 'x-max-priority' for queue 'tasks' in vhost '/': {value_negative,-1}`, which suggests to me some weird encoding is going on. Maybe RabbitMQ expects an unsigned encoding, but the client library uses a signed encoding (because how is it supposed to know, for arbitrary arguments).

**Comment by squaremo** [comment]
Iiiiinteresting: https://github.com/rabbitmq/rabbitmq-server/commit/a640f74dc8d5dcd667fd9154bb323765fbf3e863

**Comment by Laksh47** [comment]
replace the 'x-max-priority' with 'maxPriority'
reference: http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue

**Comment by tholisam-sasikala** [comment]
I want to set queue 
Max length should be set in the call to queue declare using the params argument, not externally with rabbitmqctl...
