### ISSUE TITLE
channel.ack(message) does not return a promise or callback.

### ISSUE THREAD

**Issue by s84** [squaremo/amqp.node#167]
http://www.squaremobius.net/amqp.node/doc/channel_api.html

This says `channel.ack` accepts a callback or promise.

   Uncaught TypeError: Cannot call method 'then' of undefined

**Comment by squaremo** [comment]
> This says channel.ack accepts a callback or promise

Hmmmmnnn ah! Because the title immediately above says "Promises and callbacks"? What I meant there was that both of the flavours of API (promises and callbacks) have the same method `#ack`, which doesn't take a callback and doesn't return a promise. Some of the methods differ between the APIs, and I've labelled the different versions "Promises" and "Callbacks" to distinguish them.

I should be clearer -- perhaps it should say "Promises API", "Callback API", or "Either API" in the title, what do you think?

**Comment by s84** [comment]
You are always quick to reply. Thanks for that.

I can see how this is in the promise api because it uses promises but returns undefined, but how is this in the callback api.

What's the motivation for not returning a promise or a callback. Does the server not give us anything?

As for the promise api saying it returns undefined is enough. I don't still don't see how it's a candidate for the callback api.

Any help is appreciated.

**Comment by s84** [comment]
I forgot that the callback/promise apis are literally different things and are required different; ignore respectively.

**Comment by michaelklishin** [comment]
There is no response for `basic.ack` in the protocol. What would such a promise consider a successful or failed operation?

**Comment by s84** [comment]
If there is no response then there is no need for asynchrony. So I guess it's up to the client to catch any errors from `channel.ack(message)`.

**Comment by govorovvs** [comment]
@squaremo @s84

**Comment by squaremo** [comment]
> Ack should return Promise and handle latency logic

The article you linked to is talking about acknowledgements from the broker to the client, of messages _sent by the client_. These are handled by `ConfirmChannel`s, and are distinct from acknowledgements of messages _sent by the broker_.

**Comment by figo2264** [comment]
> @squaremo @s84
> We have recently been migrating to this library to support a processing queue. One of the features we are trying to support is a clean shutdown (wait for all current recieved messages to be processed before shutdown). To do that, we capture the shutdown request and wait for the current message to be ack'd and then call close on the connection. This is causing a problem I think is related to this issue. The messages are staying in the queue even after calling ack! My guess at the moment is that the channel or connection have not flushed yet and the server hasn't received the ack. Adding a 1ms timeout after the ack and before closing the connection seems to solve the issue, but that seems like a brittle solution to me. Do you have any recommendations?
> 
> As a note: we have long processing times on some of our messages, so letting another consumer pick up the message after disconnect is not a good option. Thanks!

I also have a similar issue.
After I sent ack to queue, I made it wait for 3 seconds. Then tried to close the channel.
However, the ack action intermittently fails because of the close channel action. 

Is there any way to confirm that the message on the queue is gone after ack is delivered?
