### ISSUE TITLE
Subscribing no existing QUEUE (connection_closed_abruptly)

### ISSUE THREAD

**Issue by jgato** [squaremo/amqp.node#175]
I have a problem (I think I also had that using node-amqp, so I am making something wrong) when subscribing to not existing queues. 

If I try to subscribe to a non existing queue I will receive this in the promise reject:

```
[Error: Operation failed: BasicConsume; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'hello' in vhost '/'"]
```

and also this as a connection event error:

```
[Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'hello' in vhost '/'"]
```

I am happy with the promise reject message, but now with the connection closed.

At the same time the server log shows me:

```
=INFO REPORT==== 4-Aug-2015::11:16:19 ===
accepting AMQP connection <0.21954.0> (127.0.0.1:48156 -> 127.0.0.1:5672)

=ERROR REPORT==== 4-Aug-2015::11:16:19 ===
connection <0.21954.0>, channel 1 - soft error:
{amqp_error,not_found,"no queue 'hello' in vhost '/'",'basic.consume'}

=WARNING REPORT==== 4-Aug-2015::11:16:19 ===
closing AMQP connection <0.21954.0> (127.0.0.1:48156 -> 127.0.0.1:5672):
connection_closed_abruptly

```

Connection_closed_abruptly, regarding RabbitMQ documentation, is because the client is not closing correctly the connection. 

This is a basic code I am using:

``` javascript
var amqp = require('amqplib');


amqp.connect('amqp://user:pass@localhost').then(function (conn) {
    process.once('SIGINT', function () {
        conn.close();
    });

    conn.on('error', function (error){
        console.log(error);
        if(error.message.indexOf('Channel closed by server: 404') > -1) {  
            console.log("Channel closed by server");
        }
    })
    return conn.createChannel().then(function (ch) {


        var channel = ch.consume('hello', function (msg) {
            console.log(" [x] Received '%s'", msg.content.toString());
        }, {
            noAck: true
        });

        return channel.then(function (_consumeOk) {
            console.log(' [*] Waiting for messages. To exit press CTRL+C');
        });
    });
}).then(null, console.warn);

```

So: 
- The connection is been closed not correctly
- What if I dont want to close the connection? Ok, this request was wrong, but there are other tasks doing other things in the same connection that could continue working without problems. I will notify that the queue didnt exists, and thats all.

Many thanks in advance.

**Comment by michaelklishin** [comment]
In RabbitMQ terms

```
Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'hello'
```

is a **channel** exception, it does not render the connection unusable.

`connection_closed_abruptly` means that the client closed TCP connection without closing AMQP 0-9-1 connection. This is harmless but sometimes indicate unexpected errors in the client/app.

**Comment by jgato** [comment]
Ok, the subscription to a no existing queue is considered as en error command. But, I need to avoid closing the connection. Because this implies a reconnection and provoke problems with other tasks/workers playing in the same connection.

**Comment by michaelklishin** [comment]
@jgato the server will only close the channel. If you observe that a connection is closed or TCP connection is lost, it's indeed a client library bug (and a fairly serious one, I'd say).

**Comment by jgato** [comment]
Yes, the connection is also closed. Actually, when you receive the error:

```javascript

  conn.on('error', function (error) {
    console.log(error);
    if (error.message.indexOf('Channel closed by server: 404') > -1) {
      console.log("Channel closed by server");
    }
  })
```

It is too late... the connection has been closed.

**Comment by squaremo** [comment]
OK, what is happening here is that the channel emits an error event; because it is unhandled (there's no 'error' handler on the _channel_, just the connection), it gets thrown as an "unhandled error event". It so happens that this is within a `try ... catch ...` statement, and the catch block ends up emitting it as an 'error' on the connection. It's absolutely a bug, and I have struggled to come up with a good solution -- see #108 and #142.

There is a workaround in the meantime: install an 'error' event handler on the channel before you use it, even if it's a no-op handler. This will prevent the "unhandled error event" being thrown, and thus the error being bubbled up to the connection.

**Comment by krysalead** [comment]
Hi,
This is quite old but I felt in this issue as well. 
My solution was to use
```
ch.assertQueue(queue, { durable: false });
```
Before consuming
