### ISSUE TITLE
Calling connection.close may return a promise which never resolves

### ISSUE THREAD

**Issue by apechimp** [squaremo/amqp.node#181]
When calling `connection.close` on a connection which has error'd, a promise which never resolves is returned. To reproduce, execute the following and close the created connection via the RabbitMQ management plugin.

```javascript
var amqp = require('amqplib')
var conn = amqp.connect()

conn.then(function (connection) {
  connection.on('error', function () {
    console.log('error')
    connection.close()
    .then(
      console.log.bind(console, 'ok'),
      console.log.bind(console, 'fail')
    )
  })
})

setInterval(function () {}, 1000)
```

You'll see that `ok` or `fail` are never logged which indicates that `connection.close()` never resolved.

Admittedly, this example is a bit contrived, but it's just a simplification of what we do in production: listen to `uncaughtException` and attempt to close any connections before the process exits.

**Comment by squaremo** [comment]
(github auto-closed this because I mentioned the issue in the commit message -- please reopen if you find it does not solve your problem!)
