### ISSUE TITLE
Can we have a demo tutorial showing priority queue implementation in amqp.node.

### ISSUE THREAD

**Issue by girirajsharma** [squaremo/amqp.node#182]
RabbitMQ has priority queue implementation in the core as of version 3.5.0. We can declare priority queues using the x-max-priority argument. This argument should be an integer indicating the maximum priority the queue should support.
We can then publish prioritised messages using the priority field of basic.properties. Larger numbers indicate higher priority.  For more information click, [ here!](https://www.rabbitmq.com/priority.html).

**Comment by michaelklishin** [comment]
@girirajsharma see https://github.com/squaremo/amqp.node/pull/180#issuecomment-137510974. Feel free to submit a PR that creates such as example. This is open source software, after all.

**Comment by girirajsharma** [comment]
@michaelklishin sounds cool. Thanks for the help.

**Comment by squaremo** [comment]
`priority` is mention in the API docs section on `Channel#publish`, although it wrongly says that RabbitMQ will ignore it. It's one of the options you can pass as a field in the `options` argument. For example,

    ch.publish('foo-exchange', 'bar-routing', content, {priority: 10});

I'll take this bug report to indicate that I should update the docs :)

**Comment by girirajsharma** [comment]
Thanks. Seems that would work for me and hopefully will issue PR's for the same :)

**Comment by squaremo** [comment]
> I'll take this bug report to indicate that I should update the docs :)

OK, docs updated -- have a look under "publish" http://www.squaremobius.net/amqp.node/channel_api.html#channel_publish

**Comment by girirajsharma** [comment]
@squaremo cool :+1:
