### ISSUE TITLE
Support for Node v4.0.0

### ISSUE THREAD

**Issue by nordisk** [squaremo/amqp.node#183]
Hi there,

I get a warning when I try to install it on the latest stable node due to this:

```
"engines": {
    "node": ">=0.8 <0.13 || ^1"
  },
```

**Comment by ZoRDoK** [comment]
+1

**Comment by jcollum** [comment]
:+1: to be fair there's probably hundreds of packages having this issue right now

**Comment by nordisk** [comment]
@jcollum Fair point, really. It was just this one for us on fairly big project. That been said: It was just so that it is tracked – the lib is working very well.

**Comment by darrellodonnell** [comment]
@jcollum hundreds? I'm betting thousands! :-)

**Comment by carlhoerberg** [comment]
make a pull request so that @squaremo just can merge it

**Comment by connec** [comment]
This was [fixed](https://github.com/squaremo/amqp.node/commit/b4954206c34425498f8a759e9f6180f78037c87b) and released 2 weeks ago.  If you still see this warning you need to use amqp.node@0.4.0.

That said, it isn't mentioned in the changelog, and the README still specifies "Node.JS v0.8, v0.9, v0.10, v0.11, v0.12, and io.js v1.x".

**Comment by squaremo** [comment]
> That said, it isn't mentioned in the changelog, and the README still specifies "Node.JS v0.8, v0.9, v0.10, v0.11, v0.12, and io.js v1.x".

My bad! I'll update that, and put a message saying "upgrade to 0.4" (I expect a fair few people have quite reasonably pinned amqplib to 0.3.x).

**Comment by squaremo** [comment]
OK changelog and README updated. If you either

    npm install amqplib@0.4.0

or update your package.json dependencies, you should get a release supporting Node.JS 4.0.
