### ISSUE TITLE
waitForConfirms is not in the api documentation

### ISSUE THREAD

**Issue by kevinsimper** [squaremo/amqp.node#187]
`waitForConfirms` is not mention in the online api docs?

http://www.squaremobius.net/amqp.node/doc/channel_api.html

And they even use setTimeout, which is bad practice, instead of using `waitForConfirms`.

http://www.rabbitmq.com/tutorials/tutorial-two-javascript.html

**Comment by kevinsimper** [comment]
I have seen it is because it has not been published? The last version was published in marts? That is very long time since!

**Comment by squaremo** [comment]
> waitForConfirms is not mention in the online api docs?

Yeah -- I don't think it's in a release yet. I have not had much time lately (for the last year, really) to attend to amqplib so it's been in fits and starts.

It seems that `waitForConfirms` is working OK for people that know about it though, so I think I can safely document it :)

**Comment by squaremo** [comment]
Docs added -- thanks for reminding me :+1:

**Comment by kevinsimper** [comment]
Cool :smile:
