### ISSUE TITLE
Error propagation issue

### ISSUE THREAD

**Issue by sandytrinh** [squaremo/amqp.node#195]
Hi there,

I'm having an issue dealing with a thrown error from one of my functions in the promise chain. Below is an example code to replicate my scenario:

```
amqp.connect(url).then((conn) => {
    conn.createChannel().then((channel) => {
        channel.assertExchange()
        .then(() => {
            console.log('success!')
        }, (err) => {
            console.log('Error handler 1');
        })
        .then(null, (err) => {
            console.log('Error handler 2');
        });

    }, (err) => {
        console.log('Error handler 3');
    }).then(null,(err) => {
        console.log('Error handler 4');
    });

}, (err) => {
    console.log('Error handler 5');
}).then(null, (err) => {
    console.log('Error handler 6');
});
```

Similar to my function `channel.assertExchange()` throws an error because the required parameters are missing, therefore I expect the thrown error to be captured in the first error handler that outputs "Error handler 1", but instead it outputs "Error handler 4". Is this the intended behaviour or is it a bug in `amqplib`?

**Comment by squaremo** [comment]
Hi -- so I can run the example, what derivative of JS is it?

**Comment by sandytrinh** [comment]
Opps just noticed I have a mixture of normal functions and arrow functions. I've updated that. It's for Node.js v4+.

**Comment by squaremo** [comment]
Ah it's ECMA 6 syntax -- I am so not up with things!

Right, `channel.assertExchange()` throws an exception because it doesn't get expected parameters; none of the handlers in the `.then` on its result will ever get invoked.

Are you saying that `assertExchange` should *always* return a promise, even if that promise is immediately rejected with an IllegalArguments error (say)? I can see an argument for that. On the other hand, what if your program was:

```js
amqp.connect().then(conn => {
  conn.createChannel().then(channel => {
    JSON.parse("not json");
    channel.assertQueue('foo').then(null, handlerOne);
  }).then(null, handlerTwo)
});
```

Which handler would you expect to be invoked?

Callbacks and promises just make error handling awful, don't they.

**Comment by sandytrinh** [comment]
Hi @squaremo,

I'm very new to promises so I wouldn't have the best knowledge to make the correct call, but based on your example code, I would imagine `handlerTwo` would be invoked capturing the `JSON.parse` error.

Ditto on error handling for callback and promises, they can be very confusing!

I initially thought that `channel.assertExchange` should capture the thrown error and return a rejected promise to the handler, but seeing your example, I think the way you have it is better. As technically the error thrown is a programer error rather then an operational error.

**Comment by squaremo** [comment]
> I'm very new to promises so I wouldn't have the best knowledge to make the correct call, but based on your example code, I would imagine handlerTwo would be invoked capturing the JSON.parse error.

Spot on -- it's really the same situation, that the exception is thrown in the scope of the outer handler, but promises make this difficult to see when scanning the code.

There's a callback-based API, if you're more used to seeing callbacks:

```js
amqp.connect((err, conn) => {
    // .. check err ..
    conn.createChannel((err, channel) => {
        // .. check err ..
        channel.assertExchange((err, ex) => ...);
    });
});
```

It's clearer, I think, that the whole thing will unravel when the assertExchange call fails.

**Comment by squaremo** [comment]
> that the whole thing will unravel

Ha, except it won't of course -- an error event will bubble up somewhere. Doh!

**Comment by sandytrinh** [comment]
Thanks for the explanation, this definitely clear things up a lot!

I'll continue on with promises. Practice makes perfect right? :)

On another note, this is an example code from your documentation:

```
amqp.connect().then(function(conn) {
    // Everything ok, but ..
    throw new Error('SNAFU');
}, function(err) {
    console.error('Connect failed: %s', err);
}).then(null, function(err) {
    console.error('Connect succeeded, but error thrown: %s', err);
});
```

Does the other promise based API have the same error handling construction? e.g.

```
conn.createChannel()
.then( function (ch) {
    // succcess
}, function (err) {
    // channel connection error
})
.then(null, function (err) {
    // handle application error
});
```

**Comment by sandytrinh** [comment]
I can confirm all promise based api has the same error construction as the example above.
