### ISSUE TITLE
Empty message when receiving a from a fanout exchange

### ISSUE THREAD

**Issue by mfrachet** [squaremo/amqp.node#196]
Hi,

I m actually studying AMQP through RabbitMQ and amqp.node and I m having a little problem.

Actually, I m following this tutorial : https://www.rabbitmq.com/tutorials/tutorial-three-javascript.html

My consumer code look like  this : 

```
let consumer1 = function(conn){
  let channel = conn.createChannel();
  channel.then((ch)=>{
    ch.assertExchange(ex, 'fanout', {durable: false});

    ch.assertQueue('', {exclusive: true}).then((q)=>{
      console.log(" [*] Waiting for messages on consumer 1");

      ch.bindQueue(q.queue, ex, '');

      return ch.consume(q.queue);
    }).then((msg)=>{
      console.log(" [x] %s", msg);
    });
  });
}
```

And my publisher like this one : 

```
let publisher = function(conn){
  let channel = conn.createChannel();
  channel.then((ch)=>{
    let exchange = ch.assertExchange(ex, 'fanout', {durable: false});
    exchange.then(()=>{
      ch.publish(ex, '', new Buffer('Hello World!'));
    });
  });
}
```

The message is well sent, but when I try to log the received message in the consumer, I only have the consumerTag displayed, not the message content.

Is there anything I make wrong ?

**Comment by squaremo** [comment]
The return value of `ch.consume` is the response to the consume RPC, not a message. `ch.consume` takes a callback for messages, as a parameter: http://squaremo.github.com/amqp.node/channel_api.html#channel_consume

**Comment by squaremo** [comment]
I may have the syntax a bit wrong, but I think you want something like:

```
let consumer1 = function(conn){
  let channel = conn.createChannel();
  channel.then((ch)=>{
    ch.assertExchange(ex, 'fanout', {durable: false});

    ch.assertQueue('', {exclusive: true}).then((q)=>{
      console.log(" [*] Waiting for messages on consumer 1");

      ch.bindQueue(q.queue, ex, '');

      return ch.consume(q.queue, (msg)=>{
        console.log(" [x] %s", msg);
      });
  });
}
```

Note how the consumer function moves into being an argument of `ch.consume(...)`.
