### ISSUE TITLE
Heartbeat Error With No Heartbeat Set

### ISSUE THREAD

**Issue by bendytree** [squaremo/amqp.node#203]
I'm on `amqplib 0.4.0`, `node 0.10.26` connecting like this:

    var amqp = require('amqplib/callback_api');
    amqp.connect(connectionString, cb);

Suddenly (after weeks of it working fine) I'm getting `Heartbeat timeout` errors:

    Error: Heartbeat timeout (process.uncaughtException)
    at Heart.<anonymous> (/mnt/app/node_modules/amqplib/lib/connection.js:424:26)
    at Heart.EventEmitter.emit (events.js:92:17)
    at Heart.runHeartbeat (/mnt/app/node_modules/amqplib/lib/heartbeat.js:88:17)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

My provider asked what heartbeat interval I'm using, but I'm not sure. 

[The docs](http://www.squaremobius.net/amqp.node/channel_api.html) say the default is no heartbeat but I think [this comment](https://github.com/squaremo/amqp.node/pull/83#issuecomment-50989634) says it will be defaulted by the server. Clearly there must be a heartbeat since I'm getting errors.

So what is the default heartbeat?

Bonus points for any advice on a good heartbeat and/or debugging this issue.

**Comment by carlhoerberg** [comment]
Reconnect on error: `conn.on("error", function(e) { log(e); setInterval(restart, 5000); }`

**Comment by bendytree** [comment]
Perfect - thank you.

For anyone else as dumb as me, I was able to confirm that the heartbeat interval is taken from the server if left as `0`.

**Comment by egemon** [comment]
I am as dumm as u - thanks!)
