### ISSUE TITLE
Get total messages count in queue

### ISSUE THREAD

**Issue by Kurtas** [squaremo/amqp.node#207]
Hi, 

 I would like to know, how to get actual total message count in queue. 
When I use ```Channel#checkQueue``` then I get only count of messages what wasn't delivered to consumer, but I need to have all messages in queue (non delivered + non ack). Like a values in total column in RabbitMQ web admin page, is it possible?

Thanks a lot!

**Comment by michaelklishin** [comment]
@Kurtas it is only possible via HTTP API which provides a lot of queue stats. See http://www.rabbitmq.com/management.html and https://raw.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_5_6/priv/www/api/index.html.

**Comment by Kurtas** [comment]
Good idea, thanks!
