### ISSUE TITLE
Usage under AngularJS

### ISSUE THREAD

**Issue by rtubio** [squaremo/amqp.node#208]
Can amqp.node be included in an Angular JS application or is it strictly restricted to be used within Node.js? I know that both the Node.js and Angular JS environments are JavaScript based, but I would like to now whether amqp.node requires specifically to be used from within Node.js.

**Comment by squaremo** [comment]
amqp.node uses a few Node.JS-specific things that may not be available in a browser -- off the top of my head, the Buffer class and the net and ssl libraries. Much of the machinery is portable, but I think the use of Buffer especially would be difficult to disentangle.

**Comment by rtubio** [comment]
Thanks for the help @squaremo : is there any pure JS or AngularJS library for AMQP?

**Comment by michaelklishin** [comment]
@rtubio have you considered using Web STOMP instead? It's got a major revamp in upcoming RabbitMQ 3.6.0, too.

I'm not aware of any other JS clients that I'd consider to be reasonably mature and maintained.

**Comment by rtubio** [comment]
Yes, I am aware of the Web STOMP option. I was just looking for a way in which to directly establish a communication with a RabbitMQ server, so that I do not need to configure any additional server like the STOMP one. I know that it is pretty straightforward, but the less the components, the easier it is to maintain an application...

**Comment by rtubio** [comment]
Has anybody ever used Browserify to port amqp.node library to a client-side Javascript application?
