### ISSUE TITLE
Channel.Ack geting failed 

### ISSUE THREAD

**Issue by SantoshSKhavekar** [squaremo/amqp.node#209]
Hi,

I am using amqplib for message queue with node.js in my project.what i am trying is publishing three messages into single Queue and i ma consuming those messages successfully.
But my problem is if I try to push 4 messages into single queue and In consumer side while consuming those messages I am passing {noAck:false} again in that i will reverse those messages in array  and i will requeue with ack.
after that I am getting "Cannot read property 'deliveryTag' of undefined".

publisher:

ch.assertExchange(ExchangeName, "direct", {durable: true});
   		        ch.assertQueue('hello3', {durable: false});
                ch.publish(ExchangeName, rountingkey1, content = new Buffer("Hello World from MAIL1!"), options = {deliveryMode: 2},  function(err, ok) {
   		         	            if (err != null) {
   		         	                console.error("Error: failed to send message\n" + err);
   		         	            }
   		         	            console.log("Pushed 'Hello World1 by Send Email.");
   		         	          setTimeout(function() { conn.close(); process.exit(0) }, 5000);
   		         	        });
  ch.publish(ExchangeName, rountingkey1, content = new Buffer("Hello World from MAIL2!"), options = {deliveryMode: 2}, function(err, ok) {
    	            if (err != null) {
    	                console.error("Error: failed to send message\n" + err);
    	            }
    	            console.log("Pushed 'Hello World1 by Send Email.");
    	            setTimeout(function() { conn.close(); process.exit(0) }, 5000);
    	        });      		    
             ch.publish(ExchangeName, rountingkey1, content = new Buffer("Hello World from MAIL3!"), options = {deliveryMode: 2}, function(err, ok) {
 	            if (err != null) {
 	                console.error("Error: failed to send message\n" + err);
 	            }
 	            console.log("Pushed 'Hello World1 by Send Email.");
 	            setTimeout(function() { conn.close(); process.exit(0) }, 5000);
 	        }); 

Consumer:

var Queuename="hello3";
var rountingkey1="Mail";
var ExchangeName="testEx";
var arr=[];
var Reverse=[];
 ch.consume(Queuename, ReverseMes, {noAck: false}); 
		       function ReverseMes(mess){
		    	   arr.push(mess.content.toString());  			
	    			 Reverse=arr.reverse();	
	    			 for(var i=0;i<Reverse.length;i++){
	    				// ch.sendToQueue(Queuename,new Buffer(Reverse[i]),{noAck: true});
	 		    		ch.ack(Reverse[i]);
	 		    		console.log(Reverse[i]);
	 		    	}	
		       };
    	     }); 

please suggest me.
Thank in advance.

**Comment by michaelklishin** [comment]
1. You are trying to ack a delivery tag that doesn't come from the delivery. Even if that works some of the time, that's a terrible idea: using an unknown tag will result in a channel exception.
2. You cannot re-queue with `basic.ack`, only with `basic.nack` or `basic.reject`.

**Comment by SantoshSKhavekar** [comment]
Thank you Michaelklishin.Hope you got my issue so please can you help me to do with basic.nack or basic.reject.

**Comment by michaelklishin** [comment]
@SantoshSKhavekar I don't understand what the intent is but the two points above cover two key mistakes: you don't use a delivery tag from an actual delivery, and `basic.ack` is not a method that can re-queue. See [RabbitMQ tutorial 2](http://www.rabbitmq.com/getstarted.html) if you are not sure about how acknowledgements work.

Please take it from there, you have all the important points mentioned.
