### ISSUE TITLE
Probably missing support for headers exchange

### ISSUE THREAD

**Issue by evolic** [squaremo/amqp.node#210]
Dear AMQP Node Library Team,

I am writing an article about RabbitMQ, where I chose amqplib as a "driver" to use it with Node.js
I have some problems with using header exchange.

I cannot find anything about this kind of exchange, neither in examples, nor in the documentation, nor in the source code.

Am I right it is not supported yet?

--
Best regards,
Tomasz Kuter

**Comment by keatz55** [comment]
+1

**Comment by squaremo** [comment]
Hello @evolic! You were correct, there was no help here on using a headers exchange. Doing so just uses standard methods, albeit in a very particular way, so it is possible.

You and @keatz55 prompted me to write an example: https://github.com/squaremo/amqp.node/blob/master/examples/headers.js. I hope it helps show the way.

**Comment by keatz55** [comment]
Thanks Michael!

**Comment by evolic** [comment]
Thank you Michael! I am closing this issue.
