### ISSUE TITLE
x-match functionality not working with headers exchange

### ISSUE THREAD

**Issue by keatz55** [squaremo/amqp.node#211]
First of all I just want to say great work with this repo,

I am using v0.4.0. I have tried to use 'x-match':'any'  every which way in all of the following argument locations. By "every which way," I mean individually or all together.  I could be way off here, but shouldn't 'x-match': 'any' work at one of these locations?

```
var ok = ch.assertExchange(exchange, type, {durable: true,match:'any','x-match':'any',arguments:{'x-match':'any',match:'any'}});
...
```

```
ch.assertQueue('', {exclusive: true,match:'any','x-match':'any',arguments:{'x-match':'any',match:'any'}});
...
```

```
ch.bindQueue(queue,exchange,routingKey, {type: 'create',match:'any','x-match':'any',arguments:{'x-match':'any',match:'any'}})
...
```

```
ch.consume(queue, handleResponse, {noAck: false,match:'any','x-match':'any',arguments:{'x-match':'any',match:'any'}});
...
```

**Comment by keatz55** [comment]
Never mind It works!  I finally put in the right combo after tirelessly searching through the API docs and seeing how implementation works with other amqp packages.  I finally got the header to work with the following location of the x-match:
```
ch.bindQueue(queue,exchange,routingKey, {
	'x-match': 'all',
	messageType: 'create',
  	email: true
});
```

**Comment by squaremo** [comment]
Oof! Yes, sorry there wasn't any guidance on using headers exchanges. It's not very clear in the AMQP specification, let alone here. Thanks for bringing it up -- I wrote an example, for future visitors: https://github.com/squaremo/amqp.node/blob/master/examples/headers.js

**Comment by keatz55** [comment]
Thanks Michael! You're the man!
