### ISSUE TITLE
Support for Node v5.x.x

### ISSUE THREAD

**Issue by leohihimax** [squaremo/amqp.node#212]
When will amqp support node v5.x.x ?
```
"engines": {
    "node": ">=0.8 <4 || ^4"
  }
```

**Comment by WiReD-** [comment]
+1

**Comment by mdrobny** [comment]
+1

**Comment by melalj** [comment]
+1

**Comment by melalj** [comment]
@squaremo It would be awesome if you could release a new version regarding the commit: https://github.com/squaremo/amqp.node/commit/ce651c6bb5033362550900478e117ba7aac4f9c6

Thanks!

**Comment by squaremo** [comment]
Hello all,

I have released a version 0.4.1, which adds tests for NodeJS 5.5 to the Makefile and .travis.yml, and expands the supported engines in package.json.

Sorry for taking my time over this -- I have had lots of other busyness for a while.
