### ISSUE TITLE
x-delay support

### ISSUE THREAD

**Issue by rodriguise** [squaremo/amqp.node#214]
https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/

Is x-delay support in the roadmap? It would be nice to be able to publish with delay.

**Comment by michaelklishin** [comment]
You already can, just like you can use any other feature that relies on optional arguments.

**Comment by rodriguise** [comment]
Except it doesn't work:

    options = { 'x-delay': 5000 };  // delay for 5s
    ch.sendToQueue(this.name, new Buffer(payload), options);

The options are just ignored.

**Comment by rodriguise** [comment]
Plugin only supports exchanges. closing..

**Comment by sudhirbitsgoa** [comment]
Is this still not supported?

**Comment by squaremo** [comment]
@sudhirbitsgoa To use the plugin you have to create an exchange of a particular kind, whereas the example given above sends directly to a queue (i.e., not through an exchange created via the plugin).

A rough translation of the blog post example is:

```
channel.assertExchange('my-exchange', 'x-delayed-message', {'x-delayed-type': 'direct'});
// then ...
channel.publish('my-exchange', 'my-queue', bytes, {headers: {'x-delay': 5000}})
```
