### ISSUE TITLE
RPC: Multiple Consume functions on a queue

### ISSUE THREAD

**Issue by ebaizel** [squaremo/amqp.node#215]
I am following the [client RPC example](https://github.com/squaremo/amqp.node/blob/master/examples/tutorials/rpc_client.js) and I'm getting stuck making this work across multiple client requests.

In the `consume` method it takes a `function(msg)` as the callback and the function looks like this:

```
function maybeAnswer(msg) {
   if (msg.properties.correlationId === corrId) {
      answer.resolve(msg.content.toString());
   }
}
```

When I run several RPC call over this, the `maybeAnswer` function only uses the first `corrId` in its check.  Another way to put it, subsequent requests generate their own `corrId` from the line:

`var corrId = uuid();`

But inside `maybeAnswer` this corrId is never checked for, although it is correctly being used as the `correlationId` when sending to the queue.

The net effect is a timeout because the `if (msg.properties.correlationId === corrId)` check never becomes true for calls beyond the first.

When I make multiple `ch.consume` calls, what is happening under the covers with the callback functions?  Are they added to an array of callback functions that it loops through to verify when the request has completed?  Do I need to remove a callback function once its request/correlationId has been fulfilled?  Otherwise it seems it would continue checking indefinitely.

Thanks!

**Comment by cressie176** [comment]
Probably too late to be any use, but the problems are likely to be

1. You've made a mistake in your code and the ```corrId``` in your maybeAnswer isn't what you think it is.
2. You're auto acknowledging the message, so even when it's not answered it's being dropped
3. You have prefetch = 1 and not auto acknowledging the answer so only 1 message is ever being checked.

You might also want to look at https://github.com/guidesmiths/stashback - it's a library for doing what I think you want, with examples using amqplib.
