### ISSUE TITLE
Setting policies

### ISSUE THREAD

**Issue by marczahnlls** [squaremo/amqp.node#216]
Hi,

I try to set up an exchange resp. queue with HA for cluster usage. Obviously I am not able to provide the correct arguments. Is this a bug or do I make a mistake all the time?

**Comment by michaelklishin** [comment]
@marczahnlls please post your code, otherwise it is impossible to tell anything. I'm not sure how policies fit into this but policies can be only managed using `rabbitmqctl` and the HTTP API, neither of which are covered by this library.

**Comment by marczahnlls** [comment]
Hi Michael,

ah ok - This could be the reason. Nevertheless, the snippet is:
```
...
channel.assertQueue(
  queueConfig.name,
  {
    durable: queueConfig.durable != undefined ? queueConfig.durable : true,
    arguments: queueConfig.arguments != undefined ? queueConfig.arguments : {}
  }
);
...
```
queueConfig.arguments:
```
arguments: {
  'x-ha-mode': 'all'
}
```

**Comment by michaelklishin** [comment]
The code above looks reasonable to me.

**Comment by michaelklishin** [comment]
What the above defines is not a policy, however, it's optional queue arguments. Policies define those, too, in a centralised manner (and have lower priority compared to client-provided arguments like above).

**Comment by marczahnlls** [comment]
So there is no possibility to set a policy with amqp.node?

**Comment by michaelklishin** [comment]
@marczahnlls see above. You can set arguments. You can't manage policies (that also control arguments but for more than 1 queue at a time).

**Comment by marczahnlls** [comment]
Ok. Thank you for your quick support :+1:

**Comment by michaelklishin** [comment]
@marczahnlls np. Would you mind closing this issue?
