### ISSUE TITLE
Consume as a promise

### ISSUE THREAD

**Issue by alantrrs** [squaremo/amqp.node#221]
Looks like ``ch.consume`` is still using a callback in the Promise API, shouldn't it be a promise instead? 
I would expect to use it like this: ``ch.consume(q).then(function (msg) {})``

**Comment by alantrrs** [comment]
nevermind, I understand why this is now. :+1:

**Comment by dynnamitt** [comment]
Help me understand pls?

**Comment by alantrrs** [comment]
I don't remember exactly but I think it is because if it were implemented as a promise ``ch.consume(q).then(function (msg) {})``  would only resolve once, so it would only consume the first message. As a callback it can be called on every message.

**Comment by squaremo** [comment]
@dynnamitt The promise return value is for the reply to the `consume` RPC, which gives you a tag you can use to cancel the `consume` later. The callback _argument_ is invoked for each message.

**Comment by dynnamitt** [comment]
ok.
Maybe just return a stream/eventemitter would be better solution than a callback arg.. 
just a though 



Sendt fra min Samsung-enhet

-------- Opprinnelig melding --------
Fra: Michael Bridgen <notifications@github.com> 
Dato: 30.04.2016  11:50  (GMT+01:00) 
Til: "squaremo/amqp.node" <amqp.node@noreply.github.com> 
Ko: Kjetil Flovild-Midtlie <kjetil.midtlie@gmail.com>, Mention <mention@noreply.github.com> 
Emne: Re: [squaremo/amqp.node] Consume as a promise (#221) 

@dynnamitt The promise return value is for the reply to the consume RPC, which gives you a tag you can use to cancel the consume later. The callback argument is invoked for each message.

**Comment by squaremo** [comment]
> Maybe just return a stream/eventemitter

It's occurred to me, yeah. One day I may write `consumeAsStream` (and perhaps `publishAsStream`, though that's a bit trickier). Anyway, hope the above helped explain what was going on.

**Comment by dynnamitt** [comment]
Yes, thanks
