### ISSUE TITLE
ECONNRESET when using SSL

### ISSUE THREAD

**Issue by gwjames** [squaremo/amqp.node#222]
Hi,

When calling:

require("amqplib").connect("amqps://****

I receive the following:

Potentially unhandled rejection [1] Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:544:26)

using Node 4.2.4 or 5.4.1.

The exact same code using amqp:// works perfectly. Only the SSL part fails. SSL connections using the RabbitMQ C library work correctly.

Using a really old Windows node version (0.10.28) works correctly but not the latest versions of node.

I followed the certificate generation instructions on:

https://www.rabbitmq.com/ssl.html

to generate the certificates.

Is there any other information I can provide? I'm trying to figure out if this is a Node bug or if it can be fixed in amqplib.

If I enable debugging on net, I get:

"onread -54" on mac

and 

"onread -4077" on windows

although I'm not sure what these numbers indicate.

**Comment by michaelklishin** [comment]
Please specify the exact URI you use (with edited out credentials and hostname) and post RabbitMQ log files. It is not clear whether you are trying to connect to the correct port, for example.

**Comment by gwjames** [comment]
The RabbitMQ log shows:

=ERROR REPORT==== 19-Jan-2016::15:10:44 ===
Error on AMQP connection <0.7509.0>:
{ssl_upgrade_failure,
    {{function_clause,
         [{tls_v1,enum_to_oid,[28],[{file,"tls_v1.erl"},{line,404}]},
          {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
              [{file,"ssl_handshake.erl"},{line,1653}]},
          {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
              [{file,"ssl_handshake.erl"},{line,1653}]},
          {ssl_handshake,dec_hello_extensions,2,
              [{file,"ssl_handshake.erl"},{line,1653}]},
          {tls_handshake,decode_handshake,3,
              [{file,"tls_handshake.erl"},{line,182}]},
          {tls_handshake,get_tls_handshake_aux,3,
              [{file,"tls_handshake.erl"},{line,153}]},
          {tls_connection,next_state,4,
              [{file,"tls_connection.erl"},{line,454}]},
          {gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,505}]}]},
     {gen_fsm,sync_send_all_state_event,[<0.7510.0>,{start,5000},infinity]}}}

The SSL versions in my config are as follows:

 {ssl, [{versions, ['tlsv1.2', 'tlsv1.1']}]},

The code to connect is:

var opts = {
  cert: fs.readFileSync('cert.pem'),
  key: fs.readFileSync('key.pem'),
  ca: [fs.readFileSync('cacert.pem')]
};

var rabbitOpen = require("amqplib").connect("amqps://" + encodeURIComponent(username) + ":" + encodeURIComponent(password) + "@" + hostname + "?heartbeat=" + heartbeat, opts);

**Comment by michaelklishin** [comment]
@gwjames upgrade your Erlang version to at least 17.5 (only RabbitMQ 3.5.7+ can run on 18.x).

**Comment by gwjames** [comment]
Great thanks that fixed the issue!
