### ISSUE TITLE
SSL connection with rabbitmq is not working with node(v5.4.1).

### ISSUE THREAD

**Issue by pradeepsecurifi** [squaremo/amqp.node#224]
I ran ssl.js in examples with my certificates.

Receiving this error from rabbitmq server

{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by michaelklishin** [comment]
That error is not from the server, it is from your client's TCP socket. It means the hostname/port it tried to connect to refused the connection: is RabbitMQ configured to use TLS on port 5671 (default)?

**Comment by pradeepsecurifi** [comment]
RabbitMq is running on port 5671 and ssl connection is working with node v0.12.0. But when i upgraded node to v5.4.1, it did not work either with  the current fix, node engine update to 5 (the commit was made 3 days ago) or with the version of  library I got from npm install.

**Comment by michaelklishin** [comment]
What's in RabbitMQ log files?

**Comment by michaelklishin** [comment]
Also, what Erlang version is used?

**Comment by pradeepsecurifi** [comment]
Erlang Version : R16B03

RABBITMQ ERROR LOG :
** Reason for termination = 
** {function_clause,[{tls_v1,enum_to_oid,
                             [28],
                             [{file,"tls_v1.erl"},{line,404}]},
                     {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
                                    [{file,"ssl_handshake.erl"},{line,1653}]},
                     {ssl_handshake,'-dec_hello_extensions/2-blc$^1/1-0-',1,
                                    [{file,"ssl_handshake.erl"},{line,1653}]},
                     {ssl_handshake,dec_hello_extensions,2,
                                    [{file,"ssl_handshake.erl"},{line,1653}]},
                     {tls_handshake,decode_handshake,3,
                                    [{file,"tls_handshake.erl"},{line,182}]},
                     {tls_handshake,get_tls_handshake_aux,3,
                                    [{file,"tls_handshake.erl"},{line,153}]},
                     {tls_connection,next_state,4,
                                     [{file,"tls_connection.erl"},{line,454}]},
                     {gen_fsm,handle_msg,7,
                              [{file,"gen_fsm.erl"},{line,505}]}]}

**Comment by michaelklishin** [comment]
This is the same thing as https://github.com/squaremo/amqp.node/issues/222 then. Upgrade Erlang to 17.5 or later.

**Comment by pradeepsecurifi** [comment]
Thanks, i appreciate your help.

**Comment by squaremo** [comment]
I should make note of this kind of thing in the SSL guide -- thanks for the report @pradeepsecurifi, and thanks for the diagnosis @michaelklishin.
