### ISSUE TITLE
x-message-ttl examples

### ISSUE THREAD

**Issue by molinto** [squaremo/amqp.node#228]
Any examples with delayed messages please?

Found this on headers: https://github.com/squaremo/amqp.node/blob/master/examples/headers.js

Good article but its in Ruby:
https://www.cloudamqp.com/docs/delayed-messages.html

Thanks

**Comment by michaelklishin** [comment]
You are confusing optional queue arguments with headers and headers exchanges, which route based on message headers.

See `options` in `Channel#publish`: https://github.com/squaremo/amqp.node/blob/master/lib/channel_model.js#L159.

**Comment by molinto** [comment]
You are correct, I'm totally confused what to do :(

Seen an example here too (but uses https://github.com/postwait/node-amqp):
https://bhelx.simst.im/articles/precisely-delaying-jobs-with-dead-letter-exchanges-in-rabbitmq/

**Comment by cressie176** [comment]
@molinto Rascal (built on top of amqp.node) can do that for you. See the [advanced example)[https://github.com/guidesmiths/rascal/blob/master/examples/advanced/config.js]

There's also an [experimental plugin](https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/) for rabbit MQ which does something similar.

**Comment by molinto** [comment]
Thank you
