### ISSUE TITLE
checkQueue is breaking checking a queue that is exclusive 

### ISSUE THREAD

**Issue by grahamjenson** [squaremo/amqp.node#231]
when executing `checkQueue` on an exclusive queue from a connection that is not the one that declared the queue, then I get this error 

```
Error: Channel closed by server: 405 (RESOURCE-LOCKED) with message "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue
```

I am not sure if it is possible to check an exclusive queue exists from outside the connection, but it would be useful.

**Comment by michaelklishin** [comment]
@grahamjenson exclusive queue can only be used from one connection by definition.

**Comment by grahamjenson** [comment]
Being used is fine, but is there an easy way to check that it exists from another connection. I could send a mandatory message to it and make sure it is not returned, but that seems a bit overkill to just ask if it exists.

**Comment by michaelklishin** [comment]
@grahamjenson the point of exclusive queues that only their declaring connection should ever use it. You can check if it exists from that connection using a passive `queue.declare`, just like with any other queue. Other connections should not worry about exclusive queues of other connections; if that's not the case, perhaps your queue should not be exclusive.

**Comment by grahamjenson** [comment]
Definitely should be exclusive. Was just writing tests to check that the queue exists at different points in the application lifecycle, and is easier to execute with a new connection that from the existing one.

checkQueue was working in the tests before I changed the queue type to be exclusive, so thought it might be an issue, but if it is not I will try the work around you suggested.

Cheers for the quick replies :)
