### ISSUE TITLE
Cancel a consumer.

### ISSUE THREAD

**Issue by bweston92** [squaremo/amqp.node#234]
In other languages such as PHP there is a `get` method where I can get a single message. However I cannot find it in this library. So I need to consume a temporary queue (I am awaiting RPC reply) and then need to stop consuming so I don't have lots of temporary queues.

Currently I have the following:
```
      let consumerTag = '';
      this.channel.consume(queue.queue, (rawMessage) => {
        this.channel.ack(rawMessage);
        const decodedMessage = JSON.parse(rawMessage.content.toString());
        deferred.resolve(matches);
        this.channel.cancel(consumerTag);
        this.channel.deleteQueue(queue.queue);
      }).then((temp) => {
        consumerTag = temp.consumerTag;
      });
```

**Comment by michaelklishin** [comment]
@bweston92 and what is your question?

**Comment by bweston92** [comment]
Would help wouldn't it, is this the best way of doing it? Is this the only way of doing it?

Also if I just delete a queue will this library stop consuming it?

**Comment by squaremo** [comment]
Hi @bweston92, there's [Channel#get](http://www.squaremobius.net/amqp.node/channel_api.html#channel_get); is that what you're looking for or have I misunderstood?

**Comment by bweston92** [comment]
@squaremo oh, thanks aha :D the JS library differs from another library I've used in another language where stuff like `Channel.get` is on a queue. Thanks for your time.
