### ISSUE TITLE
Using await reserved word in code

### ISSUE THREAD

**Issue by Kurtas** [squaremo/amqp.node#235]
Hi, 

 [here](https://github.com/squaremo/amqp.node/blob/master/lib/channel_model.js#L311) and [here](https://github.com/squaremo/amqp.node/blob/master/lib/connection.js#L151) you are using reserved word `await` ... I found this when I tried to bundle node app with Webpack and it crashed because of this

**Comment by squaremo** [comment]
I've replaced the uses of `await` in master branch. Do you mind trying it out? (If you don't want to have to clone the repo, you could wait for the next release to do so)

**Comment by daixtrose** [comment]
I am too unexperienced with mixing this w/ release. Any hints how to proceed?

When is the next release?

**Comment by spdionis** [comment]
@squaremo hasn't there been any new release?

**Comment by deanmckee** [comment]
This appears to still be a problem (using await reserved word).  Trying to use babel to do a build that is depending on your code errors out when encountering these:

SyntaxError: node_modules/amqplib/test/channel.js: await is a reserved word (33:27)
  31 |     pair.server.read(8); // discard the protocol header
  32 |     var s = util.runServer(pair.server, function(send, await) {
