### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by madhatter42** [squaremo/amqp.node#236]
Hi, I have a pretty straightforward consumer that picks up messages from a queue and passes them to a callback to perform some business logic. I'm running the consumer as a long-running process. What I'm finding is that whenever a new message comes in, a brand new connection is opened up with the broker. After a while, the pool of connections gets choked and we are unable to consume any more messages. Can somebody please help me debug this? Appreciate your help!

```
amqp.connect('amqp://localhost', function(err, conn) {
    if(err) { bail(err); }
    process.once('SIGINT', function() { if(conn) { conn.close(); } });
    conn.createChannel(function(err, ch) {
        if(err) { 
            conn.close();
            bail(err); 
        }
        var callback = function(msg) {
              // do something
        };    
        var q = 'mesl_receive_messages';
        ch.assertQueue(q, { durable: true }, function(err, ok) {
            if(err) { bail(err); }
            ch.consume(q, function(msg) {
                if(msg !== null) {
                    callback(msg);
                }
            });
        });
    });
});
```

(edited for formatting by squaremo)

**Comment by squaremo** [comment]
That code looks fine in itself.
You say "pool of connections"; where does this pool live? What is it that's invoking your script?

**Comment by madhatter42** [comment]
I assume that the RabbitMQ broker has a maximum number of allowed connections because after the consumer creates a certain number of connections, it stops consuming messages from the queue. I'm running the consumer script as a long running process (using [forever](https://www.npmjs.com/package/forever)).

**Comment by michaelklishin** [comment]
RabbitMQ does not have a maximum number of supported connections but realistically the OS and the amount of physical resources available limit how many connections a node can handle. See the [Networking guide](http://rabbitmq.com/networking.html) in the docs.

**Comment by madhatter42** [comment]
But any idea why the number of connections keeps increasing with every
incoming message?

On Saturday, March 19, 2016, Michael Klishin <notifications@github.com>
wrote:

> RabbitMQ does not have a maximum number of supported connections but
> realistically the OS and the amount of physical resources available limit
> how many connections a node can handle. See the Networking guide
> <http://rabbitmq.com/networking.html> in the docs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/squaremo/amqp.node/issues/236#issuecomment-198752472>
>


-- 
Best,

Madhav

**Comment by madhatter42** [comment]
Is there any way I can work around this? Is there a hook that I can use to safely exit from my script (and subsequently restart it)?

**Comment by michaelklishin** [comment]
@madhatter42 if the number of connections grows over time, this means your app(s) don't properly close them, and the heartbeat interval is higher than it should be in your case. With every client but PHP there is no justification for opening a new connection (or channel) for every message published.

**Comment by michaelklishin** [comment]
@madhatter42 @squaremo has a a good question that wasn't answered above: where does the "pool of connections" come from? If you use an external library for connection or application lifecycle management, I suspect that's where the problem is.

**Comment by madhatter42** [comment]
@michaelklishin the app is the code that I've provided above... do you see any reason it would open a new connection for every message? Re: the pool - I was under the impression that the RabbitMQ broker had a finite pool of connections but that doesn't seem to be the case. Perhaps the number of connections is limited by the OS in some way.

**Comment by squaremo** [comment]
> has a a good question that wasn't answered above: where does the "pool of connections" come from?

I think the "pool gets choked" is just a way of saying things slow down or stop working.

> do you see any reason it would open a new connection for every message?

Nope, not that I can see.

You said that you run this under `forever`, which I think means it'll get restarted if it crashes. Does forever log the crashes? That would be worth checking. (I assume that in the bit commented `// do something` your _actual_ code does something.)

**Comment by madhatter42** [comment]
@squaremo I'm running the script with forever in production. However, the issue with the script creating a new connection per message can be reproduced on my development environment by running the script with vanilla node - it doesn't crash at all. I'm checking the number connections using "rabbitmqctl list_connections".

**Comment by michaelklishin** [comment]
I don't see where in your code the connection is closed. Is `amqp.connect` supposed to do it after invoking the callback?

It would also help immensely to have RabbitMQ log file contents.

**Comment by madhatter42** [comment]
The connection isn't closed in the script - only on error. The callback basically does this:

`
            async.waterfall([
                function(callback) {
                    // Some logic to get user
                    callback(null, user);
                }, function(user, callback) {
                    // Some logic
                    callback();
                }
            ], function(err, results) {
                if(err) { 
                    ch.close();
                    conn.close();
                    bail(err);
                }
                ch.ack(msg);
            });
`

**Comment by madhatter42** [comment]
Nothing useful in the logs except an entry for the creation of the new connection:

=INFO REPORT==== 20-Mar-2016::20:44:34 ===
accepting AMQP connection <0.11889.20> (127.0.0.1:52000 -> 127.0.0.1:5672)

Here is a list of the connections returned by rabbitmqctl (51817 was the previous connection made by the consumer, 52000 was the new one created due to an incoming message):

Listing connections ...
guest	127.0.0.1	51817	running
guest	127.0.0.1	52000	running
guest	127.0.0.1	52003	running

**Comment by michaelklishin** [comment]
There are no abruptly or cleanly closed connections in the log. With localhost this pretty reliably suggests no processes terminate. So something must be starting multiple copies of this process.

**Comment by madhatter42** [comment]
There's definitely only one copy of the process in this case - I ran it
without forever here.

On Monday, March 21, 2016, Michael Klishin <notifications@github.com> wrote:

> There are no abruptly or cleanly closed connections in the log. With
> localhost this pretty reliably suggests no processes terminate. So
> something must be starting multiple copies of this process.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/squaremo/amqp.node/issues/236#issuecomment-199054105>
>


-- 
Best,

Madhav

**Comment by madhatter42** [comment]
Is there a way to have the script timeout if it receives no messages for a certain amount of time?

**Comment by squaremo** [comment]
Hi @madhatter42 

I can run the example script (with a `// do something` that logs the message then acks it), and send messages to that queue, and it behaves -- i.e., there's only ever one connection.

I also tried it with this callback, based on the one you posted:

```
var callback = function(msg) {
          async.waterfall([
            function(callback) {
              // Some logic to get user
              callback(null, {username: 'squaremo'});
            }, function(user, callback) {
              console.log(msg);
              callback();
            }
          ], function(err, results) {
            if(err) {
              ch.close();
              conn.close();
              bail(err);
            }
            ch.ack(msg);
          });
        };
```

with the same effect. If I provoke an error by changing this line:

```
              // Some logic to get user
              callback(new Error('foobar!'), null);
```

then it logs the error and exits, as expected. So I think there is something else going on, that is not to do with that script (or a subtle bug, perhaps). I can't see anything in the script that would make it open any more than one connection, so if you run it once, it should open at most one connection.

Perhaps silly questions, but worth ruling out some possibilities: are you definitely using this library _as released_, i.e., `npm install amqplib`? Are the connections that mount up definitely those opened by this script, and not by, for example, whatever is sending the messages?

**Comment by madhatter42** [comment]
Thanks for your help - I figured out what the issue was. My "// do something" logic was publishing messages to the queue as well. I used the same code as on your NPM page... didn't add any logic for cleaning up connections there.

```
// Publisher 
function publisher(conn) {
  conn.createChannel(on_open);
  function on_open(err, ch) {
    if (err != null) bail(err);
    ch.assertQueue(q);
    ch.sendToQueue(q, new Buffer('something to do'));
  }
}
```

**Comment by madhatter42** [comment]
One last question - what is the safest way to close the connection in this case? Is there a way to make sendToQueue synchronous? I've found that messages don't get published if I close the connection right after I call sendToQueue.

**Comment by squaremo** [comment]
> Is there a way to make sendToQueue synchronous?

If you're just sending one message then exiting, you can call `channel.close(function() { connection.close(); })`, which will mean the connection doesn't get closed until after the channel is closed, and that won't happen until the message has been received by RabbitMQ.

If you're sending continually, you can use confirmations: http://squaremo.github.io/amqp.node/channel_api.html#confirmchannel, and `channel.waitForConfirms(...)`.
