### ISSUE TITLE
Handshake terminated by server: 403

### ISSUE THREAD

**Issue by devilmengcry** [squaremo/amqp.node#237]
Handshake terminated by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."]

**Comment by pie6k** [comment]
@devilmengcry sadly you didn't tell what was your solution :) I have the same problem. Let me know if you remember how did you solve this

**Comment by KaranGauswami** [comment]
I had the same issue .
There can be two possible reasons for this . 

1.  Username and password is incorrect.
2.  Accessing RabbitMQ via guest user credentials

 If you are Accessing via remote you have to create new user from rabbitmqctl.

`rabbitmqctl add_user test password`
`rabbitmqctl set_user_tags test administrator`
`rabbitmqctl set_permissions -p / test ".*" ".*" ".*"`

And Accessed it using this line
`amqp://test:password@<IP>:5672`

Hope this helps.
