### ISSUE TITLE
Q: Are channel.reject(message, re-queue) calls 100% synchronous?

### ISSUE THREAD

**Issue by mateodelnorte** [squaremo/amqp.node#238]
Hi there. Thanks again for the great lib. 

I've got a question regarding channel.reject() calls and whether they're synchronous across the wire. It looks like the call to reject a message ends up calling https://github.com/squaremo/amqp.node/blob/30a346bc83f863c829324fb26be142d019018dd6/lib/connection.js#L527. The method is writing the message frame to the buffer, which assumably causes those bytes to go out over the wire - but there is no callback which could be fired when the message is fully sent. 

If our application logic is to terminally throw immediately after a channel.reject(message, requeue) call, how do we know the message has successfully been sent to the broker?

**Comment by michaelklishin** [comment]
There is no response for `basic.{ack,nack,reject}` in the protocol, so I don't see how it can be synchronous.

Your best bet is to close the channel before terminating.

**Comment by squaremo** [comment]
> If our application logic is to terminally throw immediately after a channel.reject(message, requeue) call

If you do an RPC on the channel, once that succeeds you know the `reject` has been received. A channel close, as suggested above, is a good choice, since it's also cleaning up before crashing.

**Comment by squaremo** [comment]
Hi @mateodelnorte, did you manage to get your code working?

**Comment by mateodelnorte** [comment]
I went with @michaelklishin's perspective to just take errors as a sign all things are borked, close the channel and cycle the process. To be honest, I don't know if closing the channel just hid a race condition that still existed, but it sounds like it's a game of cat and mouse given to use by the AMQP standard implementers at RabbitMQ. :D

**Comment by squaremo** [comment]
A bit of reassurance: if the channel closes successfully, everything prior was also successful.
