### ISSUE TITLE
Publish headers/message properties not being set on messages

### ISSUE THREAD

**Issue by ph0bos** [squaremo/amqp.node#239]
When publishing a simple message to an exchange the headers and message properties are not correctly set when using the following snippet:

```javascript
  var payload = { "foo": "bar" };

  connecton.createConfirmChannel(function(err, channel) {
    channel.assertExchange('my exchange', 'topic', { }, function(err, ex) {
      channel.publish(ex.exchange, '', new Buffer(JSON.stringify(payload), { persistent: true, headers: { "myKey": "myValue" } }));
      channel.waitForConfirms(function(err) {
        channel.close()
      });
    });
  });
```

The above result is monitored by binding a queue to the exchange and observing using the RabbitMQ Management Web UI. All messages rated to the queue do not have delivery_mode 2 (as should be set by enabling persistent messaging) and also have no custom headers.

Please advise if the above snippet is not the correct way to set message properties/headers?

**Comment by michaelklishin** [comment]
You need to inspect message properties with a consumer. Management UI is not meant to be used for inspecting messages because the only way it can do that is to consume a message and then re-queue it, which **modifies message properties** (and the UI warns about that).

**Comment by ph0bos** [comment]
Understood, however the initial concern here is that the messages aren't being sent in persistent mode (delivery_mode = 2) despite being set in the options as per the documentation which would be shown correctly in the Management console.

In this case Management UI indicates that the messages are being sent in non-persistent mode (delivery_mode = 1) not the requested persistent mode. This is confirmed by restarting RabbitMQ which results in message loss.

The above indicates that the Channel#publish(exchange, routingKey, content, [options]) call either isn't respecting the provided options or I am not providing them correctly.

**Comment by ph0bos** [comment]
My fault entirely, the options were actually being provided to the Buffer constructor rather than the publish function!

```new Buffer(JSON.stringify(payload), { persistent: true, headers: { "myKey": "myValue" } })```

should be:

```new Buffer(JSON.stringify(payload)), { persistent: true, headers: { "myKey": "myValue" } }```
