### ISSUE TITLE
connect errors

### ISSUE THREAD

**Issue by tsabbay** [squaremo/amqp.node#247]
hi,

i got a connection error on my dev serv.
node 5.8, ubuntu 14.04
last libs, rabbit works fine on srv, (able to connect from another clinet)
from my dev server i cant connect to public rabbit : dev.rabbitmq.com 
from my client , i can.
also from my serv i cant connect to the existing rabbitmq server

amqp://test:test@localhost
amqp://guest:guest@localhost

in logs we see:
=INFO REPORT==== 9-May-2016::10:16:51 ===
accepting AMQP connection <0.582.0> (77.122.171.10:24272 -> 104.131.103.189:5672)

=ERROR REPORT==== 9-May-2016::10:19:35 ===
closing AMQP connection <0.619.0> (104.131.103.189:54637 -> 104.131.103.189:5672):
{handshake_timeout,frame_header}

thanks.
b.

**Comment by squaremo** [comment]
Are there more RabbitMQ logs? Those two log lines refer to two different connections (look at the client IP address).

**Comment by tsabbay** [comment]
sorry, nothing more,
the first log show i can connect to the rabbitmq server from a remote IP
the second one, is that trying to connect localhost/lanip/public ip will ause this handshake error.
it is also the same error when trying to connect to the public dev server..

if u can guide me, ill look for more logs.
