### ISSUE TITLE
Is it possible to consume message one by one?

### ISSUE THREAD

**Issue by Jianru-Lin** [squaremo/amqp.node#248]
In my application, I want to consume the message one by one. Which means I will handle every message for a while (asynchronously), and I don't want to receive other message before I handled current message.

Is it possible? I see there is an channel.get() API exits, but I'm not sure is it the right way to achieve it.I tried, but I failed because I didn't understand this API correctly.

Thanks very much for your help!

**Comment by michaelklishin** [comment]
Yes, using the `basic.get` method in the protocol.

**Comment by squaremo** [comment]
You can use `channel.get()` to ask for a single message at a time, yes.

The other way is to set the channel [prefetch](http://squaremo.github.io/amqp.node/channel_api.html#channel_prefetch) to 1, and use acknowledgments when you set up the consumer (http://squaremo.github.io/amqp.node/channel_api.html#channel_consume). The prefetch is the number of messages RabbitMQ will let you have unacknowledged, so if you set it to one, you'll only get one message at a time.
