### ISSUE TITLE
TypeError: require(...).connect is not a function

### ISSUE THREAD

**Issue by AntonioMendez** [squaremo/amqp.node#253]
node version: v4.4.4
    npm version: 3.9.2
    ionic version (app): 2.0.0-beta.7
    amqplib version: 0.4.1

I am currently trying to develop an app using Ionic 2 framework and I have decided to introduce messaging in my app by using RabbitMQ within this [library](https://github.com/squaremo/amqp.node). Feel free to inspect the code [here](https://github.com/daixtrose/Ionic2AndVS2015/tree/MyIonic2App_antonio/MyIonic2App_2) for any further reference.

1. First of all, I installed the library manually using ```npm install https://github.com/squaremo/amqp.node.git``` because the release version from [npm](https://www.npmjs.com/package/amqplib) is [outdated](https://github.com/squaremo/amqp.node/issues/251).

2. After that, I added the Typescript definitions for the library via ``` typings install dt~amqplib --global --save```.
3. I created a new page for my app called *[Page2](https://github.com/daixtrose/Ionic2AndVS2015/blob/MyIonic2App_antonio/MyIonic2App_2/app/pages/page2/page2.ts)* where the library is imported...

        import * as amqp from 'amqplib/callback_api';
        [...]

    ... and used to connect to the server... 
        
        [...]
        setConnection() {
            amqp.connect(this.connectionUrl, (err: any, connection: amqp.Connection) => {
                this.connection = connection;
                this.connection.createChannel((err: any, channel: amqp.Channel) => {
                    this.channel = channel;
                    this.channel.assertExchange(this.exchange, 'topic', { durable: false });
                });
            });
        }
        [...]
        
4. The problem comes when I try to run it (I have done it using both an **emulator** and a **native device** running Android). If I try to hit the *Set connection* button, I get the following error:

![image](https://cloud.githubusercontent.com/assets/10880610/15540317/ea494c94-2286-11e6-8948-78dc93af3e4e.png)

The error is linked to the line ```sock = require('net').connect(sockopts, onConnect);``` of *[connect.js](https://github.com/squaremo/amqp.node/blob/master/lib/connect.js)* file. Is there any trouble with NodeJS *[Net](https://nodejs.org/dist/latest-v4.x/docs/api/net.html#net_net_connect_path_connectlistener)* module in the library or is it a misconfiguration I made somewhere in my app?, thanks in advance.

**Comment by jaredcnance** [comment]
+1

**Comment by squaremo** [comment]
> Is there any trouble with NodeJS Net module in the library

Naive question: is the `'net'` module available on the platform for which you're building?

**Comment by AntonioMendez** [comment]
I was answered in the Ionic 2 forum and you are right @squaremo.

> Libraries like ampqlib would need to be run on a server. If you do have a serve setup with ampqlib, from there is just building out your own API that can interact with the library. If you need some sort of realtime messaging in your app, you could always checkout http://socket.io/3, which has it's own client side library.

You can see the whole post [here](https://forum.ionicframework.com/t/nodejs-library-within-ionic-2/53727/)
