### ISSUE TITLE
Allow to get client ip

### ISSUE THREAD

**Issue by DanielHreben** [squaremo/amqp.node#258]
Info about client connection (ip, port, etc) available in RabbitMQ management web interface:
![shoot_007](https://cloud.githubusercontent.com/assets/1102227/16164578/a183d038-34e7-11e6-9f48-acff02759a9e.png)

Please, implement interface for get this data through api

**Comment by RoboPhred** [comment]
Unfortunately there is no way to get this data through the amqp spec, as no api was ever defined for it.
Luckily, the same plugin that defines that web management interface also has a nice RESTful api behind it, and it should be simple enough to make your own calls through the http module.  See the [RabbitMQ Management API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_3/priv/www/api/index.html) for details.

**Comment by cressie176** [comment]
Thanks @RoboPhred
