### ISSUE TITLE
Error sending message to queue 

### ISSUE THREAD

**Issue by ajalama** [squaremo/amqp.node#260]
I have a code like this

```
using (var bus = RabbitHutch.CreateBus("MyConnection"))
{                
       bus.Send("MyCodeName", "MyClass");
}
```

the connection is open when I create the bus, but there is this error when I send the message

The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - inequivalent arg 'x-max-priority' for queue ....: received none but current is the value '10' of type 'long'", classId=50, methodId=10, cause=

I setup the queue with x-max-priority:	10.
I have to setup anything else in the connection string?

**Comment by squaremo** [comment]
This is really a question for RabbitHutch, but I'll tell what's happening in case that helps.

In AMQP, when you declare a queue (or an exchange) more than once, you have to provide the same properties. It's like an assertion "the queue exists and has these properties". So what's happening is that you've declare the queue with a particular property `x-max-priority` that RabbitHutch doesn't know about, and it's trying to declare the queue without that property, and RabbitMQ is complaining.

A way around could be to use policies in RabbitMQ to apply the x-max-priority property to your queue: https://www.rabbitmq.com/parameters.html
