### ISSUE TITLE
CPU-intensive tasks cause heartbeat to stop firing

### ISSUE THREAD

**Issue by danteoh** [squaremo/amqp.node#261]
I've run into an interesting situation where I have an extremely CPU-intensive task (image processing), the heartbeat stops sending... it seems like it's depending on a setInterval or something that never gets fired since there's no empty cycles.

You can see in my logs that once the processing starts, the "Sending heartbeat" log that I added in stops firing.  The log on the rabbitmq side reports:

=ERROR REPORT==== 2-Jul-2016::06:01:43 ===
closing AMQP connection <0.21044.6> (100.66.25.82:3459 -> 100.66.17.86:5672):
missed heartbeats from client, timeout: 2s

Is there any known way around this? It's rather inconvenient because in my situation I'm connecting through an AWS ELB which normally kills idle connections after 60s.

[outfile.log.txt](https://github.com/squaremo/amqp.node/files/344430/outfile.log.txt)

**Comment by michaelklishin** [comment]
If the task blocks the event loop, yes. A way around this is

 * Do blocking processing in a separate OS process (e.g. via shelling out or one of the modules that supports OS process clusters) or thread (e.g. via a native extension)
 * Use a runtime that is not limited to a single event loop for everything (which in turn means not using this client)

**Comment by squaremo** [comment]
Yep. NodeJS is single-threaded, and if you use that thread to do something for a long time, nothing else will happen. As @michaelklishin suggests, the known solution for this general problem is using a [child process](https://nodejs.org/api/child_process.html), or the [ cluster module](https://nodejs.org/api/cluster.html).
