### ISSUE TITLE
Delete only if the queue is empty.

### ISSUE THREAD

**Issue by HERRKIN** [squaremo/amqp.node#267]
Hello, I am testing the deleteQueue method on your lib. it says if I pass isEmpty:true it wont delete the messages, I am calling the method this way ch.deleteQueue(queuename,{isEmpty:true).then(console.log,console.log)

the queue gets deleted no mater if it has messages or not, I tried isEmpty:false, same behaviour, is it a bug?

**Comment by connec** [comment]
Per the docs:

> ifEmpty (boolean): if true and the queue contains messages, the queue will not be deleted and the channel will be closed. Defaults to false.

E.g. the option to test is `ifEmpty`, not `isEmpty`.

**Comment by HERRKIN** [comment]
oh thanks, my bad, but I see that if not empty the channel drops connection. shouldn't 'reject' handle it?

**Comment by HERRKIN** [comment]
I mean, I don't want to close the channel only know if the queue got deleted or not and continue.

**Comment by connec** [comment]
From [the spec](https://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.delete) it sounds like that's the defined behaviour ("Error code: precondition failed").

The failure model of AMQP generally means that most failed assertions will blow up the channel. I've not used the library directly for a while, but I expect you can catch this with an error handler on your channel.

```js
channel.on('error', function () {
  console.log('Ruh roh')
})
```

I'm not sure what to suggest in your case, Could you wait to delete the queue until you are done with the channel? Could you create a separate channel to delete the queue?

**Comment by squaremo** [comment]
> Could you create a separate channel to delete the queue?

Creating a one-off channel is usually the easiest way to get around this particular AMQP wonkiness. You just have to take care to not leak them.
