### ISSUE TITLE
amqp.connect should try all options from DNS result before giving up

### ISSUE THREAD

**Issue by jonasfj** [squaremo/amqp.node#268]
Example we have a rabbitmq cluster `pulse.mozilla.org` the DNS resolves to 3 IPs, so I wouldn't think it's highly available. But when 2 out of 3 servers are down, the result is that 66% of the time our servers will fail to connect. As connections are stateful and rarely break, it's a legitimate solution to just crash and restart the process when connections break, hehe, but obviously with 2 out of 3 servers down, that won't work so well if we try all IPs when trying to establish a connection.

I understand that reconnect logic is a non-trivial topic as connection are stateful. But it should be fairly uncontroversial to retry connection establishment if we get `ECONNREFUSED` trying to establish the connection. Notice, I don't propose we retry broken connections (maybe later, or maybe leave that to consumers).

So if the DNS record for the hostname holds multiple IPs, maybe we should try all options in randomized order.

Thoughts? I would be happy to look into this...

**Comment by michaelklishin** [comment]
.NET and Java clients recently introduced abstractions that return a list of endpoints to try. This becomes a specific implementation of it. Perhaps this client could consider doing the same.

**Comment by jonasfj** [comment]
So that in addition to doing `connect(url, socketOptions)` you can also do `connect([url1, url2, url2], socketOptions)`.

That would probably be a good idea. Probably I would say that if you supply a DNS name it still should automatically expand to all possible resolutions. Because using DNS for load-balancing a rabbitmq cluster is a pretty common pattern.

But certainly offering an option to supply more than URL would be neat. Some cluster are configured with multiple hostnames.

**Comment by jonasfj** [comment]
hmm.. Maybe this isn't the solution after all. I just noticed that cloudamqp defaults to just one dns record and then randomize the result.

So perhaps the result solution is to retry connection establishment.
