### ISSUE TITLE
amqp.connect() shows unexpected behavior with special character(#) in password

### ISSUE THREAD

**Issue by brianjang** [squaremo/amqp.node#269]
```
amqp.connect('amqp://incowiz:incowiz#1@192.168.0.104', function(err, conn) {
  conn.createChannel(function(err, ch) {
    var q = 'hello';

    ch.assertQueue(q, {durable: false});
    console.log(" [*] Waiting for messages in %s. To exit press CTRL+C", q);
    ch.consume(q, function(msg) {
      console.log(" [x] Received %s", msg.content.toString());
    }, {noAck: true});
  });
});
```

err object shows the below log message:
err --------------------------------------
{ [Error: getaddrinfo ENOTFOUND incowiz incowiz:5672]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'incowiz',
  host: 'incowiz',
##   port: 5672 }

/home/brian-pc/workspace/incowiz_push/rabbitmq/01_send.js:10
  conn.createChannel(function(err, ch) {
      ^

**Comment by connec** [comment]
A plain `#` in a URL is treated as the fragment/hash separator. Try URL encoding the hash:

```js
amqp.connect('amqp://incowiz:incowiz%231@192.168.0.104', function (err, conn) {
  ...
});
```

**Comment by squaremo** [comment]
Yes indeed, thanks @connec.

@brianjang You can use [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) to reliably do this for the password (and username, and virtual host, ...) before constructing the URL. Another option is to use a connection object, as in #159, which means you don't have to encode things.
