### ISSUE TITLE
DNS error on connection causes unhandled rejection error

### ISSUE THREAD

**Issue by niahmiah** [squaremo/amqp.node#270]
Unhandled rejection Error: getaddrinfo ENOTFOUND someunknownhostname someunknownhostname:5672
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

attempting to catch() after connect() does not seem to handle this

**Comment by squaremo** [comment]
Just to check: `.catch()` handles exceptions, but the error was propagated in the reject handler instead?

**Comment by n-sviridenko** [comment]
I still have this issue. The node process is still running after although there are no other things running except the amqp client.
