### ISSUE TITLE
unknown delivery tag problems

### ISSUE THREAD

**Issue by jwalton** [squaremo/amqp.node#271]
I have this problem where my connection dies with "unknown delivery tag 4".  I added a bunch of console.log()s, and I see a message coming in with delivery tag 1, and I call `ack` for that message, and 2, and 3, and then 4 shows up, and I call `ack` on each of these in order (and as far as my console.log knows, I only call it once) and for some reason on that fourth message, my connection dies with "unknown delivery tag 4".  Sometimes it's on the fourth message, sometimes on the first, sometimes on the sixth.  It seems to be pretty random.

Any ideas on how to troubleshoot this?

**Comment by jwalton** [comment]
What's also strange is this happens very consistently on my co-worker's machine, but not on mine, even though we are running identical versions of RabbitMQ.  The system is basically sitting at idle - the only messages flowing back and forth are essentially a "ping" sent by workers to make sure the notifications server is still alive.

**Comment by jwalton** [comment]
Changing title, because I know more about what's going on.

On my co-worker's machine, at startup she sees the connection to RabbitMQ die with a "Error: write EPIPE".  Not sure what this is all about, but this seems to start the horror.

A little bit later, we see `"Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - unknown delivery tag 1"`.  This is emitted by connection as an "error" event (which amqp-connection-manager [receives here](https://github.com/benbria/node-amqp-connection-manager/blob/391ed65dd7b48321fc87c57ac785216895ba5d57/src/AmqpConnectionManager.coffee#L105)), and shortly after we see connection fire a "close" event ([here](https://github.com/benbria/node-amqp-connection-manager/blob/391ed65dd7b48321fc87c57ac785216895ba5d57/src/AmqpConnectionManager.coffee#L116)).  But (and this is the fun bit) if I go into the RabbitMQ UI, I see that the connection is still alive.

Pub/Sub style subscribers (created with `consume`) will continue to receive messages from this "zombie" connection, (and then amqp-connection-manager creates a new connection and recreates all these subscribers on the new connection - so every time this happens I get a new copy of every subscriber).  The `consume()` that kills everything is a "worker queue" where I am consuming from a named queue (and where in theory other clients could be consuming from the same queue - not normally, since we're running in dev here - but probably we are since we have multiple connections running).

Calling `connection.close()` on the connection when we get the "error" event seems to have no effect - the connection still sticks around.

**Comment by squaremo** [comment]
I don't like to point fingers, but is it possible amqp-connection-manager is where the problem lies? It sounds very much like a message is being acknowledged on a channel that is not the channel it came from. In "regular" use of amqplib, that wouldn't happen, but swapping channels around is exactly the sort of thing amqp-connection-manager might do to accomplish its aims.

**Comment by squaremo** [comment]
> It sounds very much like a message is being acknowledged on a channel that is not the channel it came from. In "regular" use of amqplib, that wouldn't happen

"wouldn't happen" is a bit hopeful of me -- it's not _prohibited_ by this library. You should make sure you're not inadvertently doing it, independently of amqp-connection-manager.

**Comment by jwalton** [comment]
Yeah, I put a *ton* of console.logs throughout my code to make sure I was acking on the channel I thought I was acking on.  And as I said, this is very low volume.  I'm very suspicious of the fact that we seem to be leaking connections.  I'll see if I can construct something that artificially recreates this tomorrow.

**Comment by jwalton** [comment]
Basically, we have a "pub/sub" primitive and a "worker queue" primitive built on top of amqp that we use everywhere, and here (because I'm very lazy and I already had a pub/sub and a worker queue) we have one central notification server (responsible for sending emails and such).  In the production case, we'd have two worker threads, and they want to know if the notification server is still alive.  So every 30 seconds or so, the worker threads each send a worker-queue message to the notification server with a UUID in it.  The notification server broadcasts a "I'm still alive" with the UUID over pub sub back to the two workers.  So each worker gets two such "ping" messages, one which it ignores (because it's for the other worker) and one which it says "Yup, that notification server is still there."

In development mode, there's just the one worker, and it's running in the same node.js process as the notification server, so the worker sends a worker-queue message, and the notification server replies over pub-sub.

As things stand, every now and then the worker-queue tries to ack a message and it blows up.  If I put a log in the subscriber, though, then the first time we send a worker-queue message, we send one reply over pub-sub, and one subscriber logs it.  The next time it blows up, we still send one message back, but we see two different subscribers log the message, and then three, and then four - we add a subscriber every time we run into this problem, because we're setting up a new connection but the old connection is still there, and still subscribed.

Question: should the `deliveryTag` be unique across channels?  Certainly I am seeing multiple messages come in at the same time with the same deliveryTag, but then again, they're coming from different connections...  But could this be related?

**Comment by squaremo** [comment]
Delivery tags are scoped to the originating channel, and since they are sequence numbers with a defined starting point, you are likely to see the same numbers again and again.

Another thing to look for is acknowledging a message more than once; it's quite easy to do, since you can share messages among procedures.

**Comment by jwalton** [comment]
Yeah, double-ack was my instinct when I walked into this problem in the first place, especially because the core infrastructure of all this hasn't really changed since I wrote amqp-connection-manager a year ago, and this is all of a sudden giving us problems now.  But again, if that's what's happening then I'm missing a console.log somewhere, because I can't find it.  :P

**Comment by jwalton** [comment]
Ok, I know where the "leaked connections" are coming from.  I accepted a fix to amqp-connection-manager a little while ago which added [an `on('close')` handler](https://github.com/benbria/node-amqp-connection-manager/pull/10), only this PR makes it so if we get an "error" followed by a "close" from amqp, then we end up creating a new connection... then creating another new connection a short while later.  I don't know why having an extra connection hanging around could cause "unknown delivery tag" issues, though.

**Comment by jwalton** [comment]
Ok, well, fixing having multiple connections open at the same time seems to have made my "unknown delivery tag" issues go away, although I'm not sure why these would be related.  Closing.

**Comment by walkerx** [comment]
I have the same problem. how to fix it?

**Comment by squaremo** [comment]
> I have the same problem. how to fix it?

@walkerx There are a bunch of possible causes, which you'll be able to glean from the comments above, but the essential information is this: you can acknowledge (or reject) the `deliveryTag` that comes with each message only once, and only on the channel on which the message arrived. Look in your code for anywhere you are passing messages around, because you might be using the `deliveryTag` on a different channel as a result.

**Comment by cressie176** [comment]
@jwalton FYI just had exactly the same problem with [Rascal](https://github.com/guidesmiths/rascal) . I had also created a new connection on both the error and close events, and started experience the unknown tag problem. When stopped creating the second connection the problem went away. I'll see if I can reproduce without all the Rascal noise.
