### ISSUE TITLE
How can I create a queue?

### ISSUE THREAD

**Issue by madhur** [squaremo/amqp.node#273]
I would like to create a queue if none exists using this API. I looked at the  API but couldn't find any method. Any pointers?

**Comment by cressie176** [comment]
Just assert the queue. If it doesn't exist it will be created. If it already exists (and has the same properties) the existing queue will be retained. You can't redefine existing queue properties with rabbit. See - http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue

**Comment by madhur** [comment]
:+1:
