### ISSUE TITLE
If the network outage,the ack not to the server and the server will not send message to consume. What should i do?The below is my code Thanks for first. 

### ISSUE THREAD

**Issue by FlyingSailor** [squaremo/amqp.node#275]
If the network outage,the ack not to the server and the server will not send message to consume. What should i do?The below is my code Thanks for first. 
amqp.connect(loginUrl).then(function (conn) {
    process.once('SIGINT', function () {
        conn.close();
    });
    return conn.createChannel().then(function (ch) {
        return ch.assertQueue(q, {durable: true})
            .then(function () {
                ch.prefetch(1);
            }).then(function () {
                ch.consume(q, doWork, {noAck: false});
                console.log(" [*] Waiting for messages. To exit press CTRL+C");
            });
        function doWork(msg) {
            setTimeout(function () {
                var body = msg.content.toString();
                console.log("\n [x] Received '%s'", body, "\n [x] Done\n\n\n");
                ch.ack(msg);
            }, 3000);
        }
    });
}).then(null, console.warn);

**Comment by cressie176** [comment]
Hi @FlyingSailor. Think you can edit your question so the code properly formatted? e.g. 

```js
amqp.connect(loginUrl).then(function (conn) {
  process.once('SIGINT', function () {
  conn.close();
});
```

See the Syntax highlighting section in [markdown](https://guides.github.com/features/mastering-markdown/).

Regarding your question of what to do if you get a network outage. You need to design your application to cope with this scenario. Things you might consider...

1. Automatically reconnecting / re-establishing channels on connection errors.
2. Monitoring and alerting on queue lengths and alerting if they grow beyond a threshold - I use [datadog](https://www.datadoghq.com/)
3. Writing your applications in such a way that they can tolerate duplicate messages (in case the ack fails).
4. Ensuring there's a way to regenerate important messages if they fail to send (e.g. if you were sending a password reset email, providing a button that allows the user to resend it)

On a separate note, don't forget that when your [consumer is cancelled by rabbit](http://www.rabbitmq.com/consumer-cancel.html), amqp sends a null message to your callback, so your ```msg``` parameter can be null.
