### ISSUE TITLE
How to get the message from the callback?

### ISSUE THREAD

**Issue by jhnferraris** [squaremo/amqp.node#278]
How do I get the message from the queue from the `consume` callback?

```
let message = channel.consume(queue, msg => {
          console.log('Checking message...');
          if (msg !== null) {
            let messageString = msg.content.toString();
            console.log('Acknowledging message..');
            channel.ack(msg);
            console.log('Acknowledged.');
            return messageString;
          } else {
            console.log('No messages to consume.');
            return null;
          }
        });
```

When I tried logging `message`, the value is `{ consumerTag: 'amq.ctag-8xJApdXxBkOqiabOMtPN-A' }`

My message is:

```
{ name: 'Foo Bar' }
```

Thanks for the help!

**Comment by squaremo** [comment]
The return value of `channel.consume()` holds the consumer tag, generated
by the server, with which you can later cancel the consumer.

Messages are delivered to the function you supply as as argument (correctly
in your example). If it's not printing something out, it may be because the
message is not making it that far.

Some things to check:

- do you successfully publish the message (can you see it go past in the
rabbitmq management ui)
- are you subscribing to the right queue

**Comment by jhnferraris** [comment]
@squaremo 

My bad I forgot my basics on callbacks.

What I did to extract the message was thru this code:

```
var messageString;
channel.consume(queue, msg => {
          console.log('Checking message...');
          if (msg !== null) {
            messageString = msg.content.toString();
            console.log('Acknowledging message..');
            channel.ack(msg);
            console.log('Acknowledged.');
            return messageString;
          } else {
            console.log('No messages to consume.');
            return null;
          }
        });

console.log(messageString);
```

Let me know if there are any issues that will arise when using this workaround. Thanks!

I'm closing this for now.

**Comment by jackienomad** [comment]
> @squaremo
> 
> My bad I forgot my basics on callbacks.
> 
> What I did to extract the message was thru this code:
> 
> ```
> var messageString;
> channel.consume(queue, msg => {
>           console.log('Checking message...');
>           if (msg !== null) {
>             messageString = msg.content.toString();
>             console.log('Acknowledging message..');
>             channel.ack(msg);
>             console.log('Acknowledged.');
>             return messageString;
>           } else {
>             console.log('No messages to consume.');
>             return null;
>           }
>         });
> 
> console.log(messageString);
> ```
> 
> Let me know if there are any issues that will arise when using this workaround. Thanks!
> 
> I'm closing this for now.

I wasn't able to get the messageString, it's still undefined

**Comment by cressie176** [comment]
Hi @jackienomad,

My guess is that it's a typo. Some suggestions to help you debug...

```js
const { content, ...metaData } = msg;
console.log(JSON.stringify(metaData, null, 2));
console.log(content.constructor.name);  // Should be Buffer
console.log(content.length);
console.log(content) // Should be <Buffer 61 73 64 66 etc...>
console.log(content.toString())
```
If you're unable to find the problem please open a new issue and paste your code.

Thanks
