### ISSUE TITLE
Why doesn't sendToQueue return a Promise?

### ISSUE THREAD

**Issue by LinusU** [squaremo/amqp.node#286]
I think it would be very nice if `sendToQueue` could return a `Promise` that resolves when the server has accepted the message. Otherwise there is no way to know if the message has been accepted or not.

The same goes for `.ack`. It would be very nice to know that the message actually got acknowledged by the queue.

**Comment by squaremo** [comment]
In the first case: you can use a ConfirmChannel, which accepts a callback argument, to synchronise on the server accepting messages. The return value of both `publish` and `sendToQueue` is reserved for flow control (similarly to regular Node.JS streams).

In the second case: there's no explicit indication, in the protocol, of whether the server has processed an ack. All you can do is send an (ideally no-op) RPC after, and if that succeeds, so did the previous ack. While this isn't impossible to build into the library, it would be an unwelcome performance-killer in most situations. (And is not reliable -- an ack-ack might not arrive, and then what do you do?)

The standard advice is to have idempotent message handlers -- i.e., for duplicate messages to not have an additional effect.
