### ISSUE TITLE
ConfirmChannel callback not firing

### ISSUE THREAD

**Issue by taimur38** [squaremo/amqp.node#287]
Trying to shift over to using ConfirmChannel, but I'm seeing that the callback at the end of `channel.publish(exchange, pattern, buffer, options, callback)` is never fired. I am acking messages on the other side - if I use `channel.waitForConfirms()`, that promise does get filled, but doesn't give me the per-message ack I was looking for.

Do I need to set a field in headers to get it working per-message?

**Comment by cressie176** [comment]
You shouldn't do. [Here's](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Publication.js#L105) I use confirm channels, which is similar to what you describe. Did you create the channel with ```connection.createConfirmChannel(callback)```

**Comment by taimur38** [comment]
oops, found a typo with my parenthesis
