### ISSUE TITLE
How to setup this lib (rabbitmq) to process only one task at the same time?

### ISSUE THREAD

**Issue by jsifalda** [squaremo/amqp.node#288]
Hey,

is there a way how to setup this lib (or rabbitmq generally) to accept only one task at the same time?
If so, can you please help me, how to do it? 

Thank you vey much in advance!

My best,
Jiri

**Comment by cressie176** [comment]
Assuming you mean only process one message at the same time, then you can do this per queue by disabling auto acknowledge (by setting ```noAck``` to true) and configuring a prefetch of 1.

See the [channel api](http://www.squaremobius.net/amqp.node/channel_api.html) for more details

**Comment by jsifalda** [comment]
When I set noAct to true, how the queue will know that the job is done and start to work on another task in queue? Especially when the job is async? 
Ideally, do you have any example?

**Comment by cressie176** [comment]
You have to explicitly acknowledge (ack) or not acknowledge (nack) it. See https://github.com/squaremo/amqp.node/blob/master/examples/tutorials/worker.js

**Comment by jsifalda** [comment]
what you just said is in contrary with your previous comment or not? :) I know I can  acknowledge (ack) or not acknowledge (nack) it. But even if I do it, it still process more tasks in queue job at the same time.

**Comment by jsifalda** [comment]
Let's say I have this implementation: 
`
amqp.connect(config.amqp.connection)
.then(function (conn) {
  var consume = jobs(pn(ios(apnConnection, apnDevConnection, config), android(config)), dbConnection, rt(config.rt.url), config)
  var promises = Object.keys(consume).map(function (name) {
    return conn.createChannel()
    .then(function (channel) {
      channel.assertQueue(name)
      return channel.consume(name, function (msg) {
        if (msg !== null) {
          var result = null
          try {
            var message = JSON.parse(msg.content ? msg.content.toString() : msg.toString())
            result = consume[name](message)
          } catch (e) {
            console.log('Consume error', e)
            if (e && e.stack) {
              console.log(e.stack)
            }
          }

          if (!result) {
            result = 'ack'
          }

          switch (result) {
            case 'ack':
              channel.ack(msg)
              break
            case 'nack':
              channel.nack(msg)
              break
            case 'sack':
              channel.nack(msg, false, false)
              break
            default:
              throw new Error('Unknown consume callback response code!')
          }
        }
      })
    })
  })
  return Promise.all(promises)
})
.then(() => {
  console.log('App listening for incoming events')
})
.catch((error) => {
  console.log('Could not connect to amqp', error)
})
`

where jobs() returns object eg: 
`
{
    'pn.send.user': () => {}
}
`

and this is how the publish method looks like:
`
var rabbit = {
  publish: function (queue, message) {
    return new Promise(function (resolve, reject) {
      connect()
      .then(function (conn) {
        return conn.createChannel()
      })
      .then(function (channel) {
        return channel.assertQueue(queue)
        .then(function () {
          return channel.sendToQueue(queue, new Buffer(JSON.stringify(message)))
        })
      })
      .then(function (result) {
        resolve(result)
      })
      .catch(function (error) {
        reject(error)
      })
    })
  }
}
`

When the publish sends eg. 1000 tasks into same queue, job processor will process it all at the same time which I want to avoid.

**Comment by cressie176** [comment]
> what you just said is in contrary with your previous comment or not?

What part?

The process should be...

1. Create a single queue
2. Bind a single consumer to it
3. Set prefetch to 1 to ensure there is only unacknowledged message in play at any point in time
4. Set noAck to true to disable auto-acknowledgements, otherwise amqplib will ack the message before you've processed it, causing rabbit to release the next message immediately.
5. After your single consumer has finished processing each message, ```ack``` it to tell rabbit you've finished and can get the next message, or ```nack``` it to either rollback/discard/dead letter the message depending on your configuration.

**Comment by jsifalda** [comment]
Great! Thanks. 
I have rewritten my script into following form:
```js
amqp.connect(config.amqp.connection)
.then(function (conn) {
  var consume = jobs(pn(ios(apnConnection, apnDevConnection, config), android(config)), dbConnection, rt(config.rt.url), config)
  var promises = Object.keys(consume).map(function (name) {
    return conn.createChannel()
    .then(function (channel) {
      var ok = channel.assertQueue(name)
      ok = ok.then(() => {
        channel.prefetch(1)
      })
      ok = ok.then(() => {
        channel.consume(name, (msg) => {
          if (msg === null) {
            console.log('No message for queue task')
            return
          }

          var result = null
          try {
            result = consume[name](JSON.parse(msg.content ? msg.content.toString() : msg.toString()))
          } catch (e) {
            console.log('Consume error', e)
            if (e && e.stack) {
              console.log(e.stack)
            }
          }

          if (!result) {
            result = 'ack'
          }

          if (result && typeof result.then !== 'function') {
            result = Promise.resolve(result)
          }

          result
          .then((message) => {
            console.log('Task', name, 'finished, with message', message)
            if (!message) {
              message = 'ack'
            }

            switch (message) {
              case 'ack':
                channel.ack(msg)
                break
              case 'nack':
                channel.nack(msg)
                break
              case 'sack':
                channel.nack(msg, false, false)
                break
              default:
                throw new Error('Unknown consume callback response code!')
            }
          })
          .catch((error) => {
            console.log('Consume promise error', error)
            channel.ack(msg)
          })
        }, {
          noAct: false
        })
      })

      return ok
    })
  })
  return Promise.all(promises)
})
.then(() => {
  console.log('App listening for incoming events')
})
.catch((error) => {
  console.log('Could not connect to amqp', error)
})
```

and it works exactly as I need - it processes only one task job at the same time even for aync jobs (controlled by promises)!
The key point in my case was to set **prefetch** to 1.

Thanks for the help!
