### ISSUE TITLE
Problem with scalability - what are the best practises?

### ISSUE THREAD

**Issue by jsifalda** [squaremo/amqp.node#291]
Hey There, I have implemented this lib exactly as you have it in the examples. However, when we run this on production, we have serious problems with scalability... when it sends more than 1500 messages it takes almost 40% of ram and then rabbit closes the connections. 
Thsi is how method for publishing looks like:
```js
publish: function (queue, message) {
    return new Promise(function (resolve, reject) {
      connect()
      .then(function (conn) {
        return conn.createChannel()
      })
      .then(function (channel) {
        return channel.assertQueue(queue)
        .then(function () {
          return channel.sendToQueue(queue, new Buffer(JSON.stringify(message)))
        })
      })
      .then(function (result) {
        resolve(result)
      })
      .catch(function (error) {
        reject(error)
      })
    })
  }
```
I should mention that method "connect" does not create connection everytime but pass previously created connection if already exists. 
What I do not like about is, is the fact, it creates a channel for every single message which should be published and it sounds redundant to me. Do you think is can be pain point? Additionally, what are the  best practises for publishing? Create just one channel for all the queues or create channel for each queue eg. queues "core.facts.crated" & "channel.notifications.created" should have two different channels but not for each message which should be published. 
Thanks in advance!

**Comment by squaremo** [comment]
Yes, creating a channel for each send is wasteful. Usually the pattern is to have a channel per consumer, and one for publishing, or one for publishing per "thread of control". If you're using worker queues, one publisher channel for each of those seems reasonable.

**Comment by jsifalda** [comment]
Makes sense now! Thanks.
Btw, I have created lib which works with your one to make a little bit easier. Especially, this lib makes sure it, only one channel exists for publishing and consuming. You can check it out here https://github.com/tribelabs/amqp
