### ISSUE TITLE
expose IllegalOperationError

### ISSUE THREAD

**Issue by ben-page** [squaremo/amqp.node#299]
I've developed a small library that uses amqplib to make it easy to perform RPC over a message bus. I need to be able to distinguish between errors caused by programmer error while using the library and errors that are caused bugs in the library itself. Testing if an error is an instance of IllegalOperationError is very helpful in this.

```javascript
const IllegalOperationError = require('amqplib/lib/error').IllegalOperationError;
```
Currently, I am accessing IllegalOperationError this way. But circumventing the public API in this way is worrisome, because it could break just by reorganizing or renaming files.

It seems like good practice to expose custom error types in the public API. And it seems to be common for Nodejs libraries to do so.

**Comment by Uzlopak** [comment]
@squaremo 
This issue could be closed as the PR is already merged.
