### ISSUE TITLE
channel_model.js close function throws an exception

### ISSUE THREAD

**Issue by rizkylearns** [squaremo/amqp.node#302]
at /lib/channel_model.js:77

// this is null as it fell out of scope when using Promise
C.close = function() {
  return Promise.fromCallback(function(cb) {
    return this.closeBecause("Goodbye", defs.constants.REPLY_SUCCESS,
                    cb);
  });
};

// this to self to keep its ref to the Channel.prototype
C.close = function() {
  var self = this;
  return Promise.fromCallback(function(cb) {
    return self.closeBecause("Goodbye", defs.constants.REPLY_SUCCESS,
                    cb);
  });
};

**Comment by ismriv** [comment]
Duplicate of https://github.com/squaremo/amqp.node/issues/297
