### ISSUE TITLE
How to ".catch" upon using "connect" promise

### ISSUE THREAD

**Issue by gideonairex** [squaremo/amqp.node#311]
Im trying to test if it cant connect to Rabbitmq. 
```javascript
rabbitmq.connect( '<invalid host>' )
   .then( function ( connection ) {
   } )
   .catch( function ( error ) {
      // This part I cant seem to catch
   } );
   // I also tried using
   .then( null, function( error ) {
     // No luck
   } );
```
I also tried using the callback model
```javascript
rabbitmq.connect( '<invalid host>', function ( error, connection ) {
  if( error ) {
    // This part I want to handle
  }
} );
```
My objective for this is that I want to know already if it cant connect within a span of time so that I can redirect or handle it as soon as possible.
Is there a way to have options for retry connections timeouts or just emit if host is not reachable?

**Comment by Verikon** [comment]
try;

> rabbitmq.connect( '<invalidhost>', { timeout: 3000 } ).then( ...... )

**Comment by gideonairex** [comment]
Hi @Verikon thanks it worked throwing out the error Im not sure what happened last time. On the timeout side I think as designed they removed timeout once its connected.
https://github.com/squaremo/amqp.node/blob/master/lib/connect.js#L147
