### ISSUE TITLE
Following '1 connection per app, 1 channel per thread, 1 consumer per channel' guideline

### ISSUE THREAD

**Issue by rtorrero** [squaremo/amqp.node#313]
Hi,

I'm building a simple job queueing library (somewhat similar to [Jackrabbit)](https://github.com/hunterloftis/jackrabbit) to be used in a service that should parse pretty large feeds containing information about a lot of different events.

After the information is parsed, it gets distributed to thousands of queues (the queue is the smallest unit where message order has to be respected) and then consumed by my queueing library. 

The question is: how do I follow the '1 connection per app, 1 channel per thread, 1 consumer per channel' guideline in this case? It would cause thousand of processes to be spawned, wasting huge amounts of memory and resources.

Note: The number of messages in each of the queues is not very high: about 1-2 msg/sec at most

**Comment by cressie176** [comment]
Why 1 channel per thread / process? There's nothing to stop a single process having multiple consumers, each with their own channel.

**Comment by rtorrero** [comment]
@cressie176 According to the most upvoted answer [here](http://stackoverflow.com/questions/10407760/is-there-a-performance-difference-between-pooling-connections-or-channels-in-rab) this seems to be the 'general advise'.

I doubt having several connections or channels is that bad. But... what about having 1000 connections or 1000 channels in one connection? Is that acceptable?

**Comment by michaelklishin** [comment]
Having several is perfectly fine. Having thousands from a single host or thousands of channels on a connection is typically excessive and [yields no benefits](https://www.rabbitmq.com/blog/2014/04/14/finding-bottlenecks-with-rabbitmq-3-3/) for consumers.

**Comment by michaelklishin** [comment]
The only scenario that we see where having thousands of 10s of thousands of connections from a single process makes sense is load testing with a high number of connections. Even in Erlang where it's perfectly fine to have 100s of thousands of processes in a single VM, using a separate connection for each is a complete overkill (with channels it might be reasonable but still fairly excessive in terms of both client and server resources).

**Comment by rtorrero** [comment]
@michaelklishin what about having several threads on the consumer side (or even processes running on different machines), connecting a RabbitMQ cluster?

Would then 'one connection per job queue' be acceptable?

**Comment by michaelklishin** [comment]
@rtorrero have you considered searching rabbitmq-users archives?

For message handlers, having N threads or even OS processes is perfectly fine as long as you find their coordination worth the throughput gain. Key challenge to address in that case is concurrent processing: all official (or maintained by our team) RabbitMQ clients typically offer per-channel delivery guarantee but everything you dispatch to a thread pool or a process pool no longer carries that guarantee and will be processed concurrently. That may or may not be what you want but we certainly can't recommend against it.

**Comment by michaelklishin** [comment]
With OS processes or even kernel threads you likely won't have more than maybe low 100s of them running at the same time so that may be sufficient. Connections consume resources, primarily RAM, but that [can be configured](http://www.rabbitmq.com/networking.html) to be an order of magnitude lower than by default (by trading off some throughput, since most of RAM is used by TCP buffers). So that sounds reasonable even on 64/128/256 core machines.

**Comment by cressie176** [comment]
@rtorrero The stackoverflow advice probably didn't take into consideration the specific's of Node.js. If you were writing your application in java then launching a new thread would be trivial, but with Node.js you would have to launch a new process, which as you say would be wasteful from a memory perspective.

**Comment by michaelklishin** [comment]
Can we please close this? I believe the answers were fairly exhaustive.

**Comment by rtorrero** [comment]
Thanks for the detailed answers!
