### ISSUE TITLE
Publish/ack result to indicate that data was read from channel's buffer

### ISSUE THREAD

**Issue by ArenSH** [squaremo/amqp.node#322]
Hello,

As i understand, in current implementation there is no way to know that data from any non-rpc call is at least were transferred to socket buffer.

Consider following example:
```js
let stats = {published: 0, failed: 0}
function worker(ch) {
    //continuously publish messages
    let result = ch.publish('my_exchange', 'my_route', Buffer.from('data'));
    if(result) {
        stats.published++;
    } else {
        stats.failed++
    }
}
```

The ```result``` in this case indicates only that data is put to channel's buffer. If error occurred, channel's buffer with all data will be deleted and user will never know about it. For ack/nack there is no result at all (although ```Channel.sendImmediately``` returns boolean);

For our purposes knowing that data were transfered to socket helps to implement reliable statistics and retries for publish/acks without giving up on performance by using unnecessary confirmations (data is not critical). 
As far as i know, this problem can be solved by using callback argument for buffer.write in ```Connection.sendMethod``` and ```Connection.sendMessage```.

Can you please clarify reasons behind current implementation?

Thanks.

**Comment by squaremo** [comment]
> As far as i know, this problem can be solved by using callback argument for buffer.write in Connection.sendMethod and Connection.sendMessage.

That's possible, but I don't know that it would help you much. Do you care which buffer the message is in, while it's unsent? Once it's left the socket send buffer, do you care where it is, until all the bytes have reached the server? Once it's in a buffer on the server, do you care which buffer, until it's been seen by RabbitMQ?

I would think the only event worth caring about, once you've called `channel.publish`, is that RabbitMQ has processed the message. Confirmations are less costly than you may think -- it's worth measuring, if you've not already.

Acknowledgements are, I admit, trickier. There's nothing in the protocol to tell you whether an ack was processed by the server, so the only way you know is that subsequent operations succeed. It's still the case that reaching the socket send buffer is no guarantee of being processed by the server, though -- am error might occur on a prior operation, meaning the ack gets lost anyway, for example.

**Comment by ArenSH** [comment]
> That's possible, but I don't know that it would help you much. Do you care which buffer the message is in, while it's unsent?

I think if data loss caused by application error can be prevented - it worth doing. The rest is the kernel and tcp job. But yeah, generally this sort of confirmations (message is transfered to socket buffer) is not very useful with amqp.

Thanks for response.
