### ISSUE TITLE
Scheduling recurring tasks

### ISSUE THREAD

**Issue by elyas-bhy** [squaremo/amqp.node#328]
For performance and reliability reasons, I would like to migrate from [rschmukler/agenda](https://github.com/rschmukler/agenda) to RabbitMQ.  
However, I am relying a lot on the recurring task scheduling feature from agenda:
```js
// Schedule these 3 tasks every 15 minutes
agenda.every('15 minutes', ['printAnalyticsReport', 'sendNotifications', 'updateUserRecords']);
// Schedule this task to be executed tomorrow at noon
agenda.schedule('tomorrow at noon', 'printAnalyticsReport');
```

How can I replicate these features using RabbitMQ / amqp.node?  
I know that I can use `setInterval` in my app logic to manage the scheduling myself, but I would rather avoid that for several reasons: resource-intensive for a large number of recurrent tasks, no fault-tolerance (all intervals are lost if the process crashes), not cluster-friendly, etc.

**Comment by michaelklishin** [comment]
You'd have to build a scheduling service. RabbitMQ has an experimental [delayed publishing plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange) but it has limitations and does not even try to cover recurrence.

So I'd recommend looking into a separate service that will publish messages on a recurring basis (and handle various failure scenarios). There should be some JavaScript projects to assist you with that.

**Comment by elyas-bhy** [comment]
Alright thanks for the insight. I agree that this feature should be provided by an external service / plugin and not be in the core library.  
For documentation purposes, I have found the following library that seems to implement just what I'm looking for: https://github.com/titarenko/worque. I'll give it a try. Closing this issue for now.
