### ISSUE TITLE
[Question] Is it possible to connect multiple RabbitMQ

### ISSUE THREAD

**Issue by chatmoa** [squaremo/amqp.node#333]
I have two different RabbitMQ servers, how can I connect to them to listen messages into the first one and write another messages into the second one with the same nodejs process?

**Comment by michaelklishin** [comment]
Open two separate connection. One client connects to one node at a time.

**Comment by michaelklishin** [comment]
Actually, you DO NOT need to connect to 2 nodes to consume from queues whose master is hosted on them. RabbitMQ nodes will route traffic internally and deliver to local consumers. In other words, any client can publish to and consume from any node. That's how some messaging protocols assume things work :/

**Comment by chatmoa** [comment]
It's two different rabbitMQ clusters, not nodes of the same cluster.

**Comment by chatmoa** [comment]
Here is how i connect:

`const rmqFrontConn = require('amqplib').connect(config.rabbitFront.url);
const rmqBackConn = require('amqplib').connect(config.rabbitBack.url);`

next i use promises on each «conn»

**Comment by chatmoa** [comment]
Only the second connection is active because when assertQueue is called on the second, it does not find the queue.

**Comment by chatmoa** [comment]
`Uncaught Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'frontXchange' in vhost 'frontVhost'"`

**Comment by michaelklishin** [comment]
If it's two different clusters then you need two connections (even if queue federation is used).

**Comment by chatmoa** [comment]
Is there another way to have two connections ?

**Comment by michaelklishin** [comment]
One connection in this client (and ever other client for the protocols RabbitMQ supports that I can think of) uses 1 TCP connection under the hood. Since a TCP connection has only two ends by definition, there is only one way to have two connections: open two separate connections.

**Comment by chatmoa** [comment]
Sorry, just see that I use the same global var for referencing channels of the two connections :-(

**Comment by cressie176** [comment]
If you're not transforming the message you could also create a shovel between the two clusters.
