### ISSUE TITLE
Is sendToQueue async or not?

### ISSUE THREAD

**Issue by morzzz007** [squaremo/amqp.node#336]
Hi,

Extending the example from documentation with process exit after calling sendToQueue results no items inserted into the queue although it behaves like a sync operation. 
Is this intentional or a bug or what am I doing wrong here?

```
'use strict';

const open = require('amqplib').connect('...');
const q = 'random-queue-name';

open.then(function(conn) {
  return conn.createChannel();
}).then(function(ch) {
  return ch.assertQueue(q).then(function(ok) {
    return ch.sendToQueue(q, new Buffer('something to do'));
  });
})
.then(() => {
  process.exit(0);
})
.catch(console.warn);
```

**Comment by michaelklishin** [comment]
There is [no response method for `basic.publish` in the protocol](http://www.rabbitmq.com/amqp-0-9-1-quickref.html#basic.publish) (publisher confirms do not count), so all publishing is entirely asynchronous until a particular client library tries to wait for something. I doubt this one does.

What evidence do you have that it "behaves like a synchronous operation"?

**Comment by squaremo** [comment]
> calling sendToQueue results no items inserted into the queue although it behaves like a sync operation

Most likely what's happening is that the process exits before the message is written to the wire. If you don't explicitly exit, Node.JS will just stay running until there's no more I/O to do; but since you're telling it to exit, it drops everything on the floor.

A good way to exit gracefully and make sure everything has been done is to synchronise on `channel.close()`.

**Comment by michaelklishin** [comment]
to add to @squaremo's plausible theory (which actually confirms that message delivery is entirely asynchronous), see [Publisher Confirms](http://www.rabbitmq.com/confirms.html). They may or may not be sufficient over simply closing the channel if you want the process to exit but you should be aware of them.

**Comment by morzzz007** [comment]
Thank you for your help, I was unaware of how AMQP/RabbitMq works behind the curtains. 
Just by looking at the code I thought it's a sync operation, since it's not a promise or anything and by the time it returns the item will be at least written on the wire (hence the name sendToQueue and not eventuallySendToQueue) and on its way somewhere so the process can exit. But as far as I understand it's more of general AMQP question and not the responsibility of this library.
Again, thanks for pointing me in the right direction!
