### ISSUE TITLE
[Question] Is there 'connection pooling' like mongoose?

### ISSUE THREAD

**Issue by dustyhorizon** [squaremo/amqp.node#337]
Hi,

As the question states, is there a form of 'connection pooling' like mongoose?

e.g. mongoose.connect once from app.js and requiring mongoose from another.js will use the same mongoose object/connection from app.js?

**UPDATE**
Just stumbled upon the concept of singletons, is this a correct way to implement?
```
import amqp from 'amqplib'

let amqpClient

export default (uri = 'amqp://localhost', options = {}) => {
    if (amqpClient) return amqpClient
    amqp.connect(uri, options)
        .then((connection) => {
            amqpClient = connection
            return amqpClient
        })
        .catch((err) => {
            if (err) throw err
        })
}
```

**Comment by michaelklishin** [comment]
The singleton pattern and object pooling are arguably the opposite. Which one is it that you want?

In a single threaded/process environment such as Node.js using a singleton connection can work OK
as long as you take recovery from connection failures into consideration.

**Comment by dustyhorizon** [comment]
Actually looking for behavior similar to how mongoose works, where I can just call mongoose and use the current connection that was connected previously.

**Comment by squaremo** [comment]
This behaviour is not provided in the library, but you can certainly build it yourself without too much trouble. Just remember to synchronise everything on the connection being open, e.g., by using the promise returned from `connect()`.

There are a few errors that will kill a connection, and it can be closed remotely; probably your best option is to let it all crash when that happens, and restart the process. You can attach `'error'` handlers to do clean up, if necessary.

**Comment by dustyhorizon** [comment]
Oops, didn't mean to close and reopen. Thanks for the advice guys!
