### ISSUE TITLE
Reuse same connection and channel 

### ISSUE THREAD

**Issue by iammehrabalam** [squaremo/amqp.node#347]
I am using Expressjs and socket.io in my project and for storing user events using Rabbitmq (for async processing).

For this currently I am creating and closing connection and channel for every request and this is too costly. i am using this example [https://github.com/squaremo/amqp.node/blob/master/examples/tutorials/send.js](url)

How can I use amqplib in production?  
       **OR**
How can I reuse same connection and channel for every request?

plz help using example (i am new in javascript world)

**Comment by cressie176** [comment]
@iammehrabalam 

> How can I use amqplib in production?
Is too broad a question to yield a helpful answer.

> How can I reuse same connection and channel for every request?
Keep a reference to the channel and re-use it.
