### ISSUE TITLE
Trouble ACKing a message received via channel.get

### ISSUE THREAD

**Issue by vikasrohit** [squaremo/amqp.node#348]
I am trying to write a schedule job which would fetch (via `channel.get`) X number of messages, process them and ACK/NACK them based on message content.  The reason for choosing `channel.get` over `channel.consume` is to avoid forceful killing (I need to kill the process because it is scheduled job) of the process when it is processing a message.
Now, the problem is that even if I am always ACKing in the code, server is nacking the message as soon as the message is fetched and never ACKing the message.
Here is the original code where code is ACKing/NACKing based on business logic:
```javascript
function processMessage(channel, msg) {
  return new Promise((resolve, reject) => {
    if (!msg) {
      reject(new Error('Empty message. Ignoring'));
    }
    const key = _.get(msg, 'fields.routingKey');
    debug('Received Message', key, msg.fields);

    let handler;
    let data;
    try {
      handler = EVENT_HANDLERS[key];
      if (!_.isFunction(handler)) {
        channel.nack(msg, false, false)
      }
      data = JSON.parse(msg.content.toString());
    } catch (ignore) {
      logger.info(ignore);
      logger.error('Invalid message. Ignoring');
      channel.ack(msg);
      reject(new Error('Invalid message. Ignoring'));
    }
    return handler(logger, data).then(() => {
      channel.ack(msg);
      resolve(msg);
    })
    .catch((e) => {
      if (e.shouldAck) {
        debug("ACKing for Unprocessable Error in handler...");
        channel.ack(msg);
      } else {
        debug("NACKing for Error in handler...")
        // NACK and requeue (nack requeues by default) the message for next turn
        channel.nack(msg);
      }
      reject(new Error('Error processing message'));
    });
  })
}

try {
  // code to create connection and channels... it uses await to forcefully fetch results from promises
  // assertExchangeQueues asserts all required exchanges and queues
  assertExchangeQueues(
    channel,
    exchange,
    queue
  ).then(() => {
    debug('Asserted all required exchanges and queues');
      return channel.get(queue)
      .then((msg) => {
        if (msg) {
          return processMessage(
            channel,
            msg
          ).then((responses) => {
            debug('Processed message');
            close(channel);
          }).catch((e) => {
            debug('Processed message with Error');
            close(channel);
          })
        } else {
          debug('Processed message');
          close(channel);
        }
      }).catch(() => {
        console.log('get failed')
      })
    })
} catch (e) {
  logger.logFullError(e, 'Unable to connect to RabbitMQ');
}
```
Any help would appreciated.

**Comment by michaelklishin** [comment]
Just like with basic.consume, you must specify [acknowledgement mode](http://www.rabbitmq.com/confirms.html) to basic.get, as this client seems to default to automatic. Otherwise how would RabbitMQ know that an ack will be coming?

**Comment by vikasrohit** [comment]
Thanks @michaelklishin for the quick reply. However, I am not sure how do I specify acknowledgement mode with `channel.get`.

**Comment by cressie176** [comment]
@michaelklishin according to the docs acknowledgement mode defaults to false. Since @vikasrohit's code `return channel.get(queue)` doesn't specify any options I don't think the RabbitMQ will be auto acknowledging

> noAck (boolean): if true, the message will be assumed by the server to be acknowledged (i.e., dequeued) as soon as it's been sent over the wire. Default is false, that is, you will be expected to acknowledge the message.

**Comment by cressie176** [comment]
@vikasrohit do you mean the broker is nacking messages, or something in the node app. What leads you to this conclusion?

Also it looks like you have a bug on this line...

```
    return handler(logger, data).then(() => {
```
If there's no match for the routingKey in EVENT_HANDLERS it will be undefined, and you'll get an exception

**Comment by vikasrohit** [comment]
@cressie176 You are right about the default to `channel.get` and that why my intention for not specifying any option with it.

for bug about missing EVENT_HANDLERS, I am checking that before calling that
```javascript
    if (!_.isFunction(handler)) {
      channel.nack(msg, false, false)
    }
```
Though I should resolve the promise as well after nacking here. However, I can assure you that code is always finding the handler in my case.

**Comment by cressie176** [comment]
> for bug about missing EVENT_HANDLERS, I am checking that before calling that

I see that, however your code will still fall through to call

```return handler(logger, data)```

and at this point the handler would still be undefined, throwing an error. The error would be caught and eventually handled by the following code...

```
        debug("NACKing for Error in handler...")
        // NACK and requeue (nack requeues by default) the message for next turn
        channel.nack(msg);
```

meaning the message would be nacked twice, resulting in another error. I still think it's a bug, but if you're sure you always get a handler I agree it's not causing any problems. However I'd still like to know whether you think it's the RabbitMQ broker which is automatically nacking messages, or whether something in the node application, and what leads you to believe this.

**Comment by vikasrohit** [comment]
> I still think it's a bug, but if you're sure you always get a handler I agree it's not causing any problems.

Yes, it is a bug. I would resolve the promise if handler is not found.
>However I'd still like to know whether you think it's the RabbitMQ broker which is automatically nacking messages, or whether something in the node application, and what leads you to believe this.

I always doubt my code first, however, here I have tried replacing all nack calls with ack calls to check if it is my code which is failing. The result was same even after replacing all nack calls with ack calls. :( My doubt is either some configuration missing for channel.get or my promise chain in conjunction with a bug in amqplib is the culprit.

**Comment by cressie176** [comment]
> The result was same even after replacing all nack calls with ack calls

What's the actually result? E.g. are you looking in the web ui and seeing messages being nacked / redelivered / dead lettered?

**Comment by vikasrohit** [comment]
Oh, sorry missed that information. Yes, I am looking at the Admin UI provided by cloudamqp (we are using hosted rabbitmq from cloudamqp).

**Comment by cressie176** [comment]
Screenshot?

**Comment by vikasrohit** [comment]
<img width="740" alt="screen shot 2017-04-20 at 1 50 27 pm" src="https://cloud.githubusercontent.com/assets/2417632/25220740/5c1e05c4-25d0-11e7-960c-d0847400debf.png">

**Comment by cressie176** [comment]
Sorry - have to park this for the moment. Will look later, however I don't see any redeliveries so the messages aren't being nacked with requeue, and they're also not being consumed (acked or nacked without requeue)

**Comment by cressie176** [comment]
I wonder if the channel is being closed before the message ack / nack has been completed?

**Comment by vikasrohit** [comment]
Yes, they are not being acked or nacked either.

>I wonder if the channel is being closed before the message ack / nack has been completed?

I can see the channel being open in the Admin panel until my process exits. I have put 100 seconds delay to stop existing before completion of channel requests.

**Comment by vikasrohit** [comment]
Sorry for the troubles, it seems @cressie176 the doubt about channel/connection being closed before being acked was right. I have put sleep.sleep to wait for few seconds before closing the connection, however, that caused all async methods to block as well. That means it blocked the channel.ack call as well. And the sleep wakes, it immediately closes the connection and channel.ack still trying to ack the message.
So, finally I used setTimeout for closing connection after waiting for few seconds to give enough time to channel.ack to ack the message.
Thanks all for the help.
