### ISSUE TITLE
Flow control 

### ISSUE THREAD

**Issue by manntsheth** [squaremo/amqp.node#351]
Flow control mechanism for amqp.node

**Comment by michaelklishin** [comment]
@manntsheth it's a little terse. What do you expect the maintainer to do with a brief single sentence issue?

Client-driven flow control hasn't worked very well in AMQP 0-9-1 and the flow/recover methods are considered to be deprecated.

RabbitMQ nodes will apply [internal flow control](https://www.rabbitmq.com/flow-control.html) as well as [resource-driven flow control](http://www.rabbitmq.com/alarms.html) by throttling publishers as needed.

Clients can [register to receive notifications](https://www.rabbitmq.com/connection-blocked.html) about when they are blocked by a resource-driven alarm.
