### ISSUE TITLE
Get message number to be processed on queue  

### ISSUE THREAD

**Issue by claudiopetrini** [squaremo/amqp.node#357]
Hello,
this issue is more a request for guidance rather than an issue.
Is there a way to know how many messages are left to be processed in the queue?

The bigger problem I'm trying to solve is to delete a queue only when there are no messages left but a consumer is still registered on it. Using the RabbitMQ `autoDelete` feature won't work since it removes the queue only when there are no consumers attached.

Thank you.

**Comment by michaelklishin** [comment]
A `queue.declare` response (`queue.declare-ok`) has two fields that indicate the number of messages ready to be delivered and the number of consumers. This is true for passive declares as well.

And then there is [an HTTP API](http://www.rabbitmq.com/management.html) that provides a lot more information about queue state.

**Comment by michaelklishin** [comment]
See [queue.declare-ok](http://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.declare-ok) field description on rabbitmq.com.

**Comment by claudiopetrini** [comment]
Hello @michaelklishin ,
thank you that was exactly was I was looking for!
