### ISSUE TITLE
clusterId not mapped in module

### ISSUE THREAD

**Issue by NilsFrkal** [squaremo/amqp.node#361]
Hi experts,

I am using RPC across multiple workers. In order to associate the message to the correct consumer I need to identify the worker who had initiate the message. I wanted to use "clusterId" which is a standard property. However, in the mapping of the properties I see:

  return {
    // method fields
    exchange: exchange,
    routingKey: routingKey,
    mandatory: !!options.mandatory,
    immediate: false, // RabbitMQ doesn't implement this any more
    ticket: undefined,
    // properties
    contentType: options.contentType,
    contentEncoding: options.contentEncoding,
    headers: headers,
    deliveryMode: deliveryMode,
    priority: options.priority,
    correlationId: options.correlationId,
    replyTo: options.replyTo,
    expiration: expiration,
    messageId: options.messageId,
    timestamp: options.timestamp,
    type: options.type,
    userId: options.userId,
    appId: options.appId,
    clusterId: undefined
  };

Why is clusterId mapped to undefined?

Thank you very much.

Best, Nils

**Comment by michaelklishin** [comment]
I don't see any reason for this client to not propagate the value except that I have never seen `clusterId` actually used.

**Comment by cressie176** [comment]
Could it be because clusterId was depreciated? Any reason not to set your own property?

**Comment by michaelklishin** [comment]
I'm not aware of it being deprecated. What matters, however, is what are its chances of being removed from the protocol. The answer is "virtually none."

**Comment by NilsFrkal** [comment]
Thanks for the responses. Re "own property", can this be set on the options or only as part of the message content? I just don't understand the mapping to undefined, i.e. either it should be fully ignored or simply options.clusterId :-)

**Comment by michaelklishin** [comment]
@NilsFrkal only @squaremo really knows but sounds like it can be `options.clusterId`. You can try it and see what a different client, e.g. Bunny, receives in message properties ;)

**Comment by cressie176** [comment]
@michaelklishin https://www.rabbitmq.com/releases/rabbitmq-dotnet-client/v3.4.2/rabbitmq-dotnet-client-3.4.2-client-htmldoc/html/type-RabbitMQ.Client.IBasicProperties.html

> intra-cluster routing identifier (cluster id is deprecated in AMQP 0-9-1)

(although I agree depreciated != removed)

@NilsFrkal try the following...

```
options = { messageId: 'foo', clusterId: 'bar', headers: { producerId: 'baz' } }
```

**Comment by michaelklishin** [comment]
@cressie176 there is no shortage of things that were deprecated and then were undeprecated or never were deprecated but nobody really uses them. See [AMQP 0-9-1 Errata](http://www.rabbitmq.com/amqp-0-9-1-errata.html). Anyhow, the chances of this property being removed are very low but I also haven't seen a system that uses it :)

**Comment by cressie176** [comment]
@NilsFrkal looks like clusterId is [hard coded to undefined](https://github.com/squaremo/amqp.node/blob/master/lib/api_args.js#L242). No idea why.

**Comment by squaremo** [comment]
This is what the published spec says:
https://github.com/rabbitmq/rabbitmq-public-umbrella/blob/master/rabbitmq-docs/specs/amqp0-9-1.xml#L2372 (field renamed to "reserved"; accompanying text says "reserved, must be empty")

As it happens, the codec doesn't treat reserved fields specially and neither does RabbitMQ, because they both use a translation of the spec that restores all the field names and ignores the text. So in principle it could send a clusterId.

However, `clusterId` and `ticket` (and others?) are hardcoded to `undefined` because if they weren't, it could break any client that goes by the letter of the spec and expects them to be empty.

I suspect the cases where RabbitMQ has "undeprecated" things are all in RPCs -- i.e., between the client and server -- whereas `basic.properties` is sent on to other clients.

**Comment by squaremo** [comment]
@NilsFrkal I'm not sure I quite get your use case. Is it one of these:

 * You want the response to an RPC to be routed back to its requester, and they are both connected to the same RabbitMQ server or cluster (in which case, you should use the field "replyTo" and treat it as a queue name or routing key)
 * You want to the response to an RPC to be routed back to it requester, but naming a queue or routing key is not sufficient for this (e.g., responses must be sent to a particular host, or .. ?)
 * A worker must process messages differently depending on where they came from (in which case, include that information in the message body or headers).

.. or something else?

**Comment by NilsFrkal** [comment]
Gents, thanks a lot for the productive input. I am happy to close this issue now. 

Just before I do so, I wanted to anwser Michael's question re use case. Firstly, we are using RabbitMQ for 2 reasons: 

1. message persistence (i.e. we cannot afford to loose a message)
2. workload distribution (prefetch = 1)

We have an API which is called externally. The API is exposed on multiple workers with load balancing sitting on top. When the API is called it writes the request as a message to a single request queue which will get picked up by any free worker to process the message. The response however needs to be synchronous, so the API waits for the response. As we have potentially multiple APIs waiting for the response we have to ensure the response is send to the correct API worker - this is where we wanted to use the clusterId.

We did this with an event emitter which emitted the correlation id and workClusterId as key. When the listening API received this event it responded back to the caller. 

Alternatively we could create a unique response queue per worker.

Any feedback/thoughts on this approach would be highly appreciated.

Thank you very much.

**Comment by squaremo** [comment]
@NilsFrkal A common pattern is to create a channel with an ephemeral queue for each worker process, and set `replyTo` to the queue name. There's even a shortcut for this in RabbitMQ: http://www.rabbitmq.com/direct-reply-to.html (this is all done in the server, so if you follow the instructions, it should work with amqplib).

**Comment by NilsFrkal** [comment]
Great, thanks a lot. Will close this issue now. Best, Nils
