### ISSUE TITLE
How to get sendToQueue response without having to wait for it to be consumed

### ISSUE THREAD

**Issue by yawhide** [squaremo/amqp.node#369]
Hello, got a question, dont know how to explain without giving an example.

### producer, machine 1
```
ch.sendToQueue('rpc_queue',  new Buffer(num.toString()), (err, result) => {
  console.log("the ch.consume method has (n)acked, we waited 100000000ms");
});
```

### consumer, machine 2
```
ch.consume('rpc_queue',  (msg) => {
  setTimeout(() => ch.ack(msg), 100000000);
});
```

Is there a way for me to call `ch.sendToQueue` and get the callback to simply get called when mq has received the message (And not have to wait for ch.consume to (n)ack). Maybe the callback only has an error argument?

Thanks

EDIT: rewrote

**Comment by michaelklishin** [comment]
I highly doubt that any publishing function calls a callback when a consumer does anything. Publishers are entirely unaware of consumers.

See [publisher confirms](http://www.rabbitmq.com/confirms.html), [heartbeats](http://www.rabbitmq.com/heartbeats.html). On top of that if a message is published as mandatory and cannot be routed anywhere, it will be returned to the publisher. There is nothing in the protocol that assumes publisher-consumer awareness. [Tutorial 6](http://www.rabbitmq.com/getstarted.html) demonstrates how that can be arranged.

**Comment by yawhide** [comment]
rewrote the main post

**Comment by michaelklishin** [comment]
@yawhide have you seen this [publisher confirms example](https://github.com/squaremo/amqp.node/blob/master/examples/waitForConfirms.js)? There may be a callback-oriented way of doing it as well but you'd have to dig the source.

**Comment by cressie176** [comment]
@yawhide as @michaelklishin says, the producer doesn't wait for the message to be acked / nacked by the consumer. Either I'm still not understanding your question, or there's something else strange about what you're witnessing.

The following code demonstrates the sendToQueue callback is called before the consumer acknowledges the message.
```js
var amqp = require('amqplib/callback_api')

amqp.connect((err, connection) => {
  if (err) throw err
  connection.createConfirmChannel((err, channel) => {
    if (err) throw err
    channel.assertQueue('q', {}, (err, ok) => {
        if (err) throw err
        channel.sendToQueue('q', new Buffer('meh'), {}, (err, ok) => {
          if (err) throw err
          console.log(Date.now(), 'sent')
      })
    })
  })
})

amqp.connect((err, connection) => {
  if (err) throw err
  connection.createConfirmChannel((err, channel) => {
    if (err) throw err
    channel.assertQueue('q', {}, (err, ok) => {
        if (err) throw err
        channel.consume('q', (msg) => {
          console.log(Date.now(), 'received')
          setTimeout(() => {
            channel.ack(msg)
            console.log(Date.now(), 'acknowledge')
          }, 5000)
      })
    })
  })
})

setInterval(() => {}, 10000)
```

### Output
```
1501945361785 'sent'
1501945361788 'received'
1501945366794 'acknowledge'
```

**Comment by yawhide** [comment]
thank you @cressie176. 

I was using regular `channel.createChannel` instead of the confirm channel.
