### ISSUE TITLE
How can I use amqplib in nodejs 8.x ?

### ISSUE THREAD

**Issue by taoqf** [squaremo/amqp.node#370]
```
WARN node unsupported "node@v8.2.1" is incompatible with xxx › amqplib@latest, expected node@>=0.8 <6 || ^6
```
Any Idea?

**Comment by vpetroff** [comment]
Same here, npm throws ENOTSUP on node 8.2.1

**Comment by hartzis** [comment]
the problem right here?
https://github.com/squaremo/amqp.node/blob/master/package.json#L12

**Comment by osukaa** [comment]
That's a warning and is not really stopping you from using the library. They would have to update the engines field in the package.json when they have tested the library against v8.x.x

**Comment by taoqf** [comment]
not at all. I will close this issue.
