### ISSUE TITLE
How do you securely connect to a cluster using Compose.io?

### ISSUE THREAD

**Issue by seanlindo** [squaremo/amqp.node#371]
I've followed the tutorial [at this link](https://help.compose.com/v2.0/docs/rabbitmq-connecting-to-rabbitmq). It references this library, so I followed it step-by-step.

I get the following error each time: `Error: unable to verify the first certificate`. The common fix I've found online is to apply the servername variable as seen in #331. If this worked before, it's no longer working. 

*Node Version*: v6.9.5
*Library Version*: v0.5.1

**Comment by michaelklishin** [comment]
I'd start with [RabbitMQ's TLS troubleshooting guide](http://www.rabbitmq.com/troubleshooting-ssl.html) instead of randomly applying suggestions from the interwebs. Also consider positing the entire stack trace instead of a single line as well as server logs.

**Comment by seanlindo** [comment]
Thanks for your help.

**Comment by dylanjt** [comment]
![a gif](https://i.giphy.com/ZEmYj5XWiPoti.gif)
