### ISSUE TITLE
Control how many tasks are in the queue

### ISSUE THREAD

**Issue by jsifalda** [squaremo/amqp.node#373]
Hello, I would like to know if there is a way how to control number of tasks in the queue? 
Here is what I want to achieve: 
1) There is a queue called eg. cron.job.matches
2) There is a worker which process tasks in this queue (with prefetch=1)
3) Cron microservice publishes tasks cron.job.matches, however in case the worker still has not finished the previous task, it should not publish the same tasks again. 
(In other words, before publishing tasks into the rabbit queue, the system would have to check if there is a running task and if so, discard the publish event)

Summary: 
Only one tasks is processing at the same time, and only one task can be queued in the queue. 
I can achieve it with adding of high level abstraction, however I was wondering if something like this can be done in rabbitmq or this lib level?
 Thank you very much in advance

**Comment by michaelklishin** [comment]
See tutorial 2, [consumer acknowledgements documentation](http://www.rabbitmq.com/confirms.html) and [queue length limit](http://www.rabbitmq.com/maxlength.html).

Or consider using a lock service (ZooKeeper, Consul, etc) in your consumers to coordinate because that's what your problem comes down to.

**Comment by jsifalda** [comment]
Thanks @michaelklishin. 
Is there any example how to pass "x-max-length" param into queue with this lib?

**Comment by michaelklishin** [comment]
@jsifalda have you checked the [examples directory](https://github.com/squaremo/amqp.node/blob/master/examples/headers.js)? And the docs on [policies](http://www.rabbitmq.com/parameters.html#policies)?

**Comment by jsifalda** [comment]
thank you very much
