### ISSUE TITLE
Question: consume message exclusively while routing 

### ISSUE THREAD

**Issue by adityaanandmc** [squaremo/amqp.node#376]
**Ref:**  [routing example](https://github.com/squaremo/amqp.node/tree/master/examples/tutorials#tutorial-four-routing)

**Scenario:** 2 consumer and 1 producer
Message published by producer -> gets consumed by both consumers ( as shown in the img )
 
![image](https://user-images.githubusercontent.com/5358146/30772258-b041f834-a075-11e7-9958-338eaddf856c.png)

Ideally setting `{exclusive: true}` [here](https://github.com/squaremo/amqp.node/blob/master/examples/tutorials/receive_logs_direct.js#L33) would ensure that the message would be exclusively consumed by just one,however it ends up being consumed by all consumers listening to it. 

Any idea where I messed up ? 
More info : [here](https://stackoverflow.com/questions/46327813/setting-exclusive-as-true-in-rabbitmq-for-consumer)

**Comment by cressie176** [comment]
Do the consumers share a connection?

https://www.rabbitmq.com/amqp-0-9-1-reference.html

> Exclusive queues may only be accessed by the current connection, and are deleted when that connection closes. Passive declaration of an exclusive queue by other connections are not allowed.

**Comment by adityaanandmc** [comment]
Thanks for pointing that out 😄 Rookie mistake
