### ISSUE TITLE
This example is run in my computer,an error is：Error：connect ECONNREFUSED 127.0.0.1:5672

### ISSUE THREAD

**Issue by leesasa** [squaremo/amqp.node#382]
node -v
v6.10.2
:\Users\WebstormProjects\untitled3>node send.js
{ Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:5672
       at Object.exports._errnoException (util.js:1018:11)
       at exports._exceptionWithHostPort (util.js:1041:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5672 },
  isOperational: true,
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }

C:\Users\WebstormProjects\untitled3>node receive.js
{ Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  cause:
   { Error: connect ECONNREFUSED 127.0.0.1:5672
       at Object.exports._errnoException (util.js:1018:11)
       at exports._exceptionWithHostPort (util.js:1041:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
     code: 'ECONNREFUSED',
     errno: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 5672 },
  isOperational: true,
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672 }

**Comment by cressie176** [comment]
Hi @leesasa

I'll try to help. First thing is, when you paste console output or code samples, it makes it easier to read if you format it using [markdown](https://guides.github.com/features/mastering-markdown/).  e.g.
```
node -v
v6.10.2
:\Users\WebstormProjects\untitled3>node send.js
{ Error: connect ECONNREFUSED 127.0.0.1:5672
at Object.exports._errnoException (util.js:1018:11)
at exports._exceptionWithHostPort (util.js:1041:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
cause:
```
The above is wrapped in triple backticks.

Now on to the problem. As you may have guessed ```ECONNREFUSED 127.0.0.1:5672```, means amqplib cannot connect to a RabbitMQ server running on your development machine. It is possible that 

* you haven't started the RabbitMQ server
* something such as a firewall is blocking the connection to the RabbitMQ server
* you meant to connect to a server running on a different host or port.

### Starting RabbitMQ server
The easiest way to start RabbitMQ on your development machine is to use a containerisation technology called  [docker](https://www.docker.com/). Once you have docker installed, you can start RabbitMQ locally by running
```
$ docker run -d -p 5672:5672 -p 15672:15672 rabbitmq:3.6-management-alpine
d5dacf76743c2d6740025d9207bdb15d9ad4fdd241bbf63191a7689f303d0c3c
```
Then run docker ps to check the container
```
$ docker ps
CONTAINER ID        IMAGE                                                    COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
d5dacf76743c        rabbitmq:3.6-management-alpine                           "docker-entrypoint..."   6 seconds ago       Up 5 seconds        4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   brave_swirles
```

### Checking connectivity
If you are sure that the RabbitMQ server is running locally on port 5672, and providing you're using a linux / osx based operating system you can use the netcat command to check connectivity.
```
$ nc -v localhost 5672
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif lo0
	src ::1 port 61061
	dst ::1 port 5672
	rank info not available
	TCP aux info available

Connection to localhost port 5672 [tcp/amqp] succeeded!
```
If you get a failure and you are sure that RabbitMQ is running on port 5672 then investigate whether you have a firewall enabled. If you're using a windows based operating system, you can either find a netcat equivalent or use telnet
```
telnet localhost 5672
```

### Configuring amqplib for a different host or port
Please refer to the [amqplib client api](http://www.squaremobius.net/amqp.node/channel_api.html#connect)

**Comment by leesasa** [comment]
thanks

**Comment by cressie176** [comment]
Did you get it resolved? If so please close the issue.

**Comment by rameshakkivarapu** [comment]
Thank you

**Comment by liverbool** [comment]
in case of docker to docker connection try to change `localhost` to `your_docker_name`.

**Comment by dynshon** [comment]
I have same problem on Win10 launching tutorial file send.js.

I can't use Docker.

```
Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5672
}
```

**Comment by cressie176** [comment]
> ECONNREFUSED (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.

[ECONNREFUSED](https://nodejs.org/api/errors.html) means

i.e. this isn't likely to be a problem with amqplib. Instead it's probably that you haven't successfully installed/started [RabbitMQ](https://www.rabbitmq.com/) on localhost, port 5672. Another option is that something in your environment (e.g. a firewall) is blocking network access to that port.

**Comment by dynshon** [comment]
Thank for answer.
If I run rabbitmq-server it works fine, but I have ECONNREFUSED when I run it as service.
What should I check?

**Comment by cressie176** [comment]
Hi @dynshon, I can't help you very much with that. I haven't used windows for about 10 years. However, my guess would be that the service is failing to start properly. I would try the steps outlined above (e.g. check that something is listening on 5672) and try to find the server error logs. Double check the [service documentation](https://www.rabbitmq.com/rabbitmq-service.8.html) and if all else fails, post a message to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

**Comment by nguyentuyetnhi** [comment]
how to install rabbitmq on mac os

**Comment by cressie176** [comment]
Hi @nguyentuyetnhi,
The easiest way to install [RabbitMQ](https://www.rabbitmq.com/) on your macbook is using [docker](https://www.docker.com/). You can find instructions [here](https://www.rabbitmq.com/docs/download)
