### ISSUE TITLE
url decode username and password

### ISSUE THREAD

**Issue by travisghansen** [squaremo/amqp.node#385]
From what I can tell the library doesn't support a `:` (colon) in the username.  I'm encoding it in my configuration and it still appears to be failing.  Any tips/thoughts?

**Comment by squaremo** [comment]
If you supply a username and password in the URL, like `amqps://foo:bar@localhost`, it'll interpret the bit before the first colon as the username. If you need to include a colon in the username, you can use an object instead of a string, as described under http://www.squaremobius.net/amqp.node/channel_api.html#connect.

**Comment by travisghansen** [comment]
@squaremo unfortunately I'm using this library via a higher-level library (nodered node) and don't really have access to that.  Shouldn't a properly encoded set of credentials work (a la curl, etc)?

**Comment by squaremo** [comment]
The trouble is that `url.parse` decodes the auth value (`user:password`), so the value that amqplib sees has already had any percent-encoded colons (`'%3A'`) turned into `':'`, and any unencoded colons ':' are also ':'. There's no way to tell which were part of the username.

There are a couple of options for improving the situation. From Node 7.0 onwards, there's a  different URL parser available in the standard lib which supplies the username and password separately (and presumably deals with percent encoding properly on the way). Failing that, or for older Node, I guess someone could write a URL parser, at least for the first part of the URL.

**Comment by travisghansen** [comment]
Wow awesome!  I'll have to wait for a new version to hit before trying this out probably if you want some testing tried on it.
