### ISSUE TITLE
Extra properties in ch.sendToQueue() are not showing on the message

### ISSUE THREAD

**Issue by nareshbhatia** [squaremo/amqp.node#393]
I am using `ch.sendToQueue()` to send a message with 5 properties - 3 that are "meaningful" to RabbitMQ and 2 that are not. When I look in the RabbitMQ Management Interface, I can see the 3 meaningful properties on the message, but the other 2 are missing. Am I doing something wrong in the call below?

```
const conv_id = uuidV4();
const conv_auth = "1234";
console.log('conv_id', conv_id);
console.log('conv_auth', conv_auth);
ch.sendToQueue(sendQueue, new Buffer(JSON.stringify(payload)), {
    contentType: 'text/plain',
    correlationId,
    replyTo: this.replyToQ,
    // conversational properties
    conv_id: conv_id,
    conv_auth: conv_auth
});
```

**Comment by cressie176** [comment]
> headers (object): application specific headers to be carried along with the message content. The value as sent may be augmented by extension-specific fields if they are given in the parameters, for example, ‘CC’, since these are encoded as message headers; the supplied value won’t be mutated.

I can never remember the right syntax for this. It could be 
```
ch.sendToQueue(sendQueue, new Buffer(JSON.stringify(payload)), {
    contentType: 'text/plain',
    correlationId,
    replyTo: this.replyToQ,
    // conversational properties
    headers: {
        conv_id: conv_id,
        conv_auth: conv_auth
     }
});
```

**Comment by nareshbhatia** [comment]
You hit it on the head! The language at the beginning of the method description made me feel like you can bunch up the "meaningful" and "non-meaningful" properties at the same level. I think adding some explicit language around this and an example would be very valuable.

Thanks so much for your help, @cressie176!
