### ISSUE TITLE
#connect don't reject a promise and try to execute a callback

### ISSUE THREAD

**Issue by exos** [squaremo/amqp.node#401]
I have the next code:

```ES7
               try {                     
                    logger.info(`Connecting with amqp`);                             
                    connection = await amqp.connect(AMQP_URI);                
                } catch (e) {             
                    logger.warn(`Error connection to ${AMQP_URI}`, e.message);       
                    logger.warn(`trying in ${AMQP_TRY_TIME}ms`);                     
                    throw e;
                    await new Promise((r) => setTimeout(r, AMQP_TRY_TIME));          
                }            
```

And get

    *****-microservice-test_1  | 2018-01-19T15:37:01.726Z [com.*****.microservice.*****.rcplib.connection] info: Connecting with amqp                                
    *****-microservice-test_1  | 2018-01-19T15:37:01.738Z [com.*****.microservice.*****.rcplib.connection] warn: Error connection to amqp://rabbitmq                 
    *****-microservice-test_1  | 2018-01-19T15:37:01.739Z [com.*****.microservice.*****.rcplib.connection] warn: trying in 3000ms
    *****-microservice-test_1  |                                                                                                                                             
    *****-microservice-test_1  | /src/node_modules/amqplib/lib/connect.js:187                                                                                                *****-microservice-test_1  |     if (!sockok) openCallback(err);                                                               
    *****-microservice-test_1  |                  ^                                                                                                                          
    *****-microservice-test_1  | TypeError: cb is not a function                                                                                                             *****-microservice-test_1  |     at /src/node_modules/amqplib/callback_api.js:16:10                                                                                      
    *****-microservice-test_1  |     at Socket.<anonymous> (/src/node_modules/amqplib/lib/connect.js:187:18)                                                                 
    *****-microservice-test_1  |     at Object.onceWrapper (events.js:315:30)                                                                                                
    *****-microservice-test_1  |     at emitOne (events.js:116:13)                                                                                                           *****-microservice-test_1  |     at Socket.emit (events.js:211:7)                                                                                                        
    *****-microservice-test_1  |     at emitErrorNT (internal/streams/destroy.js:64:8)                                                                                       *****-microservice-test_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)                                                                         
    *****-microservice-test_1  |     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by fossejc** [comment]
I have the same bug. connect tries to call a callback instead of rejecting the promise
