### ISSUE TITLE
Best practices about RPC pattern

### ISSUE THREAD

**Issue by jdrouet** [squaremo/amqp.node#403]
I'm actually trying to implement the RPC pattern but I realise that the reply queues don't want to close. I don't really know if there is something wrong with my implementation or if there is a bug.

Here is my server
```javascript
const rabbit = require('amqplib');

const connection = rabbit.connect('amqp://guest:guest@localhost:5672');

const exchange = 'test';
const queue = 'login';

const listen = (ch) => async (msg) => {
  console.log('=> received', msg.content.toString());
  const {correlationId, replyTo} = msg.properties;
  await ch.sendToQueue(replyTo, msg.content, {correlationId});
};

connection
  .then((con) => con.createChannel())
  .then(async (ch) => {
    await ch.assertQueue(queue);
    await ch.assertExchange(exchange, 'topic');
    await ch.bindQueue(queue, exchange, 'login');
    return ch;
  })
  .then((ch) => ch.consume(queue, listen(ch), {noAck: true}));
```

and here is my client

```javascript
const rabbit = require('amqplib');
const uuid = require('uuid/v4');

const connection = rabbit.connect('amqp://guest:guest@localhost:5672');

const exchange = 'test';
const queue = 'login';

const channel = connection
  .then((con) => con.createChannel())
  .then(async (ch) => {
    await ch.assertExchange(exchange, 'topic');
    await ch.assertQueue(queue);
    await ch.bindQueue(queue, exchange, 'login');
    return ch;
  });

const sendMessage = (channel) => () => {
  const message = uuid();
  const body = new Buffer(message);
  const correlationId = uuid();
  const replyTo = uuid();
  console.log('=> send-message', message);
  return channel
    .then((ch) => new Promise((resolve) => {
      ch.assertQueue(replyTo, {exclusive: true});
      ch.consume(replyTo, (msg) => {
        if (msg.properties.correlationId !== correlationId) return;
        const content = msg.content.toString();
        console.log('<= received-message', content);
        setTimeout(() => ch.deleteQueue(replyTo), 100);
        return resolve(content);
      }, {noAck: true});
      ch.publish(exchange, queue, body, {correlationId, replyTo});
    }));
};

setInterval(sendMessage(channel), 2000);
```

So I have several questions:
- Is it a good practice to use the same channel to send several messages or should I recreate a channel each time ?
- When I keep the `deleteQueue`, the applications crashes (according to the documentation, `to teach you a lesson`). So should it be used?
- When I remove the `deleteQueue`, the queues stays alive (in the admin page) while the client is alive. Is it a good practice to let them hanging like this? Did I forget a parameter while creating the queue? I even tried with `x-expires` or `autoDelete` and it still stays alive...

Thank you

**Comment by cressie176** [comment]
> Is it a good practice to use the same channel to send several messages or should I recreate a channel each time ?

You can do either. Channels are fairly cheap to open and close, but do take a little time, but it's faster to re-use one via a pool or share it. In our application we started with a shared channels, but the consequence is that if the channel dies, it will affect more than one publish operation. We changed to one channel per publish, which was fine for normal operations, but slow for bulk exports. We ended up moving a [connection pool](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Publication.js#L55-L71) and got the best of both worlds, but for the cost of a little complexity.

**Comment by jdrouet** [comment]
@cressie176 in my case the problem is mainly that, for this pattern, every reply creates a new queue, that doesn't close automatically until the channel closes, even with some `x-espires` or `autoDelete` parameters. And when I try to delete the queue manually, the application crashes.
So, is it a big problem to keep those queues open? How should I close them? Should I reuse the queue for the same kind of replies?

**Comment by cressie176** [comment]
@jdrouet sorry - I haven't used reply queues.

**Comment by cressie176** [comment]
Did you read [this](https://www.rabbitmq.com/direct-reply-to.html)

**Comment by squaremo** [comment]
> So, is it a big problem to keep those queues open? How should I close them? Should I reuse the queue for the same kind of replies?

There is a cost per queue. I think thousands of queues are OK, but unbounded numbers of queues will eventually bring things to a halt. So you don't need to be sparing, but you do need to make sure you're not leaking queues.

If I recall, the standard practice is to use an `exclusive` queue, so that it gets cleaned up when the connection is closed. You could also make queues `auto-delete`, so that they go away when there's no more consumers (usually when the channel consuming from the queue closes).

If you can use RabbitMQ's "direct reply" feature, that is probably the best option: http://www.rabbitmq.com/direct-reply-to.html. If available from the server, you should be able to use it from this library as described there.
