### ISSUE TITLE
Message Properties always undefined

### ISSUE THREAD

**Issue by zelein** [squaremo/amqp.node#406]
I'm not sure if this is amqp or my environment.
The values in the properties object are always undefined within a Message.

```
{ 
    fields: {
        deliveryTag: 1,
        redelivered: false,
        exchange: 'events',
        routingKey: 'event.test.consume',
        messageCount: 0
    },
    properties: {
        contentType: undefined,
        contentEncoding: undefined,
        headers: {},
        deliveryMode: undefined,
        priority: undefined,
        correlationId: undefined,
        replyTo: undefined,
        expiration: undefined,
        messageId: undefined,
        timestamp: undefined,
        type: undefined,
        userId: undefined,
        appId: undefined,
        clusterId: undefined
    },
    content: <Buffer>
}
```
The header field correctly populates headers in cases like a dead letter, but I've yet to see any of the other properties be anything other than `undefined`. 

Is this a bug? Or my environment?

**Comment by cressie176** [comment]
The publisher is responsible for setting message properties if required. They're documented in the [channel api](http://www.squaremobius.net/amqp.node/channel_api.html) about 3/4 of the way down. The most important one for you to be aware of is deliveryMode, which amqplib makes more readable through he "persisted" pseudo property.

**Comment by zelein** [comment]
Ah, you are totally right. Thank you.

**Comment by cressie176** [comment]
> how to set it?

It's one of the publish options

https://amqp-node.github.io/amqplib/channel_api.html#channel_publish
