### ISSUE TITLE
Publisher Confirms: How to know which message was acked/nacked in the callback?

### ISSUE THREAD

**Issue by michaelgwelch** [squaremo/amqp.node#408]
The [blog entry from 2011](https://www.rabbitmq.com/blog/2011/02/10/introducing-publisher-confirms/) on Publisher Confirms describes how there are message identifiers (`seqNo` in the example) that can be used to track which messages are acked or not. In that example you can see how a list of messages pending ack is being maintained.

All of the examples using the nodejs library simply check the `err` object of the callback passed to `sendToQueue` or `publish` but none of them show you how you might get something analogous to the `seqNo` above.

Examples:

* https://github.com/squaremo/amqp.node/issues/405
* http://www.squaremobius.net/amqp.node/channel_api.html#confirmchannel

I see that many dotnet, Java, and JavaScript examples now use something like `waitForConfirms` to wait for all confirmations, but I still don't see what use that is if one or more did not succeed as none of the examples seem to tell you which messages was nacked.

The [Publisher Confirms Documentation](https://www.rabbitmq.com/confirms.html#publisher-confirms) describes the relevant details as such:

> The delivery-tag field contains the sequence number of the confirmed message. The broker may also set the multiple field in basic.ack to indicate that all messages up to and including the one with the sequence number have been handled.

But none of the recent APIs I've looked at explain how you would get access to the `delivery-tag` or the `multiple` field.

What am I missing?

**Comment by michaelgwelch** [comment]
I'm using an example loosely based on https://github.com/squaremo/amqp.node/issues/61 to publish large numbers of messages. I'm investigating what we'll need to do to be prepared to injest large numbers of messages and want to be sure I understand publisher confirms before I get too far. But I'm completely lost as to how they are supposed to be used in the present (compared to how they were described in 2011 in the blog post I link to above).

Seems to be a bit of a disconnect.

**Comment by michaelgwelch** [comment]
Note: I've used the debugger to check both the `err` object and `ok` object. In all my tests so far `err` is always null (no error) but `ok` is always undefined. This is where I'd expect to find some message identifier.

**Comment by michaelgwelch** [comment]
I guess I could use a "lambda expression factory" where some message id is injected into the lambda and when it's specifically invoked on callback I know which message it relates to.

**Comment by michaelgwelch** [comment]
I guess this works but it doesn't seem correct. But I certainly could make it work if I needed to:

```javascript
#!/usr/bin/env node
const amqp = require('amqplib');


async function main() {
  const conn = await amqp.connect('amqp://172.17.0.2');

  const ch = await conn.createConfirmChannel();

  const q = 'hello';
  await ch.assertQueue(q, { durable: true });

  var lost = 0;
  var sent = 0;
  const iterations = 100000;
  const go = () => {
    console.log(`Starting with ${sent}`);
    var keepGoing = true;
    while (keepGoing) {
      if (sent >= iterations) return;
      keepGoing = ch.sendToQueue(q, new Buffer(`Hello World! ${sent}`), { persistent: true, mandatory: true }, 
        createCallback(sent));
      sent++;
    }

    console.log(`Paused at ${sent}`);
    ch.once('drain', go);
  }
  go();

  console.log(" [x] Sent 'Hello World!'");

  var closed = false;

  setInterval(() => {
    if (sent >= iterations) {
      if (!closed) {
        closed = true;
        console.log(`Lost ${lost} messages.`);
        conn.close();
        console.log("Waiting 15 secs");
        setTimeout(() => {

          process.exit(0);

        }, 15000);
      }



    }
  }, 250);


}

function createCallback(id) {
  return (err, ok) => {
    if (err !== null) {
      lost++;
    }
    console.log(`${id} acked/nacked.`)
  }
}

main();
```

**Comment by squaremo** [comment]
The sequence numbers are usually considered internal bookkeeping, which is why they don't tend to appear in examples (after the 2011 blog post, when the feature were brand new). `waitForConfirms` was a later innovation.

That said, the bookkeeping is still carried out, and can be relied on (the protocol won't change). So there's no problem in principle with exposing it, in the way it's shown in that blog post.

As it stands, there are two expected modes of use:
 - Send every message with a callback that handles a delivery failure for that particular message (by, e.g., marking a database row as failed, or replying to a request)
 - send a batch of messages, then `waitForConfirms` to see if some might have failed. This is more use don't mind losing or resending whole batches.

For completeness, you can also send a single message then `waitForConfirms` to see if it succeeded or failed -- but you may as well supply a callback instead.

**Comment by michaelgwelch** [comment]
Got it. Thanks for the explanation.
