### ISSUE TITLE
Multiple exchange on a single queue

### ISSUE THREAD

**Issue by karlito40** [squaremo/amqp.node#410]
I'm trying to consume multiple exchange from a single queue but the callback called are wrong. I have searched into the library and found that the consumerTag return in ```handleDelivery``` is not the proper one.

Here is how i bind my exchanges.
``` javascript
var connectInstance, channelInstance;

module.exports.init = function init() {
  return amqp.connect(config.rabbitmq.url)
    .then(function(conn) {
      connectInstance = conn
      return connectInstance.createChannel();
    })
    .then(function(channel) {
      channelInstance = channel;
      return channelInstance;
    })
};

module.exports.on = function(queue, exchange, callback) {
  channelInstance.assertExchange(exchange, 'direct', { durable: true })
  return channelInstance.assertQueue(queue, { durable: true })
    .then(function(q) {
      channelInstance.bindQueue(queue, exchange, '');

      console.log('bind ', queue, exchange);
      return channelInstance.consume(q.queue, function(msg) {
        console.log('event received', queue, exchange, msg.toString());
      }, {noAck: true});
    })
}
```

and i use it like that
``` javascript
Lib.init().then(() => {
  Lib.on('my_queue', 'exchange.1', () => console.log('exchange 1 received'));
  Lib.on('my_queue', 'exchange.2', () => console.log('exchange 2 received'));
})
```

Here is what i get after publishing ```exchange.1``` countless times

> exchange 1 received
> exchange 2 received
> exchange 1 received
> exchange 2 received

I should only obtain ```exchange 1 received``` after each called.

Is that possible to bind multiple exchange on a single queue. If yes, what is wrong with my code please ?

**Comment by squaremo** [comment]
All consumers have the messages in the queue shared amongst them, and how the messages got there doesn't matter. What you are seeing is this:

 1. You create a queue and bind it to two exchanges. Sending to either exchange will result in a message in the queue.
 2. You add two consumers to the queue. Each message in the queue will go to one or other of the consumers.

If you want messages sent to exchange1 to go to one consumer, and messages sent to exchange2 to go to another consumer, you need to create two queues, bind one to exchange1, and one to exchange2, then make a consumer for each queue.

**Comment by karlito40** [comment]
Thanks you for the clarification. It helps me a lot.

**Comment by karlito40** [comment]
Yea it's good for me. I'm creating a specific queue for each exchange to do what i want.

My previous code has been changed to:
``` javascript
module.exports.on = function(onQueue, exchange, callback) {
  let queue = onQueue + '.' + exchange;
```
