### ISSUE TITLE
"Error: Frame size exceeds frame max" using amqps:// connection

### ISSUE THREAD

**Issue by QAnders** [squaremo/amqp.node#412]
I am trying to connect to Amazon (Active) MQ from a Lambda function and have a username and password and AWS MQ requires SSL.

I've tried several different variants of the connection string but I either get `Error: Frame size exceeds frame max` or `Error: unable to get local issuer certificate` depending on if I include the CA or not. The error is thrown at the connection.

I've tested using a STOMP connection and that works fine.

Does anyone have a working sample code snippet for the connection over SSL with basic auth?

Unfortunately, I can't get the Amazon MQ logs.

**Comment by rault-a** [comment]
AmazonMQ uses AMQP 1.0, this library uses AMQP 0.9.1 and there is no retro-compatibility
