### ISSUE TITLE
Channel ended, no reply will be forthcoming

### ISSUE THREAD

**Issue by palaniichukdmytro** [squaremo/amqp.node#414]
I try to delete an exchange that during the start of my service does not exist, but in case if it does not exist a channel error is raised. 
`Unhandled rejection Error: Channel ended, no reply will be forthcoming`
`Unhandled rejection Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'history-logging.Cleanup.Delayed' in vhost '/'"`

```
export const resetDelayedExchange = (connection ,expectedMessages) => async (message, type) => {

    const exchange = getExchange(type)
    const cleanupDelayedExchange = `${exchange}.${delayedExchange}`
    const channel = await connection.createChannel()

    await channel.deleteExchange(cleanupDelayedExchange, {ifUnused : false})

    channel.assertExchange(cleanupDelayedExchange, delayedExchangeType, {durable: true, arguments: {[delayedMessageType]: 'direct'}})

    await channel.bindExchange(exchange, cleanupDelayedExchange)

    logger.silly(`publishing message to ${cleanupDelayedExchange}`)

    await channel.publish(cleanupDelayedExchange, '', expectedMessages[type].encode(message).finish(), headerArg)

    await channel.assertExchange(cleanupDelayedExchange, delayedExchangeType, {durable: true, arguments: {[delayedMessageType]: 'direct'}})

    await channel.bindExchange(exchange, cleanupDelayedExchange)

    logger.silly(`publishing message to ${cleanupDelayedExchange}`)

    await channel.publish(cleanupDelayedExchange, '', expectedMessages[type].encode(message).finish(), headerArg)

}
```

**Comment by KristjanTammekivi** [comment]
Channel errors bork the channel, and according to amqp.node documentation
```If the exchange does not exist, a channel error is raised (RabbitMQ version 3.2.0 and after will not raise an error).```

**Comment by power-f-GOD** [comment]
> Channel errors bork the channel, and according to amqp.node documentation `If the exchange does not exist, a channel error is raised (RabbitMQ version 3.2.0 and after will not raise an error).`

So, please, how do I fix this, @KristjanTammekivi ? I've been unable to do anything and it blocks my work. 

Cc: @cressie176

**Comment by cressie176** [comment]
Have you tried listening for the error event and recreating the channel?
