### ISSUE TITLE
Understand clear picture of client side events and what they mean?  Or, what is the correct way to close

### ISSUE THREAD

**Issue by spr-coconnell** [squaremo/amqp.node#417]
I'm trying to capture the events that I think will get captured by my use of the client library.  For example, from what I can tell  (i.e. by using console.log(connection) or console.log(channel), the connection object will throw the following events: close, frameError, error, blocked and unblocked.  From what I can tell, the channel will throw the following events: ack, nack, delivery, cancel, close.

I'm not sure what I NEED to do with some of those.  For example, if I get a 'frameError', what does that mean?  Should I just try to close the connection and then restart a new connection?  Ditto if I get an 'error'?

I'm pretty sure that getting a 'cancel' or 'close' event on a channel is straightforward enough.  But, even so, I'm not entirely sure what the correct way to deal with things to make sure I'm not leaving resources laying around.  Does calling connection.close() automatically clean up things on the server?  What if I just create a new connection?  How long until the server cleans up resources from the first?

The documentation that I'm using here: http://www.squaremobius.net/amqp.node/channel_api.html  doesn't answer all of these questions and in a couple cases, is confusing and conflicts with what I'm seeing.  For example, the documentation says that a channel can return: close, error, return and drain events.  But, looking at an actual connection object, I see a list of different events that can have something bound to them.  Where do I go?

**Comment by spr-coconnell** [comment]
First, thank you for your reply!!!  This library came free and so any support is greatly appreciated.  Thank you.

Second, if you are willing to bear with me, I do have a couple other questions.  I'll try not to abuse your patience....

I think that when I was discussing errors, I may have mis-typed connection when I meant channel.  I'll try to be more clear :)

The documentation states that a channel can have the following events: close, error, return, and drain.

Looking at an actual channel (i.e., by just passing it into a console.log() ), I see that it can have the following events with listeners attached to them: ack, nack, delivery, and cancel

Those lists are different.  The list from the documentation implies that there are options intended for cleaning up when there are errors, when the server shuts down on me, when I cannot publish to a channel and the message gets 'returned'.  But, the actual channel object shows a much different list and I lose some of that lower level error handling.  I just wanted to confirm which list is the correct list and if what I am looking at in my console log is the wrong thing to look at.

I've looked at the amqp library and confirmed that I have version 0.5.2.

Thanks again!

**Comment by cressie176** [comment]
Probably a bit late @spr-coconnell. The only channel events I've ever used are close, error, return, and drain. Those are the ones in the documentation.
