### ISSUE TITLE
Timeout for publishing

### ISSUE THREAD

**Issue by thiagoretondar** [squaremo/amqp.node#422]
Is there a way to set a timeout when publishing something?

For example: I'm trying to publish some message (in my case with `mandatory: true` flag), but if something goes wrong with RabbitMQ (or RabbitMQ resources like queue, exchange), it takes too long to tell me that couldn't publish message.

Thanks!

**Comment by cressie176** [comment]
amqplib doesn't provide the option for setting a timeout, but it's reasonably easy to roll your own. See [here](https://github.com/cressie176/amqplib-express-example/blob/master/lib/broker.js#L60-L71) for an example.
