### ISSUE TITLE
Hooking to AmazonMQ    amqp+ssl://

### ISSUE THREAD

**Issue by relicmelex** [squaremo/amqp.node#424]
Getting an error for an unexpected protocol, which in every other case makes sense. Then AWS went and made their own. Can you please extend the type of protocols to accept "amqp+ssl"?

I'm wondering if I PR a change to lib/connect.js if you'll accept
```
  if (protocol === 'amqp:') {
    sock = require('net').connect(sockopts, onConnect);
  }
  else if (protocol === 'amqps:' || protocol === 'amqp+ssl:') {
    sock = require('tls').connect(sockopts, onConnect);
  }
  else {
    throw new Error("Expected amqp:, amqps:, or amqp+ssl: as the protocol; got " + protocol);
  }
```

I haven't forked and tested this at all yet, this was more of a 'what I want the end result to be' I'd have to dive a little deeper to be sure that's the only barrier

**Comment by squaremo** [comment]
I believe AmazonMQ implements AMQP 1.0 rather than AMQP 0-9-1 -- which are, counter-intuitively, not at all compatible. This library will only work with AMQP 0-9-1.

**Comment by relicmelex** [comment]
So yeah, I ran across that just a little earlier but coming back to this just confirms exactly that. Thank you so much for even responding to a closed ticket...
