### ISSUE TITLE
Nodejs receiver stopped receiving new messages

### ISSUE THREAD

**Issue by s888** [squaremo/amqp.node#430]
Hi,
I have a node application that receives messages from  multiple queues.
Suddenly it stopped receiving messages from one of the queues.
The sender was able to send messages to that queue.
The app was able to receive messages from other queues.
There is no error in the rabbitmq log file.
The issue got fixed after I restarted the app.
What can be the probable cause?

**Comment by Stradivario** [comment]
This is insane explanation really!

You cannot do anything! You need to create Tests and if your tests are up and running and you comply more than 70% of your website features you are all right ! :) 

But anyway please don't write post like that without any information.

Regards,
Kristiyan Tachev

**Comment by cressie176** [comment]
Hi @s888,

Thanks for posting. I'll do my best to help. There are a few things it might be, for example 

1. If the consumer has a prefetch limit and is set to explicitly ack/nack, but for some reason isn't always acknowledging messages, when it hits the limit no more messages will be read.

1. If the consumer is listening but not sensibly handling errors, the channel or connection could be closed.

The easiest way to diagnose both is by checking the RabbitMQ admin UI and seeing whether the queue has unacknowledged messages (in which case it's likely to be 1) or no consumers (in which case it's likely to be 2)

Yet another alternative is that your applications event loop is being flooded but given messages from other queues are being processed correctly, I doubt it's this.

**Comment by s888** [comment]
@cressie176 , Thanks for the reply.
Yes I did check the queue from the admin UI and the Unacked message count is 0. 
I thinks its point 2. The channel got closed. But there is no information logged into the rabbitmq logfile.
There are "Possible EventEmitter memory leak detected" errors in the code so I guess that might be the reason.

**Comment by s888** [comment]
@Stradivario FYI This is happening on a fully tested code that is up and running on live server since several months.
But since there was no error messages in the rabbitmq log I have posted this question here. So that I could get some more info on this.

**Comment by cressie176** [comment]
@s888 does the queue have consumers?

Look for any error handling code which could be swallowing a channel or connection error. It could be a genuine error is being emitted from the connection / channel (e.g. due to a network timeout). If these errors get handled without reinitialising the subscriber you will stop receiving messages.

Another cause could be a bug in the subscriber code that's throwing an error. If not handled in the subscriber code it could bubble up to the channel and cause it to break.

**Comment by cressie176** [comment]
@s888 did you get to the bottom of this?

**Comment by cressie176** [comment]
Closing. Happy to reopen if not resolved

**Comment by s888** [comment]
The channel was getting closed due to some unknown reasons.
So in the on error event I re-initiated the connection.
