### ISSUE TITLE
How do I set queue's overflow behavior?

### ISSUE THREAD

**Issue by honestserpent** [squaremo/amqp.node#435]
I want RabbitMQ to nack sent messages that arrive after the maximum queue's length has been reached. By default, RabbitMQ will drop older messages when a new message arrives and the limit has been reached.

Following the [docs](https://www.rabbitmq.com/maxlength.html#overflow-behaviour), I should set an `overflow` option to  `reject-publish` in order to discard most recent messages, but it looks like the `amqp.node` does not provide this option.

Any clues?

**Comment by mistermoe** [comment]
@honestserpent amqplib's assertQueue [documentation](http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue) states that:

>RabbitMQ extensions can also be supplied as options. These typically require non-standard x-* keys and values, sent in the arguments table; e.g., 'x-expires'. When supplied in options, the x- prefix for the key is removed; e.g., 'expires'. Values supplied in options will overwrite any analogous field you put in options.arguments`

This makes it seem as if you have two options:
```js
// Option 1:
ch.assertQueue('some-queue-name', { 'overflow': 'reject-publish' });

// Option 2:
ch.assertQueue('some-queue-name', {
    arguments: { 'x-overflow': 'reject-publish' }
});
```

Hopefully this helps.
