### ISSUE TITLE
sendQueue does not raise error if queue doesn't exist?

### ISSUE THREAD

**Issue by officer-rosmarino** [squaremo/amqp.node#440]
I do not understand if I am doing something wrong or not. I have a durable confirm channel and one queue named `tasks`. It looks like if I use another name, the `sendToQueue` does not report anything.

Is this the correct and expected behavior?

`await confirmChannel.sendToQueue('nonExistingQueue', Buffer.from('message'), {persistent: true})`

**Comment by squaremo** [comment]
Yes, this behaviour is defined of the protocol -- sending is asynchronous, and you don't always get to find out the fate of a message.

You can mark a message as `mandatory`, in which case it will be returned if it cannot be routed. In amqplib returns are an event on the channel named `'return'`: http://www.squaremobius.net/amqp.node/channel_api.html#channel_events

**Comment by ma-zxteam-org** [comment]
I have a similar question...
When I call promisable implementation:
   `await channel.sendToQueue(...)`
I expect two results when the Promise completed:
1) The message successfully delivered into target Rabbit Queue (in case Promise.resolve)
2) The message was not delivered (in case Promise.reject)

Nothing else. 
Users of the library should not know anything about underlaying protocols (and protocol behaviors).
This just my opinion.
