### ISSUE TITLE
Unexpected behavior in channel.consume for Non Existing Queue

### ISSUE THREAD

**Issue by theanurin** [squaremo/amqp.node#443]
Hi,

I use promisable approach of the amqplib.
Expected:
I expect to receive "Cannot consume due error" in the output.
Actual:
<img width="926" alt="screen shot 2018-07-18 at 13 03 49" src="https://user-images.githubusercontent.com/22301243/42875069-644be7e0-8a8b-11e8-993f-e685b8781f0b.png">

My code is
```
// index.js
// Using node: v8.11.2
const amqplib = require("amqplib"); // version: 0.5.2

async function main() {
	console.log("Opening a connection");
	const connection = await amqplib.connect("amqp://localhost");
	try {
		console.log("Opening a channel");
		const channel = await connection.createChannel();
		try {
			console.log("Do consume NonExistingQueue");
			try {
				const serverReply = await channel.consume("NonExistingQueue", (msg) => { console.log("/*do nothing*/"); }, { noAck: true });
			} catch (consumeErrorReason) {
				// Expected behavior
				console.error("Cannot consume due error");
			}
		}
		finally {
			if (channel) {
				// Expected behavior
				console.log("Closing the channel");
				try { await channel.close(); } catch(e) { /*ignore*/ }
			}
		}
	}
	finally {
		if (connection) {
			// Expected behavior
			console.log("Closing the connection");
			try { await connection.close(); } catch(e) { /*ignore*/ }
		}
	}
}

main();
```

**Comment by squaremo** [comment]
Yep, the AMQP authors decided that if you get anything like naming a queue wrong, it should invalidate the channel.
What you'll need to do is register an `'error'` handler with the channel, and open another channel. https://squaremo.github.io/amqp.node/channel_api.html#failure

**Comment by cressie176** [comment]
@theanurin need any more help with this issue?

**Comment by cressie176** [comment]
Closing. Happy to reopen if not resolved
