### ISSUE TITLE
bindQueue generate two bindings

### ISSUE THREAD

**Issue by tnargib** [squaremo/amqp.node#444]
I'm using the exact same code as the pub/sub example here: https://www.rabbitmq.com/tutorials/tutorial-three-javascript.html

When I run one consumer and one producer, I list bindings using `rabbitmqctl list_bindings`. Instead of just getting one binding, It displays two.

```
	exchange	amq.gen-tts3TAUY6NOmos_08kmOQw	queue	amq.gen-tts3TAUY6NOmos_08kmOQw	[]
logs	exchange	amq.gen-tts3TAUY6NOmos_08kmOQw	queue		[]
```

Is this an intended behaviour or am I missing something ?

Just in case here are my source files:

> logProducer.js
```
#!/usr/bin/env node

var amqp = require("amqplib/callback_api");

amqp.connect(
  "amqp://localhost",
  function(err, conn) {
    conn.createChannel(function(err, ch) {
      var ex = "logs";
      var msg = process.argv.slice(2).join(" ") || "Hello World!";

      ch.assertExchange(ex, "fanout", { durable: false });
      ch.publish(ex, "", new Buffer(msg));
      console.log(" [x] Sent %s", msg);
    });

    setTimeout(function() {
      conn.close();
      process.exit(0);
    }, 500);
  },
);
```

> logConsumer.js
```
#!/usr/bin/env node

var amqp = require("amqplib/callback_api");

amqp.connect(
  "amqp://localhost",
  function(err, conn) {
    conn.createChannel(function(err, ch) {
      var ex = "logs";

      ch.assertExchange(ex, "fanout", { durable: false });

      ch.assertQueue("", { exclusive: true }, function(err, q) {
        console.log(
          " [*] Waiting for messages in %s. To exit press CTRL+C",
          q.queue,
        );
        ch.bindQueue(q.queue, ex, "");

        ch.consume(
          q.queue,
          function(msg) {
            console.log(" [x] %s", msg.content.toString());
          },
          { noAck: true },
        );
      });
    });
  },
);
```

**Comment by squaremo** [comment]
The first binding is created by RabbitMQ so you can send directly to the queue. See https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default

**Comment by tnargib** [comment]
Still seeing this issue as open. How rude it tooks me so long to respond !Thanks for your help.
As I understand those bindings are more like "system things" that can be ignored in many use case. I was afraid at first that this would cause some performance issue but I guess not then.
