### ISSUE TITLE
Channel.Consume(...). Multiple callbacks for single ConsumerTag

### ISSUE THREAD

**Issue by PabloDeCortes** [squaremo/amqp.node#450]
Hi! There is implementation for channel.Consume(...) in C#:
[AsyncEventingBasicConsumer](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/0ffd443eb1a3de7de8db58ece20b26e379355a73/projects/client/RabbitMQ.Client/src/client/events/AsyncEventingBasicConsumer.cs)
As you can see, you can add as many callbacks for single ConsumerTag in C#, but implementation in NodeJS allow you to add only one callback for ConsumerTag. That behavior leads to misunderstanding between developers on different platforms. Please, arrange about one expected behavior.

Best regards.

**Comment by squaremo** [comment]
It's idiomatic in C# to use C#'s special-purpose event machinery. JavaScript doesn't have this machinery, so has different norms. I don't think it's helpful to give JavaScript users a client that behaves idiomatically like C#.

There is a structure that's a bit like C#'s event handlers, in Node.JS -- `EventEmitter`. It'd be possible to have an `EventEmitter` value representing the consumer, and register handlers with it. But I'm not sure it would add much. How often do you want to trigger more than one callback from a consumer?
