### ISSUE TITLE
Disconnection error

### ISSUE THREAD

**Issue by tasoss** [squaremo/amqp.node#456]
Hello!
I'm using [this EasyNetQ implementation for node](https://github.com/sfrooster/EasyNodeQ).
Until now i was developing on the same machine that rabbitmq server was running.
Now that i had to deploy the app to other computers too i'm having issues with sockets(disconnections).
I mainly get

> Uncaught Error: Unexpected close
>FROM
>ChannelModel.emit (events.js:1:1)
>emitOne (events.js:1:1)
>Connection.emit (events.js:1:1)
>Connection.C.onSocketError 
> (/home/xxxx/node_modules/amqplib/lib/connection.js:1:1)
>emitNone (events.js:1:1)
>Socket.emit (events.js:1:1)
>endReadableNT (_stream_readable.js:1:1)
>process._tickCallback (internal/process/next_tick.js:139:11)

After a simple search i have found for example [this](https://github.com/squaremo/amqp.node/pull/411)
and other issues talking about disconnection issues etc.
As fas as i can understand there is no solution right now to this problem.
Is there any way to try to correct this problem, either by configuring rabbitmq or this project or something else?Any alternative?
My rabbitmq server and clients are on a lan with 1Gbps connection between them and i can't understand why i'm having such socket errors.
Thanks!

**Comment by cressie176** [comment]
Hi @tasoss,

There are a few things I suggest...

1. Check what network infrastructure might be causing problems. In the passed I've had issues with VPNs which drop connections that have little activity.

1. Tune your heartbeat settings

1. I notice that [https://github.com/sfrooster/EasyNodeQ](EasyNodeQ) is on quite an [old version](https://github.com/sfrooster/EasyNodeQ/blob/master/package.json#L20) of amqplib. I suggest running a little experiment with a simple amqplib client to see if that reduces the problems

1. amqplib doesn't provide connection recovery, but there are some external libraries that do. E.g. [amqp-connection-manager](https://www.npmjs.com/package/amqp-connection-manager) and [rascal](https://www.npmjs.com/package/rascal)

**Comment by tasoss** [comment]
Hello and thanks for replying!
I will try your suggestions.
Thanks again!
