### ISSUE TITLE
How can a consumer know it's been cancelled?

### ISSUE THREAD

**Issue by MartinWickman** [squaremo/amqp.node#461]
I'm trying to gracefully shutdown my app.  If I just close the connection/channel, any pending consumer won't have a chance to ack the current message (if any) and will throw an exception because the connection is gone.

So I'm thinking shutdown should (1) should "cancel" each consumer channel and (2) wait for all consumers to handle whatever message they are currently processing and then (3) close the connection.

But is there any smart way to know when a consumer is done? Can a consumer know this somehow? Or do I have to roll this myself?

This is with `channel.consume(q, callback)` btw.

If figured using `if (msg == null)`, but that's only triggered trough the server.

**Comment by cressie176** [comment]
Hi @MartinWickman,

When you think about it this is a general problem which can affect things like http request and timer tasks too. In general the approach is

1. Keep a count of the outstanding tasks
1. On shutdown request, stop new tasks arriving (e.g. by cancelling the subscriber)
1. Wait until outstanding tasks reaches zero (or a timeout has occurred)
1. Proceed with shutdown

At the risk of plugging my own libraries I use https://www.npmjs.com/package/outstanding and https://www.npmjs.com/package/systemic to orchestrate graceful shutdown of node applications.
