### ISSUE TITLE
When will it be deployed that amqplain update

### ISSUE THREAD

**Issue by windofwind** [squaremo/amqp.node#466]
I need amqplain update.
0.5.3 release please.

**Comment by cressie176** [comment]
@squaremo how about using this to walk me through the release process?

**Comment by squaremo** [comment]
@windofwind We are on it. I'm interested to know why you need AMQPLAIN -- surely any server that accepts AMQPLAIN also accepts PLAIN?

**Comment by windofwind** [comment]
https://www.rabbitmq.com/authentication.html

service provider may only support amqplain.

**Comment by cressie176** [comment]
Hi @windofwind we release 0.5.3 today. Please advise if this resolves your problem.

**Comment by windofwind** [comment]
thx!!! i'm checking

**Comment by windofwind** [comment]
so greate! thank you so much!
