### ISSUE TITLE
Providing array of hosts to hostname throws confusing error

### ISSUE THREAD

**Issue by reetou** [squaremo/amqp.node#474]
Node version: 8.11.4
OS alpine
In our production we receive array of hosts and amqp.node threw this:
```JavaScript
../src/tcp_wrap.cc:286:static void node::TCPWrap::Connect(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
```
I think it should parse first element of array or at least be more clear
If you don't mind, I would like to make a PR for this.

**Comment by reetou** [comment]
@cressie176 sure
If I provide an array like below, it throws. On my computer it was just throwing that hostname must be a string, but on production it was confusing like above.
```JavaScript

module.exports = {
	rabbit: null,

	init() {
		return new Promise(async (resolve, reject) => {
			try {

				const rabbit = await amqp.connect({ hostname: [ '5.10.15.20'], username: 'username', password: 'password' })
				console.log('Rabbit connected')
				this.rabbit = await rabbit.createChannel()
				this.rabbit.assertExchange('exchange')
				console.log('Created exchange exchange')

				this.rabbit.on('error', (e) => {
					console.log('Error in rabbit')
					console.log(e)
				})
				console.log('Rabbit done')
				resolve()

 			} catch (e) {
				console.log(`Rabbit err`, e)
			}
		})
	},

}
```

**Comment by cressie176** [comment]
I also get the same error with alpine, but not locally, so I suspect there's a difference in the underlying c libraries causing the unfriendly error. 

Thanks for offering the PR. I don't think it's a good idea change the connect function to support arrays as you suggest. It could lead to developers assuming some kind of advanced connection management and being surprised when only the first node received connections.

Have you considered using [amqp-connection-manager](https://github.com/benbria/node-amqp-connection-manager)?

**Comment by reetou** [comment]
Thanks, I will look at it.
