### ISSUE TITLE
Amazon MQ

### ISSUE THREAD

**Issue by amirsaber** [squaremo/amqp.node#486]
I am trying to use this library to connect to an Amazon MQ instance. Amazon provides amqp with `amqp+ssl://[amazon url]:5671`. If I try Amazon MQ URL with this library it throws
```
(node:7990) UnhandledPromiseRejectionWarning: Error: Expected amqp: or amqps: asthe protocol; got amqp+ssl:
    at connect (/[project address]/node_modules/amqplib/lib/connect.js:165:11)
    at Object.connect (/[project address]/node_modules/amqplib/callback_api.js:14:3)
```
can someone help with this?

**Comment by cressie176** [comment]
I think Amazon MQ uses amqp 1.0, which is Incompatible with amqp 0.9.1 used by RabbitMQ and this library. Worth reading http://www.imatix.com/articles:whats-wrong-with-amqp/ for a bit more context

**Comment by sreedharbukya** [comment]
@cressie176 , any idea which library is compatible with amazonMQ which works with AMQP protocol?

**Comment by L-U-C-K-Y** [comment]
Hey all

I am also trying to use AmazonMQ with RabbitMQ 3.9.13 that should support 0.9.1, but I am facing issues using it, was anyone successful?

The error that I receive is:
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/14868134/160243449-599ba55e-4a50-4f56-aaaf-52b8604fc07e.png">

**Comment by carlhoerberg** [comment]
Your headers are too large. Increase frame_max on the client side
