### ISSUE TITLE
Run `npm i amqplib` return 404 Not Found: event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz

### ISSUE THREAD

**Issue by WendySanarwanto** [squaremo/amqp.node#487]
### Replication steps

* Change directory into a Node.js project.
* On the CLI terminal, run `npm i amqplib --save`
* Expected: The installation command is finished successfully
  Actual: The installation is failing and showing error message `404 Not Found: event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz`

![image](https://user-images.githubusercontent.com/18456618/51102626-aa7c4d00-181a-11e9-9f93-d0828bf99c3d.png)

### Environment

* OS: Windows 10 
* Node.js version: 8.9.4
* NPM's version:  5.6.0

**Comment by cressie176** [comment]
Hi @WendySanarwanto 

I don't think this is a problem with amqplib. It appears you have lots of other modules missing, and I don't think event-stream is a dependency of amqplib. It isn't shown if I run npm ls

```
npm ls
$
└─┬ amqplib@0.5.3
  ├─┬ bitsyntax@0.1.0
  │ ├── buffer-more-ints@1.0.0 deduped
  │ ├─┬ debug@2.6.9
  │ │ └── ms@2.0.0
  │ └── safe-buffer@5.1.2 deduped
  ├── bluebird@3.5.3
  ├── buffer-more-ints@1.0.0
  ├─┬ readable-stream@1.1.14
  │ ├── core-util-is@1.0.2
  │ ├── inherits@2.0.3
  │ ├── isarray@0.0.1
  │ └── string_decoder@0.10.31
  ├── safe-buffer@5.1.2
  └─┬ url-parse@1.4.4
    ├── querystringify@2.1.0
    └── requires-port@1.0.0
```

Other possible causes are

* A flakey network
* Network security software / proxy config
* A private npm registry
* Previous bad installs
* A bad npm cache

I would

1. Fix the babel-eslint dev / production dependency
1. Remove the node_modules directory and package-lock.json for this project
1. Run `npm cache --clean --force`
1. Run `npm install` (you shouldn't need --save in recent versions)

If you still have problems I would assume it's an issue with your environment (PC or Network). I don't think it's a problem with amqplib. I just did a clean install, and everything worked fine for me locally.

**Comment by WendySanarwanto** [comment]
Hello Again ,

This error happened due to older version of `grunt-nodemon` in my project has a reference to older version of `nodemon` which triggered this error. Since this error is not related to `amqlib` , I am going to close this issue.
