### ISSUE TITLE
Support for Node v10.x.x ? 

### ISSUE THREAD

**Issue by yadomi** [squaremo/amqp.node#489]
When will amqp support node v10.x.x ?

```js
  "engines": {
    "node": ">=0.8 <=9"
  },
```

**Comment by kibertoad** [comment]
Glad you asked!
https://github.com/squaremo/amqp.node/pull/463

**Comment by cressie176** [comment]
@squaremo with your fix for Node 10 I think this can be extended to `<= 11`?

**Comment by squaremo** [comment]
Ahhhh, yep -- we are testing (and passing) through to v11 https://github.com/squaremo/amqp.node/blob/master/.travis.yml, so we can reasonably claim to support it. Sorry for not keeping up!

**Comment by peterjwest** [comment]
Could you also extend to node 12 now?

**Comment by cressie176** [comment]
The current version supports >=0.8 <=12
