### ISSUE TITLE
Is there any way for me to grab only one item from the list every X seconds?

### ISSUE THREAD

**Issue by gabrielgrs** [squaremo/amqp.node#490]
Is there any way for me to grab only one item from the list every X seconds?

I tried to use get and prefetch(1), but I need to set a time between get each message, how can I do this?

thanks

**Comment by squaremo** [comment]
Two approaches:

 - use get and a timer. Sometimes there won't be a message to be got, and you'll have to wait for the next attempt. (i.e., this is "maybe get a message, every X seconds")

 - use a consumer, and prefetch(1), and only acknowledge the message after a timer (this is "get a message at most every X seconds")
