### ISSUE TITLE
Any way for channel.consume to use async callback correctly?

### ISSUE THREAD

**Issue by Josh68** [squaremo/amqp.node#495]
I have a very simple setup using a Confirmation Channel with a few queues whose messages involve handlers that run queries/mutations on a Mongo DB. I've written my handlers as `async` functions, but I think this isn't really supported, based on what I'm seeing in the docs.

E.g., 
```
// Define channel up here
const processMessage = async message => {
  try {
     const response = await db.doStuff(message);
     channel.ack(message);
  } catch(error) {
     // handle errors
  }
};
const ready = await channel.consume(queueAssertion.queue, processMessage, {
   noAck: false
});
```

This actually seems to be working, but I'm not sure it really is, or if the `ack`s are completely out of sync with the message stream.

Is there any way to actually do something like this? Is this possibly valid, and I'm just paranoid? Thanks.

**Comment by squaremo** [comment]
I don't see any reason why that wouldn't work; you have the equivalent (ignoring the try...catch detail) of

```
const processMessage = message => {
  return db.doStuff(message).then(response => channel.ack(message));
};
```

You're not obliged to do anything with the Promise return value from an async function.

**Comment by Josh68** [comment]
Thanks, @squaremo. Yeah, the catch is basically where I `nack` (without requeuing- again, this is a very basic setup, and does not attempt to be particularly smart about that, at least at the moment).

The reason I ask is confusion about what I [read here]( https://github.com/squaremo/amqp.node/blob/master/lib/channel_model.js#L167) (linked in another issue about an async callback). While my actual code (close to this pseudocode) actually seems to be working, I wasn't sure whether I was doing anything off the ranch in terms of trying to handle and `ack` asynchronously if the `consume` method expects its callback to be synchronous.

**Comment by Josh68** [comment]
@squaremo, if you have anything else to add to my last comment, please do, otherwise you can or I will close this issue. And thanks again 👍
