### ISSUE TITLE
Enable to resolve stream ./node_modules/amqplib/lib/connection.js

### ISSUE THREAD

**Issue by swapnilanar** [squaremo/amqp.node#496]
I am using angular 6 and installed amqplib but I am getting following errors. 
![amqplib](https://user-images.githubusercontent.com/33443033/54199525-24654580-44ef-11e9-89a6-ce5db4220446.PNG)

**Comment by squaremo** [comment]
amqplib depends on the Node.JS standard library.

**Comment by swapnilanar** [comment]
> amqplib depends on the Node.JS standard library.

Yes Thanks, Is there any prerequisite to use this in angular 6 or later version. I am not sure what am I missing.

**Comment by cressie176** [comment]
I suspect what's happening is that angular is a client side library designed to be run in a web browser. amqplib is a server side library designed to be run in Node.JS. While both support environments support JavaScript there are differences such as file system access, and by the looks of it streams.

**Comment by cressie176** [comment]
Any objection to closing this @swapnilanar ?

**Comment by swapnilanar** [comment]
> Any objection to closing this @swapnilanar ?

Nope, thanks for the input, it helped :)
