### ISSUE TITLE
Error on queue delete

### ISSUE THREAD

**Issue by mglowinski** [squaremo/amqp.node#497]
When I am trying to delete queue by name, I have got the following error:
[AMQP] conn error Cannot read property 'content' of null
[AMQP] channel closed
[AMQP] reconnecting
Am I doing something wrong?

**Comment by squaremo** [comment]
It's difficult to tell without seeing any code. Can you provide a failing test case?

**Comment by cressie176** [comment]
Just a guess, but when the server closes a channel it sends a null messages to any subscribers. Is it possible you are subscribing to messages, and when the channel is closed you aren't checking that hte message you've received is null?

**Comment by cressie176** [comment]
Any update @mglowinski ?
