### ISSUE TITLE
the confirmChannel cannot confirm the message was delivered

### ISSUE THREAD

**Issue by yqsailor** [squaremo/amqp.node#499]
I use the confirmChannel to publish the message to the exchange, but how to confirm it was delivered successfully? my code is below:

```
var open = require('amqplib').connect();
open.then(function(c) {
  c.createConfirmChannel().then(function(ch) {
    ch.publish('text-exchange', '', new Buffer('foobar'), { persistent: true, durable: true, mandatory: true, immediate:true },
      function(err, ok) {
        if (err !== null)
          console.warn('Message send failed!');
        else
          console.log('Message send successfully');
    });
  });
});
```

Even if exchange does not exist or the queue that binding the exchange does not exist,  the result is always `Message send successfully`

**Comment by cressie176** [comment]
Here's what I get when I run your code sample...

```
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Channel closed by server: 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'text-exchange' in vhost '/'"
    at ConfirmChannel.C.accept (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/channel.js:416:17)
    at Connection.mainAccept [as accept] (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:478:48)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```
So I suspect the exchange does exist in your environment. I also suggest not using immediate. From the amqplib [documentation](https://www.squaremobius.net/amqp.node/channel_api.html)

> immediate (boolean): in the specification, this instructs the server to return the message if it is not able to be sent immediately to a consumer. No longer implemented in RabbitMQ, and if true, will provoke a channel error, so it’s best to leave it out.

However you are right that if there is no queue bound to the exchange the callback will be executed without an error. What you are looking for in this case is the channel 'return' event. Use this event probably won't do quite what you expect, so I suggest reading the documentation carefully, and also the several other issues discussing publisher confirms.

**Comment by cressie176** [comment]
Any update @yqsailor ?

**Comment by junnyea** [comment]
You could probably missing the ch.waitForConfirms() in the confirmChannel

**Comment by cressie176** [comment]
Hi @junnyea, my understanding is you only need waitForConfirms if you're publishing multiple messages and not using the callback. See https://github.com/squaremo/amqp.node/issues/375
