### ISSUE TITLE
Promise returns unknown consumerTag 

### ISSUE THREAD

**Issue by yusufilkeroguz** [squaremo/amqp.node#500]
Hi,

In my code when i use "await" behind amqp functions, get fatal error.

Can u help me?

NodeJS: 8.15.0
Mac: 10.14.3
Amqplib: 0.5.3
RabbitMQ: 3.7.12

```javascript
const open = require('amqplib').connect('amqp://localhost');

(async () => {
  const q = 'tasks';

  // WORKING

  open.then(function(conn) {
    return conn.createChannel();
  }).then(function(ch) {
    return ch.assertQueue(q).then(function(ok) {
      return ch.consume(q, function(msg) {
        if (msg !== null) {
          console.log(msg.content.toString());
          ch.ack(msg);
        }
      });
    });
  }).catch(console.warn);
  
  /**
  * RETURN ERROR
  * events.js: throw er; // Unhandled 'error' event
  * Error: Unknown consumer: amq.ctag-5twJxFMb7rHIIT4YfedzIA
  */
  const connection = await open;
  const channel = await connection.createChannel()
  const queue = await channel.assertQueue(q)

  const msg = await channel.consume(q)
      if (msg !== null) {
          console.log(msg.content.toString())
          channel.ack(msg)
      }
})()
```

**Comment by cressie176** [comment]
Hi @yusufilkeroguz,

I didn't run your code but my guess would be that it's this line
```
const msg = await channel.consume(q)
``` 
Consume doesn't resolve to a message (there could be many on the queue), instead it still requires a function as the second argument. See the [channel api](https://www.squaremobius.net/amqp.node/channel_api.html#channel_consume) documentation.

I suspect if you change your code to the following it will start working
```
await channel.consume(q, function(msg) {
  if (msg !== null) {
    console.log(msg.content.toString());
    ch.ack(msg);
  }
})
```

**Comment by yusufilkeroguz** [comment]
@cressie176, Thanks for quick response. You are right. Its worked when change.
Thanks for help.
Closing issue.

**Comment by Telokis** [comment]
@cressie176 This helped me as well so thank you.
I noticed it's not a good idea to make this function async. Is there a way to make it not synchronous?
I have a pattern like the following (notice the enclosing infinite loop):

```js
while (true) {
    log("Waiting for message to consume...");

    await channel.consume(
        groupId,
        async message => {

            if (message.content) {
                const data = JSON.parse(message.content.toString());
                await heavyProcessing(data);
            } else {
                log("Message's content was undefined. Ignoring it.");
            }

            channel.ack(message);
        },
        { noAck: false },
    );
}
```

With the message handler async, I notice the message `"Waiting for message to consume..."` to constantly be printed again even in the middle of the logs from my `heavyProcessing` function.
It seems to mean that `consume` doesn't wait for my promise to resolve before returning.
Is there a way to force it to do so?

**Comment by cressie176** [comment]
Hi @Telokis,

I suspect you've misunderstood async messaging patterns a little.

Why put `channel.consume` in a loop? It's something that only needs to happen once, unless the connection drops or there's a channel error (which you should handle by responding to error events). After consuming the callback will be executed every time a message is published to the queue. Unless you enable explicit acknowledgements and specify a prefetch this could mean your application receives 1000s of messages concurrently, which could blow your event loop or memory.

**Comment by Telokis** [comment]
Thank you very much for the detailed explanation, it's very useful.
My whole consumer is inside a worker thread spawned and managed by my main application so I'm not really afraid of it dying unexpectedly, it will be respawned.

Moreover, the jobs themselves are not "critical" at all. Each job is there to assert N entities exist in db and creating up to N if there is not enough. Meaning that two consecutive jobs will likely result in the second being a noop.

Anyway, I'll try to take your advice into account.

`channel.consume` is like a way to register a handling function, isn't it?
I could remove my loop and the handler would still be called for each message even though `consume` is only called once?

**Comment by cressie176** [comment]
> channel.consume is like a way to register a handling function, isn't it?
I could remove my loop and the handler would still be called for each message even though consume is only called once?

Correct

> My whole consumer is inside a worker thread spawned and managed by my main application so I'm not really afraid of it dying unexpectedly, it will be respawned.

That's certainly one of the things to be concerned about. Having a process crash and respawn 1000 times a second because of a corrupt message can play havoc with your infrastructure.
