### ISSUE TITLE
Allow connection to survive channel-killing errors

### ISSUE THREAD

**Issue by djmitche** [squaremo/amqp.node#501]
AMQP defines lots of errors (such as `checkExchange('nonexistent-exchange')`) to invalidate the channel.  That's kind of annoying, but creating a channel on an existing connection is fairly cheap, so it's not awful.  However, amqplib seems to elevate all channel errors to connection errors:
https://github.com/squaremo/amqp.node/blob/c28c176dd74565c73957eebf00932a892d2aa840/lib/channel.js#L406-L408

This is quite a bit worse, as it means that multiple users of the same connection become tightly tied together.

My use case is a service that can be configured to listen to arbitrary topic exchanges and react to messages on those exchanges.  Due to this limitation of amqplib, each listener needs its own connection so that, if the user gives an invalid exchange, it only kills that listener and not those of other users.

**Comment by djmitche** [comment]
I suspect this could be implemented by recording for each rpc whether a failure kills only the channel or the whole connection (based on what the AMQP-0-9-1 spec says), and then behave differently in `C.accept` based on that information.

**Comment by cressie176** [comment]
@djmitche I could be mistaken but if you listen to the channel error event, won't that prevent the connection being closed?

**Comment by djmitche** [comment]
I will check that out.

**Comment by djmitche** [comment]
Indeed, that is the case. That's definitely not clear from the docs!

**Comment by djmitche** [comment]
So it seems like the right way to handle channel errors locally is this:

```js
channel = await conn.createChannel();
channel.on('error', () => {}); // stop propagation of errors to kill connections
try {
  await channel.someOperation();
} catch (err) {
  // recover from the error, including invalidating the channel
}
```

**Comment by cressie176** [comment]
Hi @djmitche, there is no one "right" way it depends on your use case, and often on how you are publishing and subscribing.

One thing to note though, once a channel has emitted an error, you won't be able to use it again (see the Dealing with failure section of the [channel api](https://www.squaremobius.net/amqp.node/channel_api.html))

The implications of this are you that you will have to re-create the channel when publishing, and recreate + resubscribel when consuming. Both can be tricky depending on the design of your application (e.g. if you've stored multiple references to the channel)

**Comment by djmitche** [comment]
Yeah, that part is documented. That the API both emits errors and throws/rejects is definitely a weird API, and poorly documented (with no documentation of this curious "bubbling up to the connection" behavior).

**Comment by cressie176** [comment]
Not entirely. A connection error / channel error can happen at any time. You couldn't use reject under these circumstances. However I'd much rather have a promise rejection / callback error in response to a failed publish than have to listen for an event.

**Comment by squaremo** [comment]
> That the API both emits errors and throws/rejects is definitely a weird API

What would you rather it did?

**Comment by djmitche** [comment]
I don't necessarily think this is a change the library should make.  I was making the point that it's pretty unusual and certainly deserves some specific documentation.

To your question: I'd rather see errors thrown from methods, either when that method caused an error (e.g., no such exchange) or when there is an issue with the channel or connection discovered when that method is invoked (channel closed, connection failed, etc.).  For cases where there is an active consumer, i'd like to see the consumer callback take `(message, error)` with `error` used to indicate errors (including server closing the consumer - `message == null` in that case is clearly documented, but unusual).

For cases where a process publishing messages wants advance warning of a connection failure so it can proactively reconnect, it would make sense for the connection object to emit an event in case of keepalive failure.  This would just be a "hint" that the connection is bad, and thus shouldn't be an `error` event (which has special meaning to Node) but maybe `keepalive-failure`.  Processes that ignore this message will just get an error on the next `publish` call and can reconnect and retry that call if desired.

**Comment by squaremo** [comment]
Thanks for the thoughtful response @djmitche, it's helpful to have your point of view.

**Comment by djmitche** [comment]
I can try to make a docs PR.

**Comment by squaremo** [comment]
To be clear about the error propagation: it is not intended that if you fail to handle an error on a channel, it causes an error in the connection. That's either because unhandled errors will bring down the runtime (and that ends up also causing an error on the connection); or there's simply a bug.

There will always be the need for _some_ error or error-like event coming from the channel, since the server can close a channel arbitrarily. Perhaps just `'close'`, with or without an error argument, would suffice.

It was not clear to me when I initially wrote amqplib that _just_ rejecting promises was adequate -- it seemed there were two effects, the outstanding RPC operation (and any attempted after it) being failed, and the channel being invalidated. If the latter were not signalled, the documentation and so on would need to try to teach people that a failed operation means the channel is defunct -- I'm sure there would be people lodging issues, having not picked that up :-S

Anyway, I'm not arguing that the incumbent design is perfect, just filling in some background.

**Comment by morigs** [comment]
I think this behaviour must be documented
