### ISSUE TITLE
Cluster Mode - AMQP

### ISSUE THREAD

**Issue by ayyappaappana** [squaremo/amqp.node#502]
I m trying to connecting with AMQP cluster mode as below format. Can any one guide me does it supports or not, if it supports what is my mistake.
```
amqp.connect(['amqp://localhost:4369','amqp://localhost:4367'], function (err, conn) {
    conn.createChannel(function (err, ch) {
        ch.assertExchange(ex, 'direct', {
            durable: false
        });
        channel = ch;
    });
});
```

**Comment by cressie176** [comment]
Hi @ayyappaappana,

Connect doesn't take an array. If you want specify multiple hosts for resilience take a look at something like [connection manager](https://www.npmjs.com/package/amqp-connection-manager)

It's also worth reading the amqplib channel api documentation. It provides detail on the [connect]((https://www.squaremobius.net/amqp.node/channel_api.html#connect) function and other functions you will be using.
