### ISSUE TITLE
Queue always return 2 message at same time with same deliveryTag

### ISSUE THREAD

**Issue by TechGuyVN** [squaremo/amqp.node#504]
i use rabbitMQ and my need is get random number of message in queue.

But when run  the code unfortunately prefetch & Qos setting isn't work.
2 message come to comsume at one time with the same diliveryTag.
So i can't get number of message like i expected.

here my code:

 

```
    exports.getMessageFromQueue = async  function(queue,numbMessage) {
                var exchange = queue + '.exchange';
                var result = [];
                var countReceive = 0;
                var isDone = false;
    
           
                
              let channel = await conn.createChannel()
              let response = await channel.assertQueue(queue)
              await channel.prefetch(1);
              await channel.qos(1); 
    
              response = await channel.bindQueue(response.queue, exchange, '');
             
    
              channel.consume(response.queue,getMessage(numbMessage), {noAck: false})
    
              setTimeout(() => {
                eventEmitter.emit('consumeDone');
              if(channel != null)channel.close();}, timeout)
    
              await new Promise(resolve => eventEmitter.once('consumeDone', ()=>{
                console.log("done event");
                resolve()
              }));
              console.log("return");
              return result;
            //   console.log('reading for query finish')
    
              function getMessage(messageCount) {
                return msg => {
                    var content = msg.content.toString();
                    var secs = content.split('.').length - 1;
                    result.push(JSON.parse(content));
                    console.log("deliveryTag:" + msg.fields.deliveryTag)
                    if (messageCount == deliveryTag) {
                        console.log(" [x] Done messageCount");
                        eventEmitter.emit('consumeDone')
                        channel.cancel(msg.fields.consumerTag)
                        channel.ack(msg);
                        channel.close();
                        channel = null;
                    }else {
                      setTimeout(function() {
                        console.log(" [x] Done");
                        channel.ack(msg);
                      },  secs *1000);
                    }
               }
    
              }
            }

```
 
this is how i init my queue:

 ```
exports.pushMessageToQueue = async function(queue,message){
            var exchange = queue + '.exchange';
          
          let channel = await conn.createChannel()
          await channel.assertExchange(exchange, type)
          let response = await channel.assertQueue(queue)
         
          channel.sendToQueue(response.queue, new Buffer(JSON.stringify(message)), {persistent: true});
        }
```
Anyone facing this problem, please help!

**Comment by cressie176** [comment]
Hi @TechGuyVN,

My guess is the message is being redelivered because it's not being successfully ack'd or nack'd. You can check this by seeing if the second message has a `redelivered` field.

What I am confident of is that prefetch works just fine - I use it in all my applications.

**Comment by TechGuyVN** [comment]
> Hi @TechGuyVN,
> 
> My guess is the message is being redelivered because it's not being successfully ack'd or nack'd. You can check this by seeing if the second message has a `redelivered` field.
> 
> What I am confident of is that prefetch works just fine - I use it in all my applications.

No, above is my code can you re-check my config had any wrong ?
i see in Queue lost 2 message after i request 1, it not in redelivered message

**Comment by cressie176** [comment]
Hi @TechGuyVN 

I don't have time to check your code at the moment, so the best I can do at present is offer some advice. I would start by writing something simpler that just consumes messages from the queue. Once you  get that working, I would look into adding message limiting behaviour, but possibly reconsider your approach...

From https://www.rabbitmq.com/confirms.html

> Delivery tags are monotonically growing positive integers and are presented as such by client libraries. Client library methods that acknowledge deliveries take a delivery tag as an argument.

"monotonically growing" just means increasing. I don't think the spec guarantees that the delivery tag always starts at 1 and increases by one for each message, for the lifetime of the channel (although the actual implementation may work this way).

**Comment by cressie176** [comment]
Try this...
```js
const amqplib = require('amqplib');

(async () => {
  const connection =  await amqplib.connect();

  async function getMessages(remaining) {
    const channel = await connection.createChannel();
    await channel.assertQueue('q');
    channel.prefetch(1);
    await channel.consume('q', async (message) => {
      if (message === null) return;
      console.log(message);
      if (--remaining) {
        await channel.ack(message); // I don't think await is necessary here but I left it for consistency
      } else {
        await channel.cancel(message.fields.consumerTag);
        await channel.ack(message);
        await channel.close();
      }
    });
  }

  await getMessages(3);
})();

setInterval(() => {}, 100000000)
```
Your issue could be because you are not waiting for the consumer to be cancelled or the message to be acknowledged before the channel is closed.

**Comment by cressie176** [comment]
Any luck @TechGuyVN ?

**Comment by TechGuyVN** [comment]
Thanks you @cressie176 , i will try it later.
finally i move to Java to solve my problem
