### ISSUE TITLE
ERROR: unable to verify the first certificate 

### ISSUE THREAD

**Issue by ramzes13** [squaremo/amqp.node#506]
Hello,
I have had the same problem as here #331 ,
After change my code to: 
```
const uri = 'amqp://localhost' // or amqps://.........
const parsedURI = url.parse(uri);

amqp.connect(uri, { servername: parsedURI.hostname })
```
I could make the connection.

At the moment I need to use Auto-reconnect and round robin support for amqplib.

I tried:
```
  const parsedURI = url.parse(credentials.uri_direct_1);
  const connectionOptions = { servername: parsedURI.hostname };
  const parsedURI2 = url.parse(credentials.uri);

  const connection = amqp.connect([parsedURI, parsedURI2], { connectionOptions });
```
With this config app is also conecting to the server.
I'm worried that in configuration there are 2 urls `parsedURI, parsedURI2`, But in `connectionOptions` are set only `servername` from one Url.

How can this problem be solved `correctly`?

**Comment by squaremo** [comment]
> At the moment I need to use Auto-reconnect and round robin support for amqplib.

Reconnection is not implemented in this library (in other words, you can't supply an array of URLs to `connect`). You will need to do this yourself, in which case it will be fairly easy to make the connection options depend on the URL.

**Comment by ramzes13** [comment]
Sorry, actually I use another library, but there I met the problem described #331  and I could solve with the solution described there.
I create issue in right place https://github.com/benbria/node-amqp-connection-manager/issues/82
