### ISSUE TITLE
in use amqplib i hava a problem in channels alocate

### ISSUE THREAD

**Issue by MojtabaRazmi** [squaremo/amqp.node#508]
when i use this code after get some data on my rabbit:
```
      let open = require('amqplib').connect('amqp://localhost:5672')
      open.then(function (conn) {
        return conn.createChannel()
      }).then(function (ch) {
        return ch.assertQueue(q1).then(function (ok) {
          ch.sendToQueue(q1, Buffer.from(JSON.stringify(review)))
          return ch.close()
        })
      }).catch(console.warn)
```
i got this error in response :
Error: No channels left to allocate
can any one help me to solve this problem?

**Comment by cressie176** [comment]
I believe this error means that you've somehow used up the number of channels allowed for the connection. See https://www.rabbitmq.com/channels.html#channel-max

The reasons are likely to be...

1. You are calling your code concurrently and rapidly
2. You are not closing channels. I see you have `ch.close()` but wonder whether you might be catching an error after opening the channel, and so bypassing this line.
3. Your client or server is misconfigured

**Comment by MojtabaRazmi** [comment]
i found out my mistake...
i used to open and close the channels very quickly and rapidly!
after handling the conections to rapid and controll channels by promice bace method i solve this problem!

**Comment by cressie176** [comment]
👍 Glad you got it sorted. Thanks for letting us know
