### ISSUE TITLE
How to resume receiving message for a consumer after executing channel.cancel method?

### ISSUE THREAD

**Issue by mrdulin** [squaremo/amqp.node#509]
I follow this doc https://www.squaremobius.net/amqp.node/channel_api.html#channel_cancel

The following code stop sending message to consumer: 

`channel.cancel(consumer.consumerTag);` 

Now, I want to resume sending message to the consumer? Is there a method can do this?

I need a feature like: [queue.subscribe](https://www.npmjs.com/package/amqp#queuesubscribeoptions-listener ) and [queue.unsubscribe](https://www.npmjs.com/package/amqp#queueunsubscribeconsumertag)

These two methods are provided by `amqp` library. 

What the equivalent feature using `amqplib`?

**update**

Here is my workflow:

```ts
async function consume(channel: Channel, conn: Connection) {
  let consumer: Replies.Consume;
  try {
    consumer = await channel.consume(
      QUEUE.HELLO,
      (message: ConsumeMessage | null) => onMessage(message, channel, consumer, conn),
      {
        noAck: false,
      },
    );
  } catch (error) {
    closeOnError(error, conn);
  }

  console.log('wait message');
}

async function onMessage(
  message: ConsumeMessage | null,
  channel: Channel,
  consumer: Replies.Consume,
  conn: Connection,
) {
  if (message) {
    count += 1;
    if (count < 3) {
      const content = message.content.toString();
      console.log('Received message.content: ', content);
      channel.ack(message);
    } else {
      await pause(channel, consumer);
      await sleep(5000);
      await resume(channel);
    }
  }
}
```

consumer logs:
```bash
☁  nodejs-rabbitmq [master] ⚡  npx ts-node src/cancel-and-recover/consumer.ts
[AMQP] connected
wait message
Received message.content:  {"name":"Ms. Grayce Simonis","email":"Enrique85@gmail.com"}
Received message.content:  {"name":"Ms. Paxton King","email":"Twila67@gmail.com"}
pause receiving message
recover receiving message
```

I tried `channel.recover()`, but the rabbitmq does not send unacknowledged message to the consumer again.

I want to resume sending message to the consumer after pausing 5 seconds later.

I am not sure I should use `channel.cancel` and `channel.recover` methods.

**Comment by cressie176** [comment]
Hi @mrdulin 

> #cancel(consumerTag, [function(err, ok) {...}])
>
>This instructs the server to stop sending messages to the consumer identified by consumerTag. Messages may arrive between sending this and getting its reply; once the reply has resolved, however, there will be no more messages for the consumer, i.e., the message callback will no longer be invoked.

> #recover([function(err, ok) {...}])
>
> Requeue unacknowledged messages on this channel. The server will reply (with an empty object) once all messages are requeued.

If I understand this correctly, cancel (eventually) cause the consumer to stop receiving new messages, but doesn't close the channel, so any inflight messages will still be acknowledged.

Recover doesn't resubscribe the consumer, it just requeues any unacknowledged messages.

Instead of using recover, I suspect you need to call consume again.

**Comment by mrdulin** [comment]
@cressie176 Thanks for replying. If I call `consume` again, it will create a new `onMessage` handler. 
If I call `consume` many times, I am not sure the previous `onMessage` handlers will be garbage collect(GC)? I worry about it will lead to a memory leak. 

What do you think?

**Comment by cressie176** [comment]
Mmmm. Not sure about that. I guess you could [test for memory leaks](https://medium.com/@clifcunn/an-adventure-with-a-memory-leak-in-node-3568128a0e83).

**Comment by mrdulin** [comment]
@cressie176 So, my question is does `amqplib` unbind or remove the `onMessage` event handler internally? Or, is there provide a method like `unbind`(`unsubscribe`, `removeEventListener`.. whatever) to remove previous `onMessage` handler in case of memory leak?

**Comment by cressie176** [comment]
Hi @mrdulin - I'm reasonably good with RabbitMQ and the amqplib API but don't know the internals of amqplib well enough to answer I'm afraid. Sorry.

**Comment by squaremo** [comment]
The design is such that you should be able to call `cancel` and `consume` as many times as you like. `cancel` removes the associated handler and forgets it.

In general though, using cancel to stop and start the message flow will not be very reliable. If you're doing so for the purpose of flow control, consider using `prefetch` instead.

**Comment by squaremo** [comment]
BTW I don't think `queue.subscribe` and `queue.unsubscribe` are anything other than aliases for `consume` and `cancel`.

**Comment by mrdulin** [comment]
Yes. Just a high-level API. The low-level method of rabbitmq is `basicConsume` and `basicCancel`. So, for `amqplib`, which method is `basicConsume` and which is `basicCancel`

**Comment by squaremo** [comment]
> which method is `basicConsume` and which is `basicCancel`. The `channel.consume` and `channel.cancel`?

Yes, respectively.
