### ISSUE TITLE
Channel#checkQueue Not working

### ISSUE THREAD

**Issue by ishanbhutagate6** [squaremo/amqp.node#510]
Channel#checkQueue Not working

TypeError: cb is not a function

**Comment by cressie176** [comment]
Hi @ishanbhutagate6 

I can imagine a few things are going wrong...

```#checkQueue(queue, [function(err, ok) {...}])```

1. You're not passing a 2nd parameter to the checkQueue method, therefore the callback(cb) is undefined, e.g. `checkQueue("my-queue-name")`
1. You're passing something that isn't a function as the 2nd parameter to the checkQueue method
1. You're using the callback api, but trying to use the checkQueue method as though it were a promise. Look for `require('amqplib/callback_api')` and `await checkQueue("my-queue-name") in your code base

If any of the above aren't it, then please paste your code

**Comment by cressie176** [comment]
@ishanbhutagate6 any update?

**Comment by ishanbhutagate6** [comment]
@cressie176 Thanks for the update, I have managed this according that you have suggested.
Thanks
