### ISSUE TITLE
consumer presence - check by consumer tag

### ISSUE THREAD

**Issue by Rudranand** [squaremo/amqp.node#511]
1. Unable to check the presence of consumer by the consumer tag.
2. If we are trying to create multiple consumers with the same consumer tag then its throwing error and closing the channel.

**Comment by cressie176** [comment]
Hi @Rudranand,

Can you describe the specific problem you are experiencing, including code samples and error messages where relevant please?

**Comment by squaremo** [comment]
The consumer tag is generated by the server; it's not possible to supply the tag from user code.

**Comment by cressie176** [comment]
@squaremo the docs say something else?

From #consume(queue, function(msg) {...}, [options])

> #consume(queue, function(msg) {...}, [options])

> consumerTag (string): a name which the server will use to distinguish message deliveries for the consumer; mustn’t be already in use on the channel. It’s usually easier to omit this, in which case the server will create a random name and supply it in the reply.

However the above does explain why you can't create multiple consumers with the same tag.

**Comment by squaremo** [comment]
I beg your pardon, I was wrong about not being able to choose the consumer tag in user code, oops!

**Comment by cressie176** [comment]
@Rudranand any update?
