### ISSUE TITLE
channel.sendToQueue( ... ) sometimes fail to send some message

### ISSUE THREAD

**Issue by DjDCH** [squaremo/amqp.node#52]
I don't know if it's me or my setup, or if it's really a bug, but for some reason, `channel.sendToQueue( ... )` randomly fail to send some message. It's usually the first message of a series of message that got "forget", meaning if I'm idle for a while or I just restarted my app, the first message will not be send. But again, it's not all the time. I cannot tell _when_ it will happen. It just seems so random. Also, I do not get any error or exception about this (from what I know). 

When I use a `ConfirmChannel`, I'm always able to get the Ack (`Message acked` in the log), even for those messages who are not sent. I'm able to tell that the message is not received by using the `rabbitmqctl` utility.

My code look like this (complete file is available [here](https://github.com/DjDCH/rterminal.js/blob/master/webserver/app.js)):

``` js
channel.sendToQueue(queue, new Buffer(JSON.stringify(data2)), {}, function(err, ok) {
    if (err !== null) {
        console.warn(' [*] Message nacked');
    } else {
        console.log(' [*] Message acked');
    }
});
```

Is it a known issue? How can I solve or mitigate this problem?

EDIT: Can it be caused by the fact that I'm using the same channel to send and consume to/from different queues?

**Comment by Sadanandteggi** [comment]
Facing the same issue Any idea ?

**Comment by squaremo** [comment]
@Sadanandteggi What happens when you follow the advice given in the comments?
