### ISSUE TITLE
Failing to nack a message when process uncaughtException unless a setTimeout is used

### ISSUE THREAD

**Issue by gtsec** [squaremo/amqp.node#520]
I am trying to nack a RabbitMQ message after my application code crashes for whatever reason, but the following code doesn't nack fast enough, and so the message ends up unacked and requeued when the process gets restarted by nodemon.

```
process.on('uncaughtException', err => {
	nack();
	process.exit();
});
```
Unless I defer the `process.exit()` with `setTimeout` et al, the message remains unacked in Rabbit. Using asynchronous code in the uncaughtException handler is supposedly bad practice as well.

I notice that underlying `channel.nack` uses `socket.write` (*)
(https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback), and I'm so sure if that's truly synchronous. `socket.write` allows an optional callback, but clearly the callback returns later than `process.exit()` line. Even if `socketOpts.noDelay` is set to true (it seems to default to false), I am getting the same behaviour. My guess is that even if the nack message gets "sent out", Rabbit isn't processing it in time before the whole process is killed - though I'm also not sure about the order of what happens at this step exactly.

----
I also looked at the documentation here and found some relevant parts: https://www.squaremobius.net/amqp.node/channel_api.html
> Most operations in AMQP are RPCs, synchronous at the channel layer of the protocol but asynchronous from the library’s point of view. Accordingly, most methods either return promises, or accept callbacks, yielding the server’s reply (often containing useful information such as generated identifiers). RPCs are queued by the channel if it is already waiting for a reply – synchronising on RPCs in this way is implicitly required by the protocol specification.

The Flow Control section:
> Channels act like stream.Writable when you call publish or sendToQueue: they return either true, meaning “keep sending”, or false, meaning “please wait for a ‘drain’ event”.

> Those methods, along with ack, ackAll, nack, nackAll, and reject, do not have responses from the server. This means they do not return a promise in the promises API. The ConfirmChannel does accept a callback in both APIs, called when the server confirms the message; as well as returning a boolean.

And `connection.close()`:
> If your program runs until interrupted, you can hook into the process signal handling to close the connection:

```
var open = amqp.connect();
open.then(function(conn) {
  process.once('SIGINT', conn.close.bind(conn));
  return doStuffWithConnection(conn);
}).then(null, console.warn);
```
> NB it’s no good using process.on('exit', ...), since close() needs to do I/O.

(*)
https://github.com/squaremo/amqp.node/blob/master/lib/channel_model.js#L228
`Channel#sendImmediately` < `connection#sendMethod` < `buffer.write`

**Comment by cressie176** [comment]
I guess you're trying to `Nack` the message that caused your application to crash to prevent it happening again?

I take a slightly different approach. RabbitMQ sets a `redelivered` flag on the message when it has been rolled back - unfortunately it's just a boolean not the number of attempts. A naive approach is to immediately `Nack` any messages that have been redelivered.

However this has the chance of dropping / dead lettering messages that might have been redelivered for other reasons other than being bad. For this reason I increment a counter in redis using the messageId as the key (needs to be unique set by the publisher) but just for redelivered messages. Only when the counter exceed my retry limit do I `Nack` the message.

**Comment by KristjanTammekivi** [comment]
process.exit() is essentially immediate, so of course the nack doesn't reach rabbitmq. The proper solution would be to cancel the consumer (you get a cancelTag when you start consuming, use channel.cancel(consumerTag)), then wait for all the messages to finish processing and then exit the application

**Comment by gtsec** [comment]
Thanks for the replies. I am now taking the approach of doing a `channel.close(callback)` before my `process.exit()`. I also do `channel.ack()` in case any redelivered messages surfaces when my worker restarts, thus having double protection.

> process.exit() is essentially immediate, so of course the nack doesn't reach rabbitmq. The proper solution would be to cancel the consumer (you get a cancelTag when you start consuming, use channel.cancel(consumerTag)), then wait for all the messages to finish processing and then exit the application

I don't supply a `consumerTag` in the `options` for `channel.consume()`, so I wonder if it would be randomly assigned on every worker restart.

**Comment by KristjanTammekivi** [comment]
Consumer tags are scoped to channels anyway (according to docs "mustn’t be already in use on the channel")

**Comment by cressie176** [comment]
ok to close @gtsec?

**Comment by gtsec** [comment]
Yes, thanks for everyone's help.
