### ISSUE TITLE
cosuming messages for some time will encounter Channel closed 

### ISSUE THREAD

**Issue by salamander-mh** [squaremo/amqp.node#521]
here is the output
```
{ IllegalOperationError: Channel closed
    at Channel.<anonymous> (/home/salamander/文档/douyin-spider/node_modules/amqplib/lib/channel.js:154:11)
    at Channel.C.ack (/home/salamander/文档/douyin-spider/node_modules/amqplib/lib/channel_model.js:219:8)
    at channel.consume.noAck (/home/salamander/文档/douyin-spider/get_user_info.js:156:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Channel closed',
  stack:
   'IllegalOperationError: Channel closed\n    at Channel.<anonymous> (/home/salamander/文档/douyin-spider/node_modules/amqplib/lib/channel.js:154:11)\n    at Channel.C.ack (/home/salamander/文档/douyin-spider/node_modules/amqplib/lib/channel_model.js:219:8)\n    at channel.consume.noAck (/home/salamander/文档/douyin-spider/get_user_info.js:156:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  stackAtStateChange:
   'Stack capture: Socket error\n    at Connection.C.onSocketError (/home/salamander/文档/douyin-spider/node_modules/amqplib/lib/connection.js:354:13)\n    at Socket.emit (events.js:187:15)\n    at Socket.EventEmitter.emit (domain.js:441:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' }

```
and I got error `[AMQP] error read ECONNRESET`

**Comment by cressie176** [comment]
Hi @salamander-mh 

From the [Node.js docs](https://nodejs.org/api/errors.html)

> ECONNRESET (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the http and net modules.

AMQP uses a persistent connection so depending on the reliability of your network its possible to get errors like this. Often I've found that there's a firewall or bridge between the client and server which drops connections if there isn't much traffic. The protocol does allow you to a heartbeat frequency which reduces the chance of this happening but doesn't rule it out completely. My recommendations are to try tuning with the heartbeat value (see the RabbitMQ server and amqplib docs), but also to expect the occasional connection drop and handle this by reconnecting and resubscribing in the client.

**Comment by salamander-mh** [comment]
@cressie176   thks a lot

**Comment by cressie176** [comment]
OK to close @salamander-mh ?
