### ISSUE TITLE
consume rate control?

### ISSUE THREAD

**Issue by salamander-mh** [squaremo/amqp.node#522]
`channel.consume`will be invoked thousands of times when lots of mesages enter the broker, and then the memory of nodejs process will sharply increase, how to control the comsuming rate?

**Comment by cressie176** [comment]
Hi @salamander-mh 

Use prefetch

https://www.rabbitmq.com/consumer-prefetch.html
https://www.squaremobius.net/amqp.node/channel_api.html

There's lots of really good information in the RabbitMQ and amqplib channel api documentation. Worth having at least a skim through - you'll avoid lots of errors.

e.g. when the channel closes you can receive a `null` message. This one trips lots of people up.

**Comment by salamander-mh** [comment]
@cressie176   got it!!
