### ISSUE TITLE
gracefully stop consume?

### ISSUE THREAD

**Issue by salamander-mh** [squaremo/amqp.node#524]
my problem is when Node process recevice `CTRL-C` signal, `channel` can gracefully stop consuming.
Any api of this library?

**Comment by squaremo** [comment]
If you can install signal handlers in Node.JS (and I believe you can), then you can close the channel before exiting. If you are acknowledging messages, any that remain unacknowledged when the channel is closed will be returned to the queue, or otherwise handled according to the server's policy.

**Comment by KristjanTammekivi** [comment]
Yeah you can, somewhat pseudocode:
const { consumerTag } = channel.consume(queueName, callback);
process.on('SIGINT', async () => {
  await channel.cancel(consumerTag);
  console.log('consumer was gracefully cancelled, the callback will not receive any new messages');
 // Now just wait for all your messages to finish processing
});

**Comment by salamander-mh** [comment]
@KristjanTammekivi  thks a lot.
