### ISSUE TITLE
Event Exchange Plugin Support

### ISSUE THREAD

**Issue by aviranco** [squaremo/amqp.node#527]
Hi,

Does the library supports events emitted by Event Exchange Plugin?
like detecting connect/disconnect events of queues, exchanges and bindings explained here: 
https://www.rabbitmq.com/event-exchange.html

Other than this plugin, it seems there is no way to detect disconnection of another clients other than heartbeats.

**Comment by KristjanTammekivi** [comment]
By the looks of things this plugin just creates a new topic exchange called amq.rabbitmq.event so yeah, just create a new queue, bind it to the exchange and you're ready to consume those events
