### ISSUE TITLE
Version 0.5.4 breaking

### ISSUE THREAD

**Issue by jbblanchet** [squaremo/amqp.node#534]
Using Dubnium:

```
 Error: Cannot find module './defs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jbb/Temp/tt/node_modules/amqplib/lib/connection.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by gustavopaes** [comment]
Same here. Bug introduced in 0.5.4

```
Error: Cannot find module './defs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/gpaes/git/google-amp-indexing/node_modules/amqplib/lib/connection.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by gurpreetatwal** [comment]
I'm experiencing this as well

**Comment by cressie176** [comment]
Also seeing this.

**Comment by cressie176** [comment]
@squaremo looks like there might be something going on with npm. If I understand the [docs](https://docs.npmjs.com/misc/scripts)

> prepare: Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

`npm publish` should have run the [prepare](https://github.com/squaremo/amqp.node/blob/master/package.json#L30) script, which would have generated the lib/defs.js

Maybe it did but `.npmignore/.gitignore' behaviour has changed so lib/defs.js still wasn't published.

**Comment by cressie176** [comment]
I just tried running `npm publish` locally (I added a .npmrc file so it wouldn't actually try publishing to npm) and lib/defs.js was generated and packaged correctly.

```
euphrosyne:amqp.node steve$ npm publish

> amqplib@0.5.4 prepare .
> make

curl -L https://raw.githubusercontent.com/rabbitmq/rabbitmq-codegen/rabbitmq_v3_2_1/amqp-rabbitmq-0.9.1.json > bin/amqp-rabbitmq-0.9.1.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27471  100 27471    0     0  78065      0 --:--:-- --:--:-- --:--:-- 78264
(cd bin; node ./generate-defs.js > ../lib/defs.js)
./node_modules/.bin/uglifyjs ./lib/defs.js -o ./lib/defs.js \
		-c 'sequences=false' --comments \
		-b 'indent-level=2' 2>&1 | (grep -v 'WARN' || true)
npm notice 
npm notice 📦  amqplib@0.5.4
npm notice === Tarball Contents === 
npm notice 881B    package.json                                          
npm notice 727B    callback_api.js                                       
npm notice 10.3kB  CHANGELOG.md                                          
...                                   
npm notice 1.1kB   lib/credentials.js                                    
npm notice 135.8kB lib/defs.js                                           
npm notice 673B    lib/error.js  
...                                        
npm notice === Tarball Details === 
npm notice name:          amqplib                                 
npm notice version:       0.5.4                                   
npm notice package size:  77.5 kB                                 
npm notice unpacked size: 396.5 kB                                
npm notice shasum:        2f70e8adde24ea2a475cf001e25f8b6fc4890dfe
npm notice integrity:     sha512-CP4jin1oSNDIn[...]h6viFWwuhvDyQ==
npm notice total files:   66  
```

**Comment by cressie176** [comment]
@squaremo let me know if you'd like me to 

1. deprecate 0.5.4
1. publish 0.5.5 with the missing defs

**Comment by Dentxinho** [comment]
> Same here. Bug introduced in 0.5.4

Same here too.

**Comment by OmegaPrimeZ3** [comment]
Same here

**Comment by astormnewrelic** [comment]
Not sure how useful it is at this point, but we're seeing the same things.  Builds breaking with the 

>  Error: Cannot find module './defs'

error message, and it looks like there's no `defs.js` file in the latest `0.5.4` package.

    $ npm install amqplib@0.5.3
    npm WARN foo@1.0.0 No description
    npm WARN foo@1.0.0 No repository field.

    + amqplib@0.5.3
    updated 1 package and audited 17 packages in 1.23s
    found 0 vulnerabilities

    $ find node_modules/ -name defs.js
    node_modules//amqplib/lib/defs.js
    $
    
vs.

    $ npm install amqplib@0.5.4
    npm WARN foo@1.0.0 No description
    npm WARN foo@1.0.0 No repository field.

    + amqplib@0.5.4
    updated 1 package and audited 17 packages in 1.386s
    found 0 vulnerabilities

    $ find node_modules/ -name defs.js
    $

**Comment by seivad** [comment]
```npm install amqplib@0.5.3``` is working for me this morning for now.

**Comment by gdxhsw** [comment]
Same here, I suggest to publish a new version to fix it.

**Comment by cressie176** [comment]
My guess is that the package was published using npm4, hence prepare didn't run.

**Comment by kuyh** [comment]
It seems add prepublish scripts for backward compatibility will solve this issue.

```
  "scripts": {
    "test": "make test",
    "prepublish": "make",
    "prepare": "make"
  },
```

**Comment by sshtel** [comment]
```
$npm install
npm WARN deprecated istanbul@0.1.46: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> amqplib@0.5.4 prepare /Users/sesong/workspace/opensource/amqp.node
> make

curl -L https://raw.githubusercontent.com/rabbitmq/rabbitmq-codegen/rabbitmq_v3_2_1/amqp-rabbitmq-0.9.1.json > bin/amqp-rabbitmq-0.9.1.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27471  100 27471    0     0  32594      0 --:--:-- --:--:-- --:--:-- 32587
(cd bin; node ./generate-defs.js > ../lib/defs.js)
./node_modules/.bin/uglifyjs ./lib/defs.js -o ./lib/defs.js \
		-c 'sequences=false' --comments \
		-b 'indent-level=2' 2>&1 | (grep -v 'WARN' || true)
added 91 packages from 373 contributors and audited 113 packages in 7.618s
found 8 vulnerabilities (3 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

`npm install` seems likely to run make automatically (0.5.4) maybe travis deploy script need to be fixed. as @kuyh metioned above, ` "prepublish": "make",` is missing now

**Comment by cressie176** [comment]
> It seems add prepublish scripts for backward compatibility will solve this issue.
> 
> ```
>   "scripts": {
>     "test": "make test",
>     "prepublish": "make",
>     "prepare": "make"
>   },
> ```

I don't think there's any need to add prepublish. It's been deprecated and prepare works with npm5

**Comment by sshtel** [comment]
right, actuall `"prepare": "make"` will work fine tho

**Comment by sshtel** [comment]
https://github.com/squaremo/amqp.node/pull/536

Please review PR if you don't mind. I changed also Travis VM image to xenial to fix CI build error

**Comment by ShinChven** [comment]
I rollbacked to elder version.

**Comment by cooperhsiung** [comment]
It bothered me for a while. :flushed:

**Comment by sshtel** [comment]
0.5.5 is released.  https://www.npmjs.com/package/amqplib 
build is ok for me now.

**Comment by squaremo** [comment]
Sorry folks, 0.5.4 was the first release using TravisCI for automation. Let's say it is not that easy to debug. The npm version for the deploy stage is v6, deliberately -- but TravisCI's "deploy provider" uses npm v2 instead, which was not obvious until I went back and looked at why it would miss out the generated file.

As noted above, v0.5.5 is published now. I've verified that it _does_ include the generated file. If there are other problems with it, please reopen.

**Comment by ntfs32** [comment]
v0.5.5 work ok, thanks …^_^

**Comment by cressie176** [comment]
@squaremo what about deprecating 0.5.4 in npm? e,g,

```
npm deprecate amqplib@0.5.4 'See github.com/squaremo/amqp.node/issues/534'
```

**Comment by squaremo** [comment]
> what about deprecating 0.5.4

Good idea -- done. I should fix up the changelog too.
