### ISSUE TITLE
assertExchange callback not returning

### ISSUE THREAD

**Issue by brecke** [squaremo/amqp.node#537]
Hi,

I am trying to use the `assertExchange` callback api but it stalls forever without returning neither `err` nor `ok`. Example below:

```
const declareExchange = function(exchangeName, exchangeOptions, callback) {
  channel.assertExchange(exchangeName, exchangeOptions.type, exchangeOptions, (err, ok) => {
    if (err) log().error({ exchangeName, err: new Error('Unable to declare an exchange') });

    exchanges[exchangeName] = ok.exchange;
    return callback();
  });
};
```

In this example I'm using `exchangeOptions` as `{ type: "direct", durable: true, autoDelete: false }` and the `exchangeName` is not null nor empty string.

I know this can blow up the channel if the exchange already exists but if I place a checkpoint before that line is executed and manually delete it, the same happens although the exchange eventually appears in the management UI. Don't know what I'm doing wrong.

Thanks in advance,

**Comment by cressie176** [comment]
Hi @brecke,
Sorry to ask - the times I've seen this before it's because the promise API was being used accidentally. Can you just confirm you've imported the correct API?

**Comment by brecke** [comment]
I just realized the import statement is different for callbacks... I just assumed amqplib was using something like `promise-breaker` and didn't notice the `require` statement. Sorry mate.

In any case, if you've seen this before then may I suggest making this more explicit in the README? It's fairly easy to miss.
