### ISSUE TITLE
Create mirrored queues using channel.assertQueue

### ISSUE THREAD

**Issue by vincenzodnp** [squaremo/amqp.node#538]
Hello there.
I have a 3 nodes RabbitMQ cluster, working like a sharme. If I set policies by hand or by using definitions.json file, the mirroring of the queue works.
But this requires a cluster setup that is not so flexible, because I'd like to write a client code capable of set mirrored queues.
Reading documentation, I saw `channel.assertQueue` accepts extra `x-` parameters.
Is it possible to create policies with amqp library? or is it possible to create mirrored queues during queue creation?
Thanks
Vincenzo

**Comment by flux627** [comment]
Also would like a solution for creating policies with this library.

**Comment by cressie176** [comment]
I don't see anything about creating policies in the [amqp 0.9.1 protocol](https://www.rabbitmq.com/amqp-0-9-1-reference.html), nor the [rabbitmq extensions](https://www.rabbitmq.com/extensions.html). Assuming I'm correct, I don't think this functionality belongs in amqplib.

Two options you might consider for your application...

1. Writing a module / code to create the policies via http and the management plugin.
2. Automating it by calling `rabbitmqctl` from your application. I've also done this in the past using a [kubernetes init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) to isolate the rabbitmq executables from my application.

**Comment by flux627** [comment]
I'm assuming the `rabbitmqctl` speaks `amqp` to the server to set up the policy. I'm interested to do the same from Javascript. What internals of this library can I use to leverage talking to the server in the same way, even if it makes sense to not include it in this library?

**Comment by cressie176** [comment]
@flux627 I'm not sure how rabbitmqctl communicates with the server, but if setting up policies isn't part of the amqp protocol, then I doubt it uses that protocol.

**Comment by cressie176** [comment]
According to the RabbitMQ docs, you have to configure mirrored queues via [policies](https://www.rabbitmq.com/parameters.html#policies) rather than `x-` arguments

> In addition to mandatory properties (e.g. durable or exclusive), queues and exchanges in RabbitMQ have optional parameters (arguments), sometimes referred to as x-arguments. Those are provided by clients when they declare queues (exchanges) and control various optional features, such as queue length limit or TTL.
>
> Client-controlled properties in some of the protocols RabbitMQ supports generally work well but they can be inflexible: updating TTL values or mirroring parameters that way required application changes, redeployment and queue re-declaration (which involves deletion). In addition, there is no way to control the extra arguments for groups of queues and exchanges. Policies were introduced to address the above pain points.

You can do this via the admin console, rabbitmqctl and the http api, but not via the amqp protocol (or by amqplib)

**Comment by nitinsinghit** [comment]
> Hello there.
> I have a 3 nodes RabbitMQ cluster, working like a sharme. If I set policies by hand or by using definitions.json file, the mirroring of the queue works.
> But this requires a cluster setup that is not so flexible, because I'd like to write a client code capable of set mirrored queues.
> Reading documentation, I saw `channel.assertQueue` accepts extra `x-` parameters.
> Is it possible to create policies with amqp library? or is it possible to create mirrored queues during queue creation?
> Thanks
> Vincenzo

Hi @vincenzodnp 

I configured 3 node cluster and looking for a cluster connection string. I can connect to the individual nodes by but cannot find anything where i can pass array of nodes in connection string.

**Comment by cressie176** [comment]
Hi @nitinsinghit,
That's not supported, however it's easy enough to pick one of the elements of the array at random.
