### ISSUE TITLE
My RabbitMQ amqplib reconnection logic is failing

### ISSUE THREAD

**Issue by whoisstan** [squaremo/amqp.node#541]
I have a javascript class in node environment, node 10.16 and amqplib 0.5.5, that manages my rabbitMQ connection. It should attempt to reconnect in case of a connection failure. 

```javascript
class Queue {

  constructor(url) {
    this.url = url;
  }
  async connect() {
    console.log("before connect method");
    try{
      this.connection =  await require('amqplib').connect(this.url);
      console.log("after connect method"); 
  
      this.connection.on("error",  (error)=>{
        console.log("connection error",error);
        setTimeout(()=>this.connect(),500)        
      });
      this.connection.on("close",   async (error)=> {
        console.log("connection error",error);
        setTimeout(()=>this.connect(),500)
      });             
      console.log("connected"); 
    }
    catch(error){
      //queue maybe be still booting up
      console.log("connection creation error",error);
      setTimeout(()=>this.connect(),500)
    }
    
  }
}

new Queue(process.env.URL).connect();

setInterval( ()=>null,500);

```

So when I run the above code and restart the rabbitMQ process after it connected I see the following

    reconnect_1  | before connect method
    reconnect_1  | after connect method
    reconnect_1  | connected
    NOW I RESTART
    reconnect_1  | connection error { Error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
    reconnect_1  |     at Object.accept (node_modules/amqplib/lib/connection.js:91:15)
    reconnect_1  |     at Connection.mainAccept (node_modules/amqplib/lib/connection.js:64:33)
    reconnect_1  |     at Socket.go (node_modules/amqplib/lib/connection.js:478:48)
    reconnect_1  |     at Socket.emit (events.js:198:13)
    reconnect_1  |     at emitReadable_ (_stream_readable.js:554:12)
    reconnect_1  |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 320 }
    reconnect_1  | before connect method

It never moves beyond that and never re-establishes the connection. How do I fix that? Am I using an anti-pattern?

Also posted that here:
https://stackoverflow.com/questions/57926725/my-rabbitmq-amqplib-reconnection-logic-is-failing

**Comment by manuel-di-iorio** [comment]
1) No need to retry the connection on the 'error' event, because the  'close' event is immediately emitted after 'error'.
2) I tried your code and it successfully reconnected, when I stopped and started again the RabbitMQ service. You just need to wait more seconds. In fact I have 3 seconds (also try 5) as reconnection timeout.

**Comment by whoisstan** [comment]
>No need to retry the connection on the 'error' event, because the 'close' event is immediately emitted after 'error'.
good to know

>I tried your code and it successfully reconnected, when I stopped and started again the RabbitMQ service. You just need to wait more seconds. In fact I have 3 seconds (also try 5) as reconnection timeout.

you are right, except that in my settings, new mac book pro, using docker (4CPU's and 8G RAM) it sometimes would take more then 20s for the connection to come back (i only realized that later). essentially i have the above code in the a docker image and a rabbitmq container, i simply restart the rabbitmq container and inspect the behavior. 

the problem seems have to gone, i'm not unhappy but it's strange, now it re-connects in about 2-3 seconds.
