### ISSUE TITLE
How to send message with no payload

### ISSUE THREAD

**Issue by riker09** [squaremo/amqp.node#543]
I want to send a message with no payload. In my application the message event itself is sufficiant. I was not able to craft a 0 byte long message body.

Here is what I have tried:

```javascript
// Send NULL
ch.publish("exch", "routingkey", null);

// Send empty buffer
const buff = Buffer.from("");
ch.publish("exch", "routingkey", buff.buffer);

const buff2 = Buffer.from([]);
ch.publish("exch", "routingkey", buff2.buffer);
```

**Comment by cressie176** [comment]
Looks like this isn't possible. Out of curiosity why do you want to send an empty message, and could you send a message with an arbitrary. or perhaps moderately useful payload such as a timestamp.

**Comment by riker09** [comment]
Huh, interesting. Can you elaborate on the why, though?

In my application I can send some random data as body (and using a header to indicate this is a nice trick), sure. But I'm always trying to send as few bytes over the wire as possible.

**Comment by cressie176** [comment]
Sorry, I thought I'd tried your examples and they didn't work, however when I tried the following it published a zero byte message just fine.
```
const amqplib = require('amqplib');

(async () => {
  const connection = await amqplib.connect('amqp://localhost');
  const channel = await connection.createChannel();
  await channel.assertQueue('q');
  await channel.assertExchange('ex', 'fanout');
  await channel.bindQueue('q', 'ex')
  await channel.publish('ex', 'routingkey', Buffer.from(''));
})();

setInterval(() => {}, 1000000);
```

<img width="366" alt="Screen Shot 2020-02-01 at 06 52 14" src="https://user-images.githubusercontent.com/229672/73588312-6ad4e180-44bf-11ea-9a97-5fa7edc346d8.png">

**Comment by cressie176** [comment]
@riker09, did you get this working?

**Comment by riker09** [comment]
Hi @cressie176 , sorry for never leaving a reply. I currently don't have the time to try this, so I'll go ahead and close this issue. From the looks of it I believe your code is a valid approach (not saving the buffer in a variable) and maybe JavaScript is doing some magic in the background when one does. :man_shrugging: :sweat_smile:
