### ISSUE TITLE
No way to check queue bindings

### ISSUE THREAD

**Issue by arustle** [squaremo/amqp.node#547]
How do I check to see if a queue is bound to an exchange?

Scenario:

- CLIENT_A connects to RabbitMQ server and creates QUEUE_A that is bound to EXCHANGE_1.
- Then EXCHANGE_1 is deleted.
- Then CLIENT_B tries to send a message, but notices there is no EXCHANGE_1.  So CLIENT_B creates EXCHANGE_1 and creates and binds QUEUE_B.
- Now QUEUE_A is no longer bound to EXCHANGE_1.

**Comment by cressie176** [comment]
I don't think there's anything in the amqp or RabbitMQ extensions to check bindings or receive notifications when a queue is unbound. The RabbitMQ HTTP probably lets you check bindings but I doubt this would be helpful without a notification.

Your best **technical** approach is for the publisher to listen for returned messages and to take action, however I'm curious why you fear exchanges being incorrectly deleted. If it's a process problem or bug then I attempting to automatically solve this technically will only ever be a partial solution. Someone could just as easily unbind the queue, purge it, consume messages from it, publish fake messages to it, bind another queue to the exchange so the messages wouldn't be returned, etc, etc.

**Comment by cressie176** [comment]
OK to close @arustle?

**Comment by arustle** [comment]
This rarely happens, but I had a case where the consumer was listening to messages from a queue, but the queue was no longer bound to the exchange.  I couldn't figure out why this happened, so I went the paranoid route and created a timer that `bindsQueue` every few seconds.

It would be great if the consumer had some way of knowing if the queue is still bound.

**Comment by cressie176** [comment]
One way to solve this would be to publish a test message on a timer. If the consumer doesn't receive the  test message without a period of time, take appropriate action.

**Comment by arustle** [comment]
Thanks. I like that better than my solution.
