### ISSUE TITLE
channel closed by server: 404 (NOT-FOUND) with message NOT_FOUND

### ISSUE THREAD

**Issue by lovegnep** [squaremo/amqp.node#552]
I have got this error:
"channel close by server: 404  (NOT-FOUND) with message  NOT_FOUND -no queue '**hehe**' in vhost '/'\""

my queue name is 'hehe', but the name in error is 'hehe' with expression, i dont know why, can anyone help?

**Comment by cressie176** [comment]
I know this sounds obvious but my first guess is there's a bug in the code that forms the queue name before it passes it to amqplib. Have you tried logging out the queue name before the call?

**Comment by cressie176** [comment]
Any update @lovegnep?

**Comment by lovegnep** [comment]
this is my code as follow
`    const conn = await mq.connect('amqp://127.0.0.1:5672')
    const channel = await conn.createChannel()
    await channel.assertQueue('hehe', {
        durable: false,
        autoDelete: true,
        messageTtl: 5 * 60 * 1000,
        expires: 2 * 3600 * 1000,
    })
    await channel.consume('hehe', (msg) => {
        ......
    })
`
I do not know why. because I have assertQueue, i think the queue must exist

**Comment by cressie176** [comment]
Hi @lovegnep,

You code worked fine in my environment. The queue was created with the specified attributes and when I published a message to it, it was received by the consumer.

<img width="1109" alt="Screen Shot 2020-01-06 at 21 55 25" src="https://user-images.githubusercontent.com/229672/71851834-57f10c00-30cf-11ea-926a-0f9121851f37.png">

Given you're seeing such a strange error message, I think it's worth considering that there might be something very unusual going on with your environment. E.g. could another node library be intercepting and monkeying with your code? For example https://www.npmjs.com/package/longjohn or https://www.npmjs.com/package/power-assert. Have you modified the amqplib code at any point, or symlinked (maybe using `npm link`) some and forgotten? Are you using RabbitMQ and if so what version?

I would be tempted to start a new project completely from scratch with a fresh docker image. The exact code I used was

```js
const mq = require('amqplib');

(async () => {
  const conn = await mq.connect('amqp://127.0.0.1:5672')
  const channel = await conn.createChannel()
  await channel.assertQueue('hehe', {
    durable: false,
    autoDelete: true,
    messageTtl: 5 * 60 * 1000,
    expires: 2 * 3600 * 1000,
  })
  await channel.consume('hehe', (msg) => {
    console.log(msg);
  })
})();

setInterval(() => {}, 60000);
```

I'm using amqplib@0.5.5 on OSX, starting docker with `docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.8.2-management` and running node v10.16.2

**Comment by cressie176** [comment]
Any luck @lovegnep?

**Comment by Danyelss** [comment]
This is what I use to create an exchange for the channel created on the connection:

```
const channel = await connection.createChannel();

await channel.assertExchange('hehe-exchange', 'topic', {
     durable: true
     });
});
```
        
Then I use this to connect to the topic and create the queue:

```
channel = await connection.createChannel();

channel.assertQueue(queue, {
   durable: false
});

channel.bindQueue('hehe', 'hehe-exchange', routingKey);

await channel.consume('hehe', async function (msg) {
   console.log(msg);
}
```

**Comment by cressie176** [comment]
```
channel = await connection.createChannel();

channel.assertQueue(queue, {
   durable: false
});

channel.bindQueue('hehe', 'hehe-exchange', routingKey);

await channel.consume('hehe', async function (msg) {
   console.log(msg);
}
```

There are a couple of bugs in the above...

1. queue hasn't been defined (I assume it is 'hehe')
2. You. aren't awaiting assertQueue or bindQueue
