### ISSUE TITLE
Setting `prefetch` value per consumer 

### ISSUE THREAD

**Issue by agarwalkartik** [squaremo/amqp.node#558]
How can I define seperate `prefetch` value for every consumer. As far as I can understand, the `prefetch()` function works at channel level. It sets the prefetch value for the whole channel. (please correct me if I am wrong here ->) This creates problems if one of the queues has lot of messages but others have only a few messages. The consumers for queues with fewer messages have to wait a lot of time for them to get messages   .

What I want is a prefetch value for each consumer so that messages are processed timely. I see that there is some mention of prefetch value being consumer specific from version 3.3.0 onwards, but still I cannot find how to achieve the same. Thanks a lot.

**Comment by cressie176** [comment]
From the [channel api](https://www.squaremobius.net/amqp.node/channel_api.html#channel_prefetch) documentation...

> NB RabbitMQ v3.3.0 changes the meaning of prefetch (basic.qos) to apply per-consumer, rather than per-channel. It will apply to consumers started after the method is called. See rabbitmq-prefetch.

I take this to mean that provided your setup your consumers sequentially, you could customise the channel prefetch before each call to `channel.consume`. This should be relatively easy to test just by setting up two consumers with a different prefetch and looking at the RabbitMQ admin ui

![Screenshot 2020-02-19 at 12 09 25](https://user-images.githubusercontent.com/229672/74833126-c6e99380-5310-11ea-9ed0-21b996a57d1f.png)

Alternatively you could always establish a different channel per consumer, which is what I'd usually recommend - this way if one of your consumers causes a channel error (e.g. by acking a message twice), you won't affect the other consumers.

**Comment by agarwalkartik** [comment]
thanks a lot. Different channels for each consumer seems to be a neater solution. But will anyways try to implement this by changing prefetch value for the channel before each consumer registration.

**Comment by agarwalkartik** [comment]
Update: Setting prefetch value for channel before consumer registration works. I did something like this

```
	channel.prefetch(10);
	channel.consume(queue1, consumer1);


	channel.prefetch(100);
	channel.consume(queue2, consumer2);
```

This allows us to have different values for each consumer.
