### ISSUE TITLE
From 0.5.3 onwards, URLs that don't contain slashes after protocol are not supported anymore

### ISSUE THREAD

**Issue by aml2610** [squaremo/amqp.node#559]
Hi, thanks for this nice library!

Bumping from 0.5.2 to 0.5.3 caused the library to be unable to connect to my RabbitMQ server. I dug a bit into it and found out it was because the URL I pass when trying to connect is something like `amqp:localhost` so does not contain slashes after the protocol. 
On the other hand `amqp://localhost` seems to be working. 

I can see there was [a PR that introduced a 3rd party URL parsing library](https://github.com/squaremo/amqp.node/pull/395) released with 0.5.3 and I tested that library with my URL. Indeed if you don't supply the slashes it won't parse correctly and the `host` and `hostname` properties of the URL won't be populated.

I am opening this issue to:
1) first make sure contributors and users are aware of this new incompatibility (not being able to pass URLs without slashes after protocol)
2) ask if instead we'd still like to support those kind of URLs? (I am happy to contribute with a fix, either here or on the URL parser side; but I do realise we might not care about it that much)

Thoughts?

Andrei

**Comment by squaremo** [comment]
The [syntax for amqp URLs](https://www.rabbitmq.com/uri-spec.html) requires "amqp://" specifically; if "amqp:" was allowed before, that was too permissive. (I see the [amqplib docs](http://www.squaremobius.net/amqp.node/channel_api.html#connect) imply that `amqp:` might be valid, accidentally).

Thanks for logging this, it should indeed help people who also run into this. I think if it's reasonably easy to discover the correct syntax, it's not worth the trouble to circumvent the URL parser.

**Comment by aml2610** [comment]
right, makes sense 👍
