### ISSUE TITLE
Frame size exceeds frame max ERROR

### ISSUE THREAD

**Issue by Mayhem93** [squaremo/amqp.node#560]
Hello,

So I've recently picked up working on my project again (it's been like almost a year) and I'm encountering the "`Frame size exceeds frame max`" error.

I'm using RabbitMQ@3.8.2 through windows docker and the version of amqplib is 0.5.5

I isolated the connection part of the code and tried running this script:

```javascript
const amqplib = require('amqplib');
const config = require('./config.json').amqp;

(async () => {
	await amqplib.connect({
		protocol: 'amqp',
		port: 5672,
		host: config.host,
		username: config.user,
		password: config.password,
		frameMax: 4096
	});
})();

process.on('unhandledRejection', err => {
	console.log(err);
	process.exit(1);
});
```
...but I still get that error

I've looked all over the internet for this error but nothing actually helps me 🙁

Maybe is there a RabbitMQ setting that I'm missing? I've also look out for it but didn't find anything

**Comment by cressie176** [comment]
Hi @Mayhem93,

When this error has been [previously reported](https://github.com/squaremo/amqp.node/issues/462), it's been down to message headers. Is that a possibility?

**Comment by Mayhem93** [comment]
> Hi @Mayhem93,
> 
> When this error has been [previously reported](https://github.com/squaremo/amqp.node/issues/462), it's been down to message headers. Is that a possibility?

As you can see from the code snippet there's absolutely nothing added by me. The RabbitMQ installation is also brand new through docker

**Comment by cressie176** [comment]
Sorry @Mayhem93, assumed there was a consumer missing that was receiving messages from the broker. I'll try to reproduce later, although don't have a windows machine to try things out on.

Sounds like your networking foo is better than mine, but curious as to why you're getting an HTTP response from the server. I can't see RabbitMQ doing that unless somehow the Docker ports were incorrectly mapped and the request was being sent to the admin HTTP ui?

**Comment by Mayhem93** [comment]
> Sorry @Mayhem93, assumed there was a consumer missing that was receiving messages from the broker. I'll try to reproduce later, although don't have a windows machine to try things out on.
> 
> Sounds like your networking foo is better than mine, but curious as to why you're getting an HTTP response from the server. I can't see RabbitMQ doing that unless somehow the Docker ports were incorrectly mapped and the request was being sent to the admin HTTP ui?

Ok so the "HTTP" message comes in from another service (Google Play Music desktop). I knew about this that it's using the port 5672 for its API. What I don't understand is the fact that if I turn on Docker desktop first (the container automatically starts) THEN i open up GPM desktop, somehow the app "hijacks" the port and all communications go to its API instead of going to RabbitMQ.

We can close this.

**Comment by cressie176** [comment]
I had a similar problem with Skype once. Thanks for updating.

**Comment by winrono** [comment]
For whoever ends up visiting this page: in my case the rootcause of "Frame size exceeds frame max" error on connect to RabbitMQ was due to missing "s" in protocol part of URL (so instead of  **amqp://** I was supposed to use **amqps://**)

Hope it will help someone :)

**Comment by cressie176** [comment]
Thank you @winrono

**Comment by justinaslelys** [comment]
Commenting on closed issue, but I would like to share the cause of mine "Frame size exceeds frame max" problem, hopefully it will save some time for others.

I was trying to connect to Artemis Active MQ using this library and after some troubleshooting realised that **this library supports only AMQP 0-9-1** protocol, while [Artemis is supports only AMQP 1.0](https://activemq.apache.org/components/artemis/documentation/latest/amqp.html).

**Comment by alexandros-cr** [comment]
@winrono You're my hero, this was exactly the issue for me.
