### ISSUE TITLE
sendToQueue fails randomly and silently

### ISSUE THREAD

**Issue by mnguyen25** [squaremo/amqp.node#561]
I'm using amqplib version 0.5.5, node 10.15.1 and rabbitmq 3.7.8. I'm facing a similar issue regarding [#383 ](https://github.com/squaremo/amqp.node/issues/383). This only fails on production, never on development. It seems that this happens after the channel has been idle for a while. Here's my code:
```
const RABBIT_MQ_CONFIG = require("../../../config/rabbitmq_config.js");
const open = require("amqplib").connect(RABBIT_MQ_CONFIG.HOST);
const logger = require("../logger_google_cloud.js");
let ch = null;

const init = () => {
    return new Promise((resolve, reject) => {
        return open
            .then(connection => {
                return connection.createChannel();
            })
            .then(channel => {
                ch = channel;
                logger.info(`RabbitMQ server successfully connected, environment: ${RABBIT_MQ_CONFIG.ENVIRONMENT}`);
                return resolve();
            })
            .catch(err => {
                logger.error(err);
                return reject(err);
            });
    });
};

init();

module.exports = {
    publishToQueue: (queueName, data) => {
        return ch.assertQueue(queueName, { durable: true })
            .then(() => {
                return ch.sendToQueue(queueName, Buffer.from(JSON.stringify(data)));
            })
            .catch(err => {
                logger.error(err);
            });
    },
};
```

Would a `confirmChannel` help in this case? Thanks a lot.

**Edit 1:** Message might take up to 50KB in size.

**Comment by cressie176** [comment]
Hi @mnguyen25,

Using a confirm channel means you get an acknowledgement once the message has been received by the broker. In the case of persistent messages they must also have been written to disk, and I think there are other guarantees for mirrored queues. This could help under some circumstances, for example

* if your application consumed message A, then published message B, you could wait until receiving a confirmation for message B before acknowledging A.
* if you application publishes a message in response to an HTTP request, you could wait until receiving a confirmation before returning a 200

Obviously both of these scenarios will reduce your throughput and potentially increase the number of concurrent operations.

However, this still doesn't explain why you are losing messages. If a channel or connection error occurred, it should have been emitted by amqplib, and unless a handler was registered will have crashed your applications. One thing to check then is whether anything in your code base or dependencies may be registering a process error handler (e.g. `process.on('error', () => {})`) and swallowing the error.

Looking at your code it's also possible that your application is saturating the channel, and possibly crashing while there are messages are in flight. `ch.sendToQueue` returns a boolean which can help diagnose this.

It's also possible that some network infrastructure (e.g. a firewall or VPN) are deciding that the connection is idle and quietly closing it. You can detect / avoid this by configuring heartbeats (part of the AMQP specification)

Hope that helps.

**Comment by cressie176** [comment]
I should also point out that even with a confirm channel, you may need to decide what to do if your code never receives an acknowledgement from the broker after publishing a message. It looks like we've got this situation in one of our test environments at work. WireShark shows we're publishing a message, and the broker usually sends a `Basic.Ack` back immediately, but every now and again it goes missing. I suspect we're going to have to add a timeout into our application code and treat it as an error.

**Comment by mnguyen25** [comment]
Hi @cressie176, thanks for your information. I added event listeners on connection and channel error and close and there's no message lost anymore. However, I can see the connection got reconnected multiple times (re-init - the `RabbitMQ server successfully connected, environment: ${RABBIT_MQ_CONFIG.ENVIRONMENT}` line) but cannot find any error log at all, neither close or error event. That's odd.

`connection.on("error", err => {
					logger.error(logging_keyword, "CONNECTION ERROR", err);
					return setTimeout(init, 1000);
				});
				connection.on("close", () => {
					logger.error(logging_keyword, "CONNECTION CLOSED");
					return setTimeout(init, 1000);
				});
				connection.createConfirmChannel()
					.then(channel => {
						ch = channel;
						ch.on("error", err => {
							logger.error(logging_keyword, "CHANNEL ERROR", err);
							return setTimeout(init, 1000);
						});
						ch.on("close", () => {
							logger.error(logging_keyword, "CHANNEL CLOSED");
							return setTimeout(init, 1000);
						});
						logger.info(logging_keyword, `RabbitMQ server successfully connected, environment: ${RABBIT_MQ_CONFIG.ENVIRONMENT}`);
					})
					.catch(err => {
						logger.error(logging_keyword, err);
					});`

**Comment by cressie176** [comment]
This doesn't explain the lack of logging but it's possible that you get both error and close events. It may even be possible (I'm not sure) that you can get multiple error events on the same channel. You can either use something like [lodash.once](https://www.npmjs.com/package/lodash.once) to prevent initialising unnecessarily, or unregister all event handlers when an event has been triggered.

**Comment by mnguyen25** [comment]
@cressie176 I get the idea, thanks for the advice. Closing the issue.

**Comment by cressie176** [comment]
Just in case you missed it, I edited my response quite heavily.

**Comment by mnguyen25** [comment]
Thank you, very detailed comment. The later part of your answer was what I was suspecting. Got the data saved somewhere and sending the ID to the queue only, channel still closes. When I shutdown the feature completely and still using other queues somewhere else with message as little as an ID, channel still closes unexpectedly. I tried the above and it works fine.

**Comment by mnguyen25** [comment]
@cressie176 and yes, the reason was heartbeat timeout. We register a global uncaughtException logger and it went there.

**Comment by vinothrajs** [comment]
@mnguyen25 could you ping me the final code?
am also facing the same issue
