### ISSUE TITLE
QS.unescape is not a function

### ISSUE THREAD

**Issue by CrisGarcis** [squaremo/amqp.node#562]
error in amqplib/lib/connect.js:50

use decodeURI

**Comment by cressie176** [comment]
Hi @CrisGarcis,

Thanks for reporting. I assume you mean`decodeURIComponent`rather than `decodeURII`?

If I understand correctly `unescape` is not actually deprecated, just not recommended, but we should still look into replacing as you suggest. I found usage [here](https://github.com/squaremo/amqp.node/blob/962fb9ea3c4ac16368f8006c523b8a39182e11e0/lib/connect.js#L83-L84)

```
    user = (parts.username) ? unescape(parts.username) : '';
    passwd = (parts.password) ? unescape(parts.password) : '';
```

but not on [line 50](https://github.com/squaremo/amqp.node/blob/962fb9ea3c4ac16368f8006c523b8a39182e11e0/lib/connect.js#L50), which uses the standard and stable querystring node module.

```
    vhost = QS.unescape(vhost);
```

Although according to the [documentation](https://nodejs.org/api/querystring.html#querystring_querystring_unescape_str), `querystring.unescape` is not expected to be used directly, and actually calls `decodeURIComponent` under the hood, unless monkey patched. I suspect we can replace this too.

**Comment by cressie176** [comment]
I meant to ask - are you actually getting an `error` somehow because of this line?

**Comment by CrisGarcis** [comment]
QS use this functions

`{parse: ƒ, decode: ƒ, stringify: ƒ, encode: ƒ} `
never use unescape

**Comment by cressie176** [comment]
Hi @CrisGarcis,

What version of node are you using? [querystring.unescape](https://nodejs.org/docs/latest-v0.10.x/api/querystring.html) has been part of the standard build for as long as I can remember. It's documented as far back as [v0.10](https://nodejs.org/docs/latest-v0.10.x/api/querystring.html), and still present in [v13](https://nodejs.org/api/querystring.html#querystring_querystring_unescape_str)

```
euphrosyne:foo steve$ node --version
v0.8.28

euphrosyne:foo steve$ node
> const QS = require('querystring')
undefined
> console.log(QS.unescape('%3F'))
?
```

```
euphrosyne:foo steve$ node --version
v13.10.1

euphrosyne:foo steve$ node
> const QS = require('querystring')
undefined
> console.log(QS.unescape('%3F'))
?
```

**Comment by cressie176** [comment]
The [stackoverflow](https://stackoverflow.com/questions/50037969/getting-an-error-when-subscribing-a-queue) issue looks like the user was running in in the browser, or at least webpack was involved. amqplib is for node.js only. Could this be the problem.

**Comment by CrisGarcis** [comment]
my version node v11.15.0

**Comment by CrisGarcis** [comment]
it is possible that the problem is not running it in node.js, in the same way you should not get this error

**Comment by cressie176** [comment]
Works fine with v11.15.0. 
```
Now using node v11.15.0 (npm v6.7.0)
euphrosyne:rascal steve$ node
> const QS = require('querystring')
undefined
> console.log(QS.unescape('%3F'))
?
```

> it is possible that the problem is not running it in node.js, in the same way you should not get this error

I'm sorry, but I'm not sure I understand you. amqplib cannot be run from a browser for a number of reasons, some of which are detailed [here](https://stackoverflow.com/questions/44290367/can-i-use-amqplib-in-the-browser).

**Comment by CrisGarcis** [comment]
> Funciona bien con v11.15.0.
> 
> ```
> Now using node v11.15.0 (npm v6.7.0)
> euphrosyne:rascal steve$ node
> > const QS = require('querystring')
> undefined
> > console.log(QS.unescape('%3F'))
> ?
> ```
> 
> > es posible que el problema no se esté ejecutando en node.js, de la misma manera no debería obtener este error
> 
> Lo siento, pero no estoy seguro de entenderte. amqplib no se puede ejecutar desde un navegador por varias razones, algunas de las cuales se detallan [aquí](https://stackoverflow.com/questions/44290367/can-i-use-amqplib-in-the-browser) .

thank you

**Comment by CrisGarcis** [comment]
it is wrong?
 https://www.rabbitmq.com/tutorials/tutorial-six-javascript.html

**Comment by cressie176** [comment]
No it's not wrong, it's just that client !== browser.

> A client is a piece of computer hardware or software that accesses a service made available by a server. The server is often on another computer system, in which case the client accesses the service by way of a network.

https://en.wikipedia.org/wiki/Client_(computing)

**Comment by cressie176** [comment]
OK to close @CrisGarcis?
