### ISSUE TITLE
async await channel.consume

### ISSUE THREAD

**Issue by neoty** [squaremo/amqp.node#564]
It is known that the `prefetch` value is retrieved from` queue` in advance and stored in the consumer's memory. Apart from this, I wanted to process one by one in channel.consume, but I process it through an asynchronous loop.

Is this normal?

```
channel.consume(queue, async(payload) => {
      await axios.get('http://test.com/'); --> task 10 second
      console.log(1)
      channel.ack(payload)
    }, {noAck: false});
```

i expected 
10:00:10 -> 1
10:00:20 -> 1
10:00:30 -> 1

but, 
10:00:10 -> 1
10:00:10 -> 1
10:00:10 -> 1

**Comment by cressie176** [comment]
> It is known that the prefetch value is retrieved from queue in advance

I'm not sure this is correct. As per the [channel api docs](https://www.squaremobius.net/amqp.node/channel_api.html#channel_prefetch) prefetch is usually scoped to a consumer, but if not scopped to a channel.

> NB RabbitMQ v3.3.0 changes the meaning of prefetch (basic.qos) to apply per-consumer, rather than per-channel. It will apply to consumers started after the method is called. See rabbitmq-prefetch.

If you set `channel.prefetch(1);` it should work as you expect

**Comment by neoty** [comment]
@cressie176 
thanks for you answer!
i will just use `channel.prefetch(1);`

i think amqplib(nodejs) weird
