### ISSUE TITLE
RabbitMQ list functionality for queues, bindings and exchanges.

### ISSUE THREAD

**Issue by vlikin** [squaremo/amqp.node#565]
Probably I looked not so well but I do not list functionality for such entities. I hope I do not understand something. Does a reason exist that such functionality is absent. I've created a question related at [stackverflow](https://stackoverflow.com/questions/60771649/get-a-list-of-excahnges-bindings-queues-from-rabbitmq-by-nodejs).

**Comment by cressie176** [comment]
Hi @vlikin,

Unfortunately this isn't part of the amqp specification, so not part of this library. If you need to list queues you can use RabbitMQ's HTTP api.
