### ISSUE TITLE
Does this library support ssl_cert_login_from = common_name

### ISSUE THREAD

**Issue by brt-han-mai** [squaremo/amqp.node#568]
Does this library support `ssl_cert_login_from = common_name`?
Why does it always use PLAIN authentication?

**Comment by maixuanhan** [comment]
For external authentication mechanism, put the credentials into socket options when connecting.
I've never tried but after looked into the source code, I found it.
```js
socketOptions.credentials = {
    mechanism: 'EXTERNAL',
    response: function() { return Buffer.from(''); }
  }
```
