### ISSUE TITLE
ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN.

### ISSUE THREAD

**Issue by sssanjaya** [squaremo/amqp.node#574]
ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN.

amqplib v0.5.5

screenshot attached below:
![image](https://user-images.githubusercontent.com/17382749/83002054-4b446480-a02c-11ea-84d7-6273418bcb94.png)

**Comment by sssanjaya** [comment]
anybody solved this issue?

**Comment by cressie176** [comment]
Hi @sssanjaya, chances are either the password you're supplying is incorrect, or it includes characters which need to be escaped. e.g. https://github.com/squaremo/amqp.node/issues/483

**Comment by sssanjaya** [comment]
I have changed password to text only no special letters or symbols. Also set permission to vhost. 

Tried with cloudamqp too eg:

amqp://cxiugalk:LdtSD29IOOyXUr6ZMckCqrUECyG3NEWc@reindeer.rmq.cloudamqp.com/cxiugalk

Still no luck, help me please?

**Comment by cressie176** [comment]
Only other thing I can think of is to double check the port. It's possible you're attempting to connect to the management UI. Other than this I'm not sure there's much more help I can give - amqplib is widely used, so it's quite unlikely there is a problem with plain authentication.

**Comment by sssanjaya** [comment]
@cressie176 thank you. Finally found out that we were using multiple amqp connect in our codebase. It is now fix and working great. Will close this issue. Really appreciate your time. Thank you.

**Comment by alekspickle** [comment]
For anyone that came here from google - most probably you are using wrong URI, like `website.my-company.domain` instead of `website.my-company-beta.domain` or `website.my-company.another-domain`
