### ISSUE TITLE
Messages sent from large loops only get sent after those loops

### ISSUE THREAD

**Issue by TonyTheCokedUpTiger** [squaremo/amqp.node#576]
I want to create a giant graph of objects and therefore want to put the created objects on a queue so consumers can decide how to persist those created objects.

Consider this code:

```javascript
require('dotenv').config();
const amqplib = require('amqplib');

async function example() {
  const connection = await amqplib.connect(process.env.AMQP_CONNECTION_STRING);
  const channel = await connection.createChannel();

  await channel.assertQueue('parentsCreation');
  await channel.assertQueue('childCreation');

  const PARENTS_TO_CREATE = 1000;
  const CHILDS_TO_CREATE = 9999;

  for (let parentIndex = 0; parentIndex < PARENTS_TO_CREATE; parentIndex++) {
    console.log(parentIndex);
    const parent = {
      id: Math.floor(Math.random() * 999999)
    };

    await channel.sendToQueue('parentsCreation', Buffer.from(JSON.stringify(parent)));

    for (let childIndex = 0; childIndex < CHILDS_TO_CREATE; childIndex++) {
      const child = {
        id: Math.floor(Math.random() * 999999),
        parent: parent.id
      };

      await channel.sendToQueue('childCreation', Buffer.from(JSON.stringify(child)));
    }
  }

  console.log('Creation done');
}

example();
```

What you would expect is that the messages arrive at RabbitMq as soon as the respective code lines are hit. But this is not the case. The messages only **start** to arrive at RabbitMq **after** the line `console.log('Creation done');`, so after those big loops. If I kill the process now I loose any remaining messages that have not been sent to the server.

I've written the exact same thing in C# and there it works as expected so a setting on the server or client can be ruled out. I assume it's got something to do with the event loop or node itself but I cannot get my head around it.

**Comment by cressie176** [comment]
[channel.sendToQueue](https://www.squaremobius.net/amqp.node/channel_api.html#channel_sendToQueue) does not return a promise so the `await` in your code sample doesn't wait for the message to be sent. See [flow control](https://www.squaremobius.net/amqp.node/channel_api.html#flowcontrol)

> Channels act like stream.Writable when you call publish or sendToQueue: they return either true, meaning “keep sending”, or false, meaning “please wait for a ‘drain’ event”.
>
> Those methods, along with ack, ackAll, nack, nackAll, and reject, do not have responses from the server. This means they do not return a promise in the promises API. The ConfirmChannel does accept a callback in both APIs, called when the server confirms the message; as well as returning a boolean.

Instead if you want to wait until all messages have been acknowledged by the broker, you need to

a. use [confirm](https://www.squaremobius.net/amqp.node/channel_api.html#confirmchannel) channel rather than a normal channel
b. pass a callback to the sendToQueue function

**Comment by TonyTheCokedUpTiger** [comment]
Indeed, my awaits were pointless but if I changed the code to this (like the docs suggest):

```javascript
require('dotenv').config();
const amqplib = require('amqplib');

async function example() {
  const connection = await amqplib.connect(process.env.AMQP_CONNECTION_STRING);
  const channel = await connection.createChannel();

  await channel.assertQueue('parentsCreation');
  await channel.assertQueue('childCreation');

  const PARENTS_TO_CREATE = 1000;
  const CHILDS_TO_CREATE = 9999;

  for (let parentIndex = 0; parentIndex < PARENTS_TO_CREATE; parentIndex++) {
    const parent = {
      id: Math.floor(Math.random() * 999999)
    };

    console.log(parent, parentIndex);

    channel.sendToQueue('parentsCreation', Buffer.from(JSON.stringify(parent)), {}, (error, ok) => {
      console.log('parentsCreation callback', error, ok);
    });

    for (let childIndex = 0; childIndex < CHILDS_TO_CREATE; childIndex++) {
      const child = {
        id: Math.floor(Math.random() * 999999),
        parent: parent.id
      };

      channel.sendToQueue('childCreation', Buffer.from(JSON.stringify(child)), {}, (error, ok) => {
        console.log('childCreation callback', error, ok);
      });
    }
  }

  console.log('Creation done');
}

example();
```

Nothing changes and no callback ever gets hit no matter how long I keep the process alive. Also, intellisense doesn't even recognise a callback parameter on `sendToQueue` or `publish` - which screws me in TypeScript.

Whether the messages are acknowledge by the broker isn't interesting to me. I want a message to be sent to RabbitMq as soon as `sendToQueue` is called. But they only **start** to get sent **after** those loops. This is a problem because with very large loops it takes several minutes until messages start to arrive. Also: I cannot kill the process after the loops and I don't even know how long I would have to keep it alive until all messages are sent.

Again, if I write the same thing in C#, without a confirm channel and without waiting for anything, just sending from within very large loops, it works as expected.

**Comment by cressie176** [comment]
> Nothing changes and no callback ever gets hit no matter how long I keep the process alive.

You need to use **confirm** channels to get the callback...

```js
const channel = await connection.createChannel();
```
Should be
```js
const channel = await connection.createConfirmChannel();
```

> Whether the messages are acknowledge by the broker isn't interesting to me

If your script finishes before the messages have been acknowledged by the broker, they could still be buffered by the channel, and will be lost.

> Again, if I write the same thing in C#, without a confirm channel and without waiting for anything, just sending from within very large loops, it works as expected.

The difference is most likely because of Node's [event loop](
https://medium.com/the-node-js-collection/what-you-should-know-to-really-understand-the-node-js-event-loop-and-its-metrics-c4907b19da4c#:~:text=js%20Event%20Loop,-Daniel%20Khan&text=This%20means%20that%20everything%20that,mechanism%20called%20an%20event%20loop.)

**Comment by cressie176** [comment]
[waitForConfirms](https://www.squaremobius.net/amqp.node/channel_api.html#confirmchannel_waitForConfirms) might be a little easier than using callbacks. You still need to you confirm channels though.
