### ISSUE TITLE
Unable to set quorum queue type

### ISSUE THREAD

**Issue by lozadaOmr** [squaremo/amqp.node#578]
I'm trying to create a queue with type Quorum, and according to [this](https://www.rabbitmq.com/quorum-queues.html#declaring) I just have to set the queue argument to `quorum`

```
let options = {
  autoDelete: false,
  arguments: {
    'x-queue-type': 'quorum'
  }
}

channel.assertQueue(queueName, options)
```

Error: Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'data' in vhost 'foo'

**Comment by cressie176** [comment]
Hi @lozadaOmr,

WHen I've seen PRECONDITION-FAILED messages before it's been because the queue (or exchange) existed with different attributes. Could this be the problem?

If so you'll need to delete the queue before you can recreated it the `x-queue-type` attribute

**Comment by lozadaOmr** [comment]
Yes thanks @cressie176

**Comment by lnfel** [comment]
Just leaving here for future readers, typically exchanges are created as durable as seen on management ui. Trying to create a queue with durable option set to false and 'x-queue-type' to quorum, results in the error mentioned above. Setting durable to true fixed it for me.
