### ISSUE TITLE
Try to detect TCP connection drops

### ISSUE THREAD

**Issue by squaremo** [squaremo/amqp.node#58]
It's not clear to me that I cover all detectable cases of the TCP connection dropping.

**Comment by timon-michel-scopevisio** [comment]
Can you please add the "channel closed handling" as described in https://amqp-node.github.io/amqplib/#how-do-i-recover-from-a-connection-or-channel-error to the code examples? This caused a lot of headaches for me, until reading the Troubleshooting and i was almost overseeing this crucial step.

**Comment by cressie176** [comment]
@timon-michel-scopevisio I've added a comment covering your request to https://github.com/amqp-node/amqplib/issues/25
