### ISSUE TITLE
support for SAC (single active consumer)

### ISSUE THREAD

**Issue by SunilRangpadiya** [squaremo/amqp.node#590]
Hello,

I tried to use the new feature SAC of rabbitMq released in 3.8.  i.e. single active consumer
https://www.rabbitmq.com/consumers.html#single-active-consumer

I guess the current version of amqplib doesn't support that.

When we are expecting the support for the same?

**Comment by squaremo** [comment]
Single active consumer is enabled when you create a queue, by including the entry `{"x-single-active-consumer": true}` in the the table of arguments. You supply a table of arguments to [channel.assertQueue()](http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertQueue):

```javascript
var queuePromise = channel.assertQueue('name', {'arguments': {'x-single-active-consumer': true}});
```

**Comment by niket-pbtech** [comment]
Would it work if we pass `{'arguments': {'x-single-active-consumer': true}}` in channel.bindQueue as arguments ?
@squaremo

**Comment by cressie176** [comment]
Hi @niket-pbtech,

amqplib passes arguments straight through to the broker, so this is really a question for the RabbitMQ team. That said, I think it's unlikely. The [RabbitMQ documentation](https://www.rabbitmq.com/consumers.html) doesn't say anything about binding.

> Single active consumer can be enabled when declaring a queue, with the x-single-active-consumer argument set to true

Conceptually binding has nothing to do with consumption. You can have multiple bindings to a queue - what would you expect to happen if only one was set to single-active-consumer?
