### ISSUE TITLE
Can't fetch data from the queue.

### ISSUE THREAD

**Issue by raedon707** [squaremo/amqp.node#592]
I started AMQP server on AWS.
When i connect to the server to consume the data from queue, i get this error.

`Operation failed: QueueDeclare; 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - access to queue 'data_q' in vhost 'exampleVhost' refused for user 'example@gmail.com'`

There is no issues in connection, i'm getting the connection object.
When i try to get the data using django with same creds and same technique, it's working without any issue.
please help!

**Comment by cressie176** [comment]
Hi @raedon707,
Any unusual characters in the password? It could be down to URL escaping.

**Comment by raedon707** [comment]
> Hi @raedon707,
> Any unusual characters in the password? It could be down to URL escaping.

No.
Password is fine, no unusual characters.

**Comment by cressie176** [comment]
The error refers to "QueueDeclare". Maybe the user doesn't have the permission to create queues? Or perhaps you are using `channel.assertQueue` instead of `channel.checkQueue`

**Comment by raedon707** [comment]
> The error refers to "QueueDeclare". Maybe the user doesn't have the permission to create queues? Or perhaps you are using `channel.assertQueue` instead of `channel.checkQueue`

Nope, that's not the issue, i just checked.
It's working fine when i consume the queue in python from same machine.

**Comment by cressie176** [comment]
Can you paste your code from connection through to queue consumption please? Including any option values (obviously not secure ones you're setting). 

Can you also confirm the permissions for the vhost/user that you're connecting with?

Thanks

**Comment by raedon707** [comment]
> Can you paste your code from connection through to queue consumption please? Including any option values (obviously not secure ones you're setting).
> 
> Can you also confirm the permissions for the vhost/user that you're connecting with?
> 
> Thanks

`const` q = "list";

function bail(err) {
  console.error(err);
  process.exit(1);
}

function consumer(conn) {
  function on_open(err, ch) {
    if (err != null) bail(err);
    ch.assertQueue(q, { durable: false }, function (err, ok) {
      if (err !== null) return bail(err);
      ch.consume(
        q,
        function (msg) {
          console.log(msg);
          ch.ack(msg);
        },
        { noAck: true },
        function (_consumeOk) {
          console.log("wait...");
        }
      );
    });
  }
  conn.createChannel(on_open);
}

const params = {
  protocol: "",
  hostname: "",
  port: "",
  username: "",
  password: "",
  heartbeat: "",
  locale: "",
  vhost: "",
  auth: "",
  package: "",
  frameMax: 0,
};

require("amqplib/callback_api").connect(params, function (err, conn) {
  if (err != null) bail(err);
  process.once('SIGINT', function() { conn.close(); });
  consumer(conn);
`});`

a boilerplate code i found in the library readme.

**Comment by cressie176** [comment]
> ch.assertQueue(q, { durable: false }, function (err, ok) {

The above line, coupled with insufficient permissions could be your problem. `assertQueue` will send a 'queue declare' instruction to RabbitMQ which will create the queue if it does not exist. If the user does not have permission to declare a queue within the vhost ,then it makes sense for the broker to reply with a 403.

Can you also confirm the permissions for the vhost/user that you're connecting with? (you should be able to find these from the management UI assuming you've installed this plugin.

**Comment by raedon707** [comment]
> > ch.assertQueue(q, { durable: false }, function (err, ok) {
> 
> The above line, coupled with insufficient permissions could be your problem. `assertQueue` will send a 'queue declare' instruction to RabbitMQ which will create the queue if it does not exist. If the user does not have permission to declare a queue within the vhost ,then it makes sense for the broker to reply with a 403.
> 
> Can you also confirm the permissions for the vhost/user that you're connecting with? (you should be able to find these from the management UI assuming you've installed this plugin.

Ohhhh, got it. I don't have the write permission (I wanted my server like that).

Can you please tell, what parameter / permission is missing from my code in the above line? Or maybe if you could provide a boilerplate for options object.

**Comment by cressie176** [comment]
Try using `channel.checkQueue` instead of `channel.assertQueue`.
