### ISSUE TITLE
node v15 support

### ISSUE THREAD

**Issue by skarbovskiy** [squaremo/amqp.node#593]
Why 
```
"engines": {
  "node": ">=0.8 <=14"
}
```
I dont see any restrictions for v15

**Comment by davesag** [comment]
My various projects using `amqplib` all work fine under Node 15 so I believe this restriction can be lifted.

Note however, Node 15 comes with NPM 7.0.7 (as of current writing) which is a buggy pos and breaks a lot of things.  I am enforcing NPM >= 7.0.8 in my projects now. (Or people can use Yarn, or delete the v2 package-lock.json file and use npm 6)

**Comment by gajus** [comment]
Yeah, works fine on v15.

Regarding NPM, just set `--legacy-peer-deps` and it will work as NPM 6.

**Comment by davesag** [comment]
I recommend updating the `"engines" section of `package.json` to enforce `"npm":  "<= 6 >= 7.0.8"` and to allow node 15.  That should work and remove the warnings.

**Comment by Allain55** [comment]
Any update on this?

**Comment by davidLeonardi** [comment]
Bump

**Comment by deblanco** [comment]
Bump

**Comment by gperdomor** [comment]
@squaremo can you check this please? I can help sending a PR with the proposed change

**Comment by squaremo** [comment]
The tests don't pass with Node v15, e.g., https://travis-ci.org/github/squaremo/amqp.node/jobs/759402326.
Investigating.

**Comment by squaremo** [comment]
This is what is tripping up the tests: https://github.com/nodejs/node/pull/33075/files

**Comment by xamgore** [comment]
@squaremo great job, thank you very much! 👍
