### ISSUE TITLE
Does this lib has the exchangeDeclare method?

### ISSUE THREAD

**Issue by qing8888** [squaremo/amqp.node#594]
Hello, does this lib has the ```exchangeDeclare``` method?
How do I declare a exchange dynamically?
![image](https://user-images.githubusercontent.com/25190239/97998524-2f3bbf00-1e25-11eb-8f8a-28ffbc2b1763.png)

**Comment by squaremo** [comment]
http://www.squaremobius.net/amqp.node/channel_api.html#channel_assertExchange

**Comment by qing8888** [comment]
x-delayed-type' must be an existing exchange type

After i using delayed message :
```
          const exchange = queueName + "_Exchange";
          const exchangeType = "x-delayed-message"; 
          const routingKey = queueName + "_RoutingKey";
            await channel.assertExchange(exchange, exchangeType, {
              durable: true,
              "x-delayed-type": "direct",
            });
```

**Comment by cressie176** [comment]
What happens if you nest `x-delayed-type` inside and `arguments` document, i.e.

```
 await channel.assertExchange(exchange, exchangeType, {
  durable: true,
  arguments: {
    "x-delayed-type": "direct",
  }
});
```

**Comment by victorbadila** [comment]
Had the same question as the op. I tried @cressie176's suggestion above and it worked for me.
