### ISSUE TITLE
How to retry the message N times？

### ISSUE THREAD

**Issue by simuty** [squaremo/amqp.node#597]
if i set `num > 3` **channel.nack(msg, false, true)** then **Endless loop**.

API info: [nack(message: Message, allUpTo?: boolean, requeue?: boolean): void;]

```js
async funtion consumer {
        const connect = await amqp.connect(url);
        const channel = await connect.createChannel();
        await channel.assertExchange(exchange, exchangeType, { durable: true })
        const queueA = await channel.assertQueue(queueName);
        await channel.consume(queueA.queue, msg => {
            const num = msg.content.toString()
            if(Number(num) > 3) {
// success
                channel.ack(msg, false);
            } else {
// nack
                channel.nack(msg, false, true);
            }
        });
    }
```

if set  deadLetterExchange, `nack` will send msg to `deadLetterExchange`.

```js
const queueConsumer = await channel.assertQueue(queueName, {
        exclusive: true,
        deadLetterExchange: elx,
        deadLetterRoutingKey: elk,
  });
```

#### but how achieve:

1. if error => retry =>  if [retry num > 3] => deadLetterExchange 
OR
2. if error => retry => if success => ack(msg)

**thanks** 🙏

**Comment by cressie176** [comment]
There are a few ways to do this...

1. Use a quorum queue (requires RabbitMQ 3.8.0 or higher) and specify a [redelivery limit](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling)

1. Count message redeliveries in an external store (you need a unique way to identify the message if you do this)

1. Instead of nacking the message, re-publish it with a new header which counts the number of redeliveries, then acknowledge the original. This can lead to duplicate messages if you application crashes between the publish and the acknowledgment however

**Comment by simuty** [comment]
> There are a few ways to do this...
> 
> 1. Use a quorum queue (requires RabbitMQ 3.8.0 or higher) and specify a [redelivery limit](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling)
> 2. Count message redeliveries in an external store (you need a unique way to identify the message if you do this)
> 3. Instead of nacking the message, re-publish it with a new header which counts the number of redeliveries, then acknowledge the original. This can lead to duplicate messages if you application crashes between the publish and the acknowledgment however

thank you very much, I will try this

**Comment by simuty** [comment]
> There are a few ways to do this...
> 
>     1. Use a quorum queue (requires RabbitMQ 3.8.0 or higher) and specify a [redelivery limit](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling)
> 
>     2. Count message redeliveries in an external store (you need a unique way to identify the message if you do this)
> 
>     3. Instead of nacking the message, re-publish it with a new header which counts the number of redeliveries, then acknowledge the original. This can lead to duplicate messages if you application crashes between the publish and the acknowledgment however

i read [redelivery limit](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling), but i'm not sure use`delivery-limit` or `x-delivery-count`, so i set all, 
I hope channel consume 3 or 4 times, then end. 
but **not working  it will Endless loop.**

**would you please help, thank you very much**


```
It is possible to set a delivery limit for a queue using a policy argument, delivery-limit.

When a message has been returned more times than the limit the message will be dropped or dead-lettered (if a DLX is configured).
```



```bash
# version

rabbitmq: stable 3.8.9

"amqplib": "^0.6.0",
```



```js
// send.ts
(async function testConfirmChannel() {
    const url = `amqp://localhost`;
    const connect = await amqp.connect(url)
    let index = 0;
    await publish(`发送消息${index}`, connect);

    process.exit(0);
})();

async function publish(msg: string, connect: amqp.Connection) {
    const exchange = '6.delivery.exchange';
    const exchangeType = 'direct';
    const routingKey = '6.delivery.routingKey';

    const channel = await connect.createConfirmChannel();
    await channel.assertExchange(exchange, exchangeType, { durable: false })
    const content = JSON.stringify({ msg });
    channel.publish(exchange, routingKey, Buffer.from(content), {
        headers: {
            'x-delivery-count': 3,
            'delivery-limit': 4
        }
    }, (err, ok) => {
        if (err !== null) {
            console.log('--', err);
        } else {
            console.log('--', err, ok, content);
        }
    });
    await channel.waitForConfirms()
    await channel.close();
}

```

```js
// receive.ts
(async function receive(){
    const connect = await amqp.connect(url);
    const channel = await connect.createChannel();
    const exchange = '6.delivery.exchange';
    const exchangeType = 'direct';
    const routingKey = '6.delivery.routingKey';
    const routingQueue = '6.delivery.queue';

    await channel.assertExchange(exchange, exchangeType, { durable: false });
    const queueA = await channel.assertQueue(routingQueue);
    await channel.bindQueue(queueA.queue, exchange, routingKey);

    channel.consume(queueA.queue, msg => {

        console.log("receive: ", msg.content.toString())
// nack 
        channel.nack(msg, false, true);
        // channel.nackAll(false)
    });
    // await connect.close();
})();
```

**Comment by simuty** [comment]
i set **policy** argument, **delivery-limit**. but the consumer  still  endless loop. What am I missing?

Hope to help， thank you very much 


<img width="1015" alt="image" src="https://user-images.githubusercontent.com/9928645/102857802-0e2a3e80-4464-11eb-9ab3-d740fcb2eff9.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/9928645/102858036-87299600-4464-11eb-93b0-fba9bee43352.png">

**Comment by simuty** [comment]
Finally solved the problem --- [redelivery limit](https://www.rabbitmq.com/quorum-queues.html#poison-message-handling)

### The First Method

1. you need a **queue** 【type: quorum】
2. set **delivery-limit**

```js
const queueEX = await channel.assertQueue(queueExName, {
        exclusive: false,
        deadLetterExchange,
        deadLetterRoutingKey,
        arguments: {
            'x-queue-type': 'quorum',
            'x-delivery-limit': 3
        }
    });
```

### The Second Method

1. only set quorum type queue
2. [http://127.0.0.1:15672/#/policies](http://127.0.0.1:15672/#/policies) find **Add / update an operator policy**
3. add new policy;  add  `Delivery limit`

```js
const queueEX = await channel.assertQueue(queueExName, {
        exclusive: false,
        deadLetterExchange,
        deadLetterRoutingKey,
        arguments: {
            'x-queue-type': 'quorum',
        }
  });
```

I prefer The Second Method。

**Comment by simuty** [comment]
Resolved
