### ISSUE TITLE
Failed to connect  Expected ConnectionOpenOk; got <ConnectionClose channel:0>

### ISSUE THREAD

**Issue by jitenderchand1** [squaremo/amqp.node#602]
While trying to connect to rabbit MQ which is on a remote server. I am getting the following error. It is working fine when connecting to localhost Rabbit MQ. 

version 
`"amqplib": "^0.6.0"`

```
const CONN_URL = 'amqp://dev-development:password@rabbitmq-development-0:5171/development';
amqp.connect(CONN_URL, function (err, conn) {
    conn.createChannel(function (err, channel) {
        ch = channel;
    });
});
```

```
api_1    | [Node] Disconnected from rabbit MQ Error: Expected ConnectionOpenOk; got <ConnectionClose channel:0>
api_1    | [Node]     at /home/node/app/node_modules/amqplib/lib/connection.js:168:14
api_1    | [Node]     at /home/node/app/node_modules/amqplib/lib/connection.js:160:12
api_1    | [Node]     at Socket.recv (/home/node/app/node_modules/amqplib/lib/connection.js:499:12)
api_1    | [Node]     at Object.onceWrapper (events.js:421:28)
api_1    | [Node]     at Socket.emit (events.js:315:20)
api_1    | [Node]     at Socket.EventEmitter.emit (domain.js:467:12)
api_1    | [Node]     at emitReadable_ (internal/streams/readable.js:569:12)
api_1    | [Node]     at processTicksAndRejections (internal/process/task_queues.js:79:21)
```

Edit:

RabbitMQ is hosted on secure server. I used `amqps` as well but I got ` Disconnected from rabbit MQ Error: 140259317198152:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:` error.

**Comment by jitenderchand1** [comment]
by adding extra `/` in the connection string for the virtual host fixed this issue. 

From 
`'amqp://dev-development:password@rabbitmq-development-0:5171/development'`

to

`'amqp://dev-development:password@rabbitmq-development-0:5171//development'`

**Comment by forinda** [comment]
Add user to and login to the admin dashboard. After that, you have to allow the user you created to connect to your server. Navigate to the admin tab then on the permissions section set permissions to allow vhost

**Comment by nover** [comment]
Stumbled into this problem just now in an AWS environment (Fargate + Aws MQ with RabbitMQ).

In our case it was because the created user did not have access (permissions) to use the `vhost` - in our case the default `/`.
