### ISSUE TITLE
High number of consumers

### ISSUE THREAD

**Issue by guicuton** [squaremo/amqp.node#603]
Hi guys!

I do not know if it's normal, but with only 10 active queues i'm getting something close to 40k of consumers...
Each queue is consumed by one worker that create 1 connection/channel per each
![image](https://user-images.githubusercontent.com/37594431/106360315-8f43e380-62f6-11eb-8878-cd93d0691a28.png)

Here is my code:

***Connection function*** 
```javascript
const amqpConnect = async () => {

  let conn = await amqp.connect(`amqp://${AMQP_USER}:${AMQP_PASS}@${AMQP_HOST}:${AMQP_PORT}/${AMQP_VHOST}?heartbeat=${AMQP_BEAT}`)

  let channel = await conn.createChannel()

  //Connection error events
  conn.on("error", function(err) {
    if (err.message !== "Connection closing") {
      console.error("[AMQP] conn error", err.message);
    }
  });

  conn.on("close", function() {
    console.error("[AMQP] reconnecting");
    return setTimeout(connect, 10000);
  })

  //Channel error events
  channel.on("error", function(err) {
    console.error("[AMQP] channel error", err.message);
  })

  channel.on("close", function() {
    console.log("[AMQP] channel closed");
  })

  return channel
}

const connect = amqpConnect()
```

***Consumer function*** 
```javascript 
/**
  * Consumer specified queue
  * @param {string} queueName - queue name to be consumed
  * @param {int} prefetch - tps to be used per once
  * @param {json} calback - json string with message received from queue
  * @argument {object} conn - connection link to queue manager
*/
const consumeQueue = async (queueName, prefetch, callback, conn = connect) => {

  try {

    let channel = await conn
    let bind = await channel.bindQueue(queueName, AMQP_EXCHANGE_DIRECT)

    channel.prefetch(prefetch)
    channel.consume(queueName, callback, {noAck:false})

  } catch (e) {

    console.error('Fail on consume queue. %s', e)

  }

}
```

***My worker app*** 
```javascript 

//Messaqges structure
var messages = []
var acks = []

/**
  * Get messages and send batch through webhook callback endpoint
  * @param {array} messages - Array with callback status
  * @param {array<object>} acks - Array with messages object to be ack
  * @argument {function} callback
*/
var requestWebhook = (messages, acks, callback) => {

  try {

    if(messages.length > 0 && acks.length > 0) {

      let api = new Webhooks(DLR_ENDPOINT, 'DLR/MO. Volume: '+messages.length, acks)
      api.sendMessage(messages, true)

      callback(true)

    }

  } catch (err) {

    console.error('Error. %s', err)
    setTimeout(getMessages, parseInt(CALLBACK_TPS_TIME_30SEC))

  }

}

/**
  * Recursive loop to find new messages on queue
*/
setTimeout(getMessages = () => {

  //Queue consumer
  amqp.consumeQueue(DLR_QUEUE, parseInt(CALLBACK_TPS_400), (message) => {

    let messageData = JSON.parse(message.content.toString())

    messages.push(messageData)
    acks.push(message)

  })

  //Only use callback function if exist some message
  if(messages.length > 0 && acks.length > 0) {

    async.eachLimit(messages, 1, function(item, callback) {

      requestWebhook(messages, acks, (response) => {

        if(response) {

          //Clean array if response goes well
          messages = []
          acks = []

          //Restart queue consumer
          setTimeout(getMessages, parseInt(CALLBACK_TPS_TIME_10SEC))

        }

      })

    }, (err) => {
      if(err) {
        console.error('Error %s', err)
        setTimeout(getMessages, parseInt(CALLBACK_TPS_TIME_30SEC))
      }
    })

  } else {

    setTimeout(getMessages, parseInt(CALLBACK_TPS_TIME_10SEC))

  }

})
```

What my worker do is open the consumer function each 10 seconds, limited to 400 messages, that will be pushed into an array to be sent it over through POST request on my endpoint.

I believe that my "error" is on my worker. 
Someone can help me to find this "bug"?!

**Comment by cressie176** [comment]
Hi @guicuton,

I suspect the bug is to do with your use of `channel.consume`. 

Consume creates a consumer that will continue receiving messages until [cancelled](https://www.squaremobius.net/amqp.node/channel_api.html#channel_cancel). I don't see you cancelling the consumer at any point, so suspect you are repeatedly consuming each time your timeout is run. 

You might also want to consider using [channel.get](https://www.squaremobius.net/amqp.node/channel_api.html#channel_get), which will only fetch a single message.

You should be able to get either approach to work though.

**Comment by guicuton** [comment]
Hi  @cressie176 

Always helping a lot! 😄

Looking with more attention to the docs, i've saw that consumerTag - if not provided - the rabbitmq randonly creates one.

So to avoid this, i setted my custom tag and always call `channel.cancel` after each timeout.

```javascript
const consumeQueue = async (queueName, prefetch, callback, conn = connect) => {

  try {

    let channel = await conn
    let bind = await channel.bindQueue(queueName, AMQP_EXCHANGE_DIRECT)

    channel.prefetch(prefetch)
    channel.consume(queueName, callback, {noAck:false, consumerTag:queueName})
    channel.cancel(queueName)

  } catch (e) {
    console.error('Fail on consume queue. %s', e)
  }

}
```

**Comment by cressie176** [comment]
Hi @guicuton,

I might be missing something, but I think your approach still has a few holes. For example, you appear to be cancelling your consumer immediately after calling consume. You also appear to be connecting each time you call consume, which would be inefficient), but I don't see you closing that connection anywhere.

Thinking back to your originally issue, I remember your goal was to:
1. consume a batch of messages from a long queue, 
2. post the batch to an external api
3. repeat after a short period

I would approach this in the following way...

1. Setup
    1.1. Connect to RabbitMQ, set error handlers etc
    1.2. Create channel, set prefetch to 1, and set error handlers etc
    1.3. Assert and bind the queue
2. const messages = consumeMessages({ channel, batchSize, timeout });
    2.1 Create the consumer (the amqplib api yields the consumer tag)
    2.2. Push messages onto a local array until the size === 100, or the timeout has passed
    2.3. Cancel the consumer (using the provided tag)
    2.4. Resolve the array of messages
3. Post messages to the api
4. Tidy up
    4.1. Acknowledge the messages
    4.2. Close the channel   
    4.3. Close the connection
5. Repeat from step 1 after a short interval

- Setting the prefetch to 1 is important. If you omit this, multiple messages will be delivered concurrently, and you may still be processing them after resolving the array of messages (2.4). These could continue to be pushed onto the array right up to the point where you close the channel and depending on your logic cause you to cancel the consumer twice, resulting in a channel error.

- Depending on the size of your repeat interval I would adapter the above to setup outside of the loop, or if I lost the connection or channel.

- Almost every amqplib command is asynchronous, so you would need to `await` each call, including consumeMessages (2)
