### ISSUE TITLE
Question: vhost management API

### ISSUE THREAD

**Issue by wojciechbator** [squaremo/amqp.node#611]
It is specified in [RabbitMQ official docs](https://www.rabbitmq.com/vhosts.html) that one creates new virtual host using either `rabbitmqctl` or HTTP API. I'm unable to find the API for managing the vhosts so I assume these are Rabbit features and beyond the scope of this library. Is it the common pattern to use rabbit HTTP API to manage vhosts directly or there are better ways to do it?

**Comment by cressie176** [comment]
Hi @wojciechbator, there's nothing in the amqp protocol for creating vhosts, so there's no way to do it with this library. I'm afraid rabbitmqctl, the HTTP API or a configuration management tool are the way to go.

**Comment by wojciechbator** [comment]
> Hi @wojciechbator, there's nothing in the amqp protocol for creating vhosts, so there's no way to do it with this library. I'm afraid rabbitmqctl, the HTTP API or a configuration management tool are the way to go.

Thanks! I thought so and it's perfectly understandable. This library does AMQP part really great and that's OK.
