### ISSUE TITLE
amqplib is flooding the queue with messages

### ISSUE THREAD

**Issue by kamdhenu** [squaremo/amqp.node#612]
Hello,

I'm trying to create a basic micro in service using RabbitMQ, mqtt and amqplib, where:

1. MQTT client will send a request to RabbitMQ
2. And an API will process this request and send a response back to RabbitMQ
3. RabbitMQ will then push the response to the MQTT using a routing key

My mqtt client looks a below:

```
const mqtt = require('mqtt');

const client = mqtt.connect('mqtt://localhost:1883', {
  username: 'test-pub',
  password: 'test-pub',
});

client.on('connect', function () {
  client.subscribe('123', function (err) {
    if (err) {
      console.log(err);
    } else {
      client.publish('123', 'Hello from mqtt');
    }
  });

  client.on('message', function (topic, message, packet) {
    console.log(message.toString());
  });
});
```
And my amqplib client is as below:
```
const amqplib = require('amqplib');
(async () => {
  const client = await amqplib.connect('amqp://test-sub:test-sub@127.0.0.1:5672');

  const connection = await client.createChannel();

  await connection.assertQueue('requests');
  await connection.bindQueue('requests', 'amq.topic', '*');
  connection.consume('requests', (message) => {
    const response = message.content.toString().toUpperCase();
    console.log(`Sending response: ${response}`);

    connection.publish(
      'amq.topic',
      message.fields.routingKey,
      Buffer.from(response)
    );

    connection.ack(message);
  });
})();
```
Now when I test this code, the `requests` queue is getting flooded with messages published by amqplib.

I'm new to this topic and I don't have any clue what is going wrong, please help.

Thanks...

**Comment by cressie176** [comment]
Hi @kamdhenu,

I haven't any experience of mqtt, so apologies if the following is obviously wrong, or nonsensical. 

From reading the above, my understanding is that...

1. the amqp client is listening to all messages delivered to the requests queue
2. all messages from the 'amq.topic' are routed to the requests queue
3. the amqp client publishes the response to the 'amq.topic'

This sounds like you have an infinite loop, where the amqp client receives a copy of the same message it publishes, and so may publish another message in response.  I assume that those messages are also being delivered to the mqtt client, hence it's being flooded.

My guess is you will need to use a different topic for either the request or the response, or use routing keys to be more selective about what either the amqp client or mqtt client receive.

**Comment by kamdhenu** [comment]
Hi @cressie176 

Yes, your understanding is right and as you suggested I also tried the routing key approach but it didn't work. so finally I ditched MQTT and implemented AMQP on both end, so now it works.

So as my problem has nothing to do with amqplib closing this issues...
