### ISSUE TITLE
reconnect by setTimeout is the best practice?

### ISSUE THREAD

**Issue by pigLoveRabbit520** [squaremo/amqp.node#614]
here is my code:
```
const amqp = require('amqplib');

class Rabbit {
    /**  @type {Object} */
    _config;
    /**  @type {amqp.Connection} */
    _client;
    retryInterval = 5000; 

    constructor(config) {
      this._config = config;
      this.connect();
    }

    connect() {
      this.getMQConnection().then((conn) => {
        this._client = conn;
        console.log("[AMQP] connected");
        this._client.on("error", (err) =>
        {
          console.error("[AMQP] conn error", err.message);
        });
        this._client.on("close", (err) =>
        {
          console.info("[AMQP] reconnecting");
          setTimeout(this.connect.bind(this), this.retryInterval);
        });
      }).catch(err => {
        console.error("[AMQP] connecting failed", err.message);
        setTimeout(this.connect.bind(this), this.retryInterval);
      });
    }

    async getMQConnection() {
      return await amqp.connect({
        protocol: 'amqp',
        hostname: this._config.host,
        port: this._config.port,
        username: this._config.user,
        password: this._config.pass,
        locale: 'en_US',
        frameMax: 0,
        heartbeat: this._config.heartbeat, // 心跳
        vhost: this._config.vhost,
      });
    }

    async sendToQueue(queueName, msg) {
      const channel = await this._client.createChannel();
      await channel.sendToQueue(queueName, Buffer.from(msg, 'utf-8'), {
        persistent: true, 
        mandatory: true,
      });
      await channel.close();
    }
}

module.exports = Rabbit;
```
some people say `setTimeout` is not a good method? any advice?

**Comment by xamgore** [comment]
Why do you prefer implementing reconnection by yourself instead of using `amqp-connection-manager` or `rascal`?

**Comment by salamander-mh** [comment]
@xamgore  because I don't want to require another package and modify my code.

**Comment by xamgore** [comment]
I recommend you to look through `amqp-connection-manager` sources then.

**Comment by cressie176** [comment]
Hi @salamander-mh,

What you've got is reasonable but has the following drawbacks...

1. You are waiting 5 seconds before attempting to reconnect. Instead maybe consider an exponential (but capped) retry interval starting from a very low number of milliseconds.
2. You are creating a new channel for each publish. This is slower than keeping the channel open, but could still be fast enough. If you keep the channel open, you will need similar retry logic for channel errors.
3. Your approach doesn't support consumers, which would need to re-consume following a connection or channel error (but possibly you don't need to)

**Comment by salamander-mh** [comment]
@cressie176
An exponential (but capped) retry interval is reasonable, and I know I have to wrap a  consume method.  
By the way, is [rascal](https://github.com/guidesmiths/rascal) stable for production?

**Comment by cressie176** [comment]
> By the way, is rascal stable for production?

Yes, although not great if you need to do supper high volumes (it's constrained because the architecture doesn't allow you to share channels), and doesn't support RPC.

**Comment by xdolnak** [comment]
> Hi @salamander-mh,
> 
> What you've got is reasonable but has the following drawbacks...
> 
> 1. You are waiting 5 seconds before attempting to reconnect. Instead maybe consider an exponential (but capped) retry interval starting from a very low number of milliseconds.
> 2. You are creating a new channel for each publish. This is slower than keeping the channel open, but could still be fast enough. If you keep the channel open, you will need similar retry logic for channel errors.
> 3. Your approach doesn't support consumers, which would need to re-consume following a connection or channel error (but possibly you don't need to)

How do you solve point 2? I am working on a similar solution, because refreshing SSL certificate on rabbitMQ drops our queues. Is it possible to reopen an existing channel? I cannot keep it open because rabbitMQ need to be restarted, so it does not run for a short period of time.

**Comment by cressie176** [comment]
Hi @xdolnak,

It's not possible to reopen an existing channel, but what you could do is keep the existing channel open and only reconnect / re-establish when the connection is dropped.
