### ISSUE TITLE
Can't get a message from a queue.

### ISSUE THREAD

**Issue by qing8888** [squaremo/amqp.node#617]
```
    const msgInQ = await this.channel.get(queueName, {
      noAck: true,
    });
    console.log("msgInQ", msgInQ);
```

**Comment by cressie176** [comment]
Hi @qing8888, 

Can you describe what's happening? An error, is `msgInQ` false or something else?

**Comment by qing8888** [comment]
I got ```false``` all the time.I want to get a message from a queue and delete it.

**Comment by qing8888** [comment]
```
      await channel.publish(exchange, routingKey, msgBuffer, {
        persistent: true,
        messageId,
        headers: {
          "x-delay": expiration,
        },
      });
```

**Comment by cressie176** [comment]
> Ask a queue for a message, as an RPC. This will be resolved with either false, if there is no message to be had (the queue has no messages ready), or a message in the same shape as detailed in #consume.

Are you sure the message was delivered to the correct queue? Worth checking using the management ui if you have it installed.
Also how big is the delay? The message won't be routed to the exchange until it expires.

**Comment by qing8888** [comment]
Is this related to the delay? A user who has placed an order and has not paid for 30 minutes will cancel the order. But if he pays within 30 minutes, the system doesn't need to cancel the order. So I need to delete the cancellation message.

**Comment by cressie176** [comment]
I believe the x-delay header [delays the routing of the message](https://www.rabbitmq.com/blog/2015/04/16/scheduling-messages-with-rabbitmq/#:~:text=To%20delay%20a%20message%20a,queues%20or%20to%20other%20exchanges.), so it won't have been published to the queue.

> To delay a message a user must publish the message with the special header called x-delay which takes an integer representing the number of milliseconds the message should be delayed by RabbitMQ. It's worth noting that here delay means: delay message routing to queues or to other exchanges.

**Comment by qing8888** [comment]
Thank you very much. Is there any other solution to realize my idea?

**Comment by cressie176** [comment]
1. Publish the message with the 30 minute delay
2. Consume from the queue
3. When the message arrives check to see whether the customer has paid

**Comment by qing8888** [comment]
I have used ```channel.consume``` when I created the channel. If I change this, will it affect other messages?

**Comment by qing8888** [comment]
I understand your idea, and I am using this scheme now. But I want to use a more elegant solution

**Comment by qing8888** [comment]
If the message is delayed, can I cancel the ```publish```? If not a delayed message. I get it and I delete(```ack```) it?

**Comment by qing8888** [comment]
Could i delete or ```ack`` the delayed message before it is be routed to the exchange?

**Comment by cressie176** [comment]
> I have used channel.consume when I created the channel. If I change this, will it affect other messages?

I'm not sure what you mean.

[channel.consume](https://www.squaremobius.net/amqp.node/channel_api.html#channel_consume) will consume messages from a queue indefinitely (watch out though - you will get a null message when the broker shuts down). What other messages are you worries about affecting?

> If the message is delayed, can I cancel the publish? If not a delayed message. I get it and I delete(ack) it?
> Could i delete or ack the delayed message before it is be routed to the exchange?

No. The publish succeeded - the message was sent to the broker, and stored using mnesia.

**Comment by qing8888** [comment]
```
createChannel(
    channel.consume ()=>{
        console.log('111');
    }
)

channel.publish(
    1 delayed message (30min)
)

channel.publish(
    2 delayed message (40min)
)

channel.consume ()=>{
    console.log('222');
}

1 console.log('111') or console.log('222')
```
I hope you understand what I mean.

**Comment by qing8888** [comment]
After I ```publish`` a message, I can get the messageId. It is nice if i can delete(or cancel or ack) it by messageId.

**Comment by cressie176** [comment]
Unfortunately queues don't work like that. They operate on a First In First Out (FIFO) basis - you can't selectively retrieve or delete a specific message

**Comment by cressie176** [comment]
You should only call channel.consume once. RabbitMQ will execute the supplied callback whenever a message is delivered.

**Comment by xamgore** [comment]
> Is this related to the delay? A user who has placed an order and has not paid for 30 minutes will cancel the order. But if he pays within 30 minutes, the system doesn't need to cancel the order. So I need to delete the cancellation message.

You may set `x-message-ttl: 30min` to each message in the queue, so the broker will drop outdated messages automatically. But that will require a RabbitMQ extension to be installed.

If you are ok with non-paid messages being in the queue for more than 30 minutes, then just do the following:
* send a message to the queue with the attached order and creation date
* the consumer receives a message:
   * if the message's lifetime is less than 30 min, put it back (=don't `ack`/`nack`), sleep
   * else, if the order wasn't paid, `nack` it
   * else, continue processing, `ack` the message

**Comment by cressie176** [comment]
> You may set x-message-ttl: 30min

> * send a message to the queue with the attached order and creation date
> * the consumer receives a message:
>    * if the message's lifetime is less than 30 min, put it back (=don't `ack`/`nack`), sleep
>    * else, if the order wasn't paid, `nack` it
>    * else, continue processing, `ack` the message

I'm not sure either of these proposals will help...

x-message-ttl automatically nacks a message after the specified timeout. This means the message would be immediately available on the queue, and vanish after 30 minutes. This could mean that an unpaid order might never be cancelled.

I also don't see how the second proposal helps. Reading the message and putting it back (the cleanest way I know of is using nack + requeue) if the message order hasn't been paid, then sleeping, is more effort than using x-delay.

**Comment by xamgore** [comment]
<details>

![image](https://user-images.githubusercontent.com/4586392/114437314-0c30ea80-9bcf-11eb-8be6-e7fdea138d12.png)

</details>

qing8888 hasn't actually shared a description of the whole system. I imagine it being more like this (see details). Orders are automatically canceled after being dropped from the queue. Moreover: they 'start existence' only when the payment is done.

> Reading the message and putting it back (the cleanest way I know of is using nack + requeue)

Exactly, `noAutoAck` and a manual `nack` is what I have meant. Thank you for the correction. I have checked `x-delay`, it's indeed a shortcut, I would prefer it.

**Comment by qing8888** [comment]
@xamgore Thanks a lot.And i try may best to solve this problem.
