### ISSUE TITLE
Listener idles out and stops listening.

### ISSUE THREAD

**Issue by ekumahost** [squaremo/amqp.node#619]
Hello guys, what could be the cause of this and how do i fix..
listener after app is started works for a while and then stops. messages are queued in the dashboard (... no consumers ... show in the queue consumers section) and not consumed again until i restart the node app.
my script below.

        const amqp = require('amqplib/callback_api');
        const MyConsumers = require('../rabbit/lestener_');

    
        const opt = { credentials: require('amqplib').credentials.plain(process.env.RABBIT_USERNAME, 
        process.env.RABBIT_PASSWORD), clientProperties: {connection_name: "newListerner"} };

        await amqp.connect(process.env.RABBIT_SERVER, opt, async function (error0, connection) {
            if (error0) {
                console.log(error0)
                //throw error0;
            }

            connection.on('error', function(handle){
               // reject(handle);

            });

         
            await MyConsumers.messageListener(connection);
    

        });// connection ends..

**Comment by xamgore** [comment]
There may be connection issues, the package doesn't provide the reconnect-on-fail mechanism itself. Though, there are [amqp-connection-manager](https://github.com/jwalton/node-amqp-connection-manager) and [rascal](https://github.com/guidesmiths/rascal) that do this for you.

```diff
        connection.on('error', function(handle) {
           // reject(handle);
+          console.error({ error: handle })
        });
```
