### ISSUE TITLE
Allow Node.js v16

### ISSUE THREAD

**Issue by vitalets** [squaremo/amqp.node#622]
Node.js v16 is just released.
But I can't use this library because of restriction in `package.json`:
```json
  "engines": {
    "node": ">=0.8 <=15"
  },
```

**Comment by xamgore** [comment]
There is a [PR](https://github.com/squaremo/amqp.node/pull/615) for that.

**Comment by xamgore** [comment]
@vitalets the PR got merged and a new 0.7.1 version released! Could you please test it and close the issue?

**Comment by marvinroger** [comment]
It’s merged but not released yet! 0.7.1 is 2 months old.

**Comment by marvinroger** [comment]
Released in 0.8.0 😉

**Comment by jimmywarting** [comment]
can be closed now
