### ISSUE TITLE
AMQP 1.0 Support

### ISSUE THREAD

**Issue by cleancoderocker** [squaremo/amqp.node#63]
Do you plan to add support for AMQP 1.0? I've tried using amqp.node with the Microsoft Azure Message Bus, but I got an error ("[Error: Frame size exceeds frame max]"). After some research I noticed that Azure currently only support AMQP 1.0 (see http://azure.microsoft.com/de-de/documentation/articles/service-bus-amqp-overview/), most likely this is the reason for the error.

Or does somebody know another module, that supports AMQP 1.0? I know that there is the Azure SDK for Node.js, but as far as I know this can be used _only_ with Azure. In one of my current projects we are looking for a module that supports Azure but does not depend on Azure.

So if amqp.node would add support for AMQP 1.0 I think this module would be the best choice.

**Comment by mbroadst** [comment]
For future reference, https://github.com/noodlefrenzy/node-amqp10 is probably your best bet at the moment.

**Comment by GuyHarwood** [comment]
> For future reference, https://github.com/noodlefrenzy/node-amqp10 is probably your best bet at the moment.

that's what i am currently using, and it works well against Azure Service Bus and Rabbit MQ (providing you enable AMQP 1.0 core plugin).

However, i believe that the `amqp10` package is no longer maintained, which is slightly worrying.

Any recommendations welcomed

**Comment by jayarjo** [comment]
Recommendations still welcomed.

**Comment by cressie176** [comment]
The node-amqp readme suggests https://github.com/amqp/rhea.
