### ISSUE TITLE
write ECONNRESET

### ISSUE THREAD

**Issue by einsqing** [squaremo/amqp.node#632]
write ECONNRESET，This problem is often encountered when the network environment is unstable，Use amqp-connection-manager to automatically reconnect

**Comment by cressie176** [comment]
Hi @einsqing,
Thanks for your suggestion. Similar requests have already been made so I'm closing as a duplicate.

- https://github.com/squaremo/amqp.node/issues/163
- https://github.com/squaremo/amqp.node/issues/25
