### ISSUE TITLE
is nack a Promise?

### ISSUE THREAD

**Issue by eugen-klm** [squaremo/amqp.node#650]
Hi there,
I have one small question: here is an implementation of nack-method:
```
C.nack = function(message, allUpTo, requeue) {
  this.sendImmediately(
    defs.BasicNack,
    Args.nack(message.fields.deliveryTag, allUpTo, requeue));
};
```
Seems, _nack_ in not a Promise (coz we don't return anything), and I can't  await it, right? or I'm wrong?
Thanks in advance for any help

**Comment by cressie176** [comment]
Hi @eugen-klm,

You are correct, neither channel.ack nor channel.nack return a promise (or accept a callback)
