### ISSUE TITLE
how do prevent connect two consumer to queue?

### ISSUE THREAD

**Issue by MohMehrnia** [squaremo/amqp.node#655]
how do prevent connect two consumer to queue?

**Comment by Uzlopak** [comment]
https://www.rabbitmq.com/queues.html#exclusive-queues

**Comment by MohMehrnia** [comment]
Is not eny solution for control in app without used thsi queue type

**Comment by Uzlopak** [comment]
Maybe it is not even the correct solution. If I remember correctly there is an option to make the queue consume by multiple consumers, but only the first consumer will get messages.

Maybe StackOverflow is better place for your question.
