### ISSUE TITLE
Async consumer function with channel.consume

### ISSUE THREAD

**Issue by akwodkiewicz** [squaremo/amqp.node#662]
Is it possible to **properly** use a _native_ `async` function inside the `channel.consume` call?

I see that the `callback` function provided to `registerConsumer` (via public `consume` method) is not awaited in `dispatchMessage`.

https://github.com/squaremo/amqp.node/blob/e3e10167d3f498f632a5a50dc7fac62b314400c8/lib/channel_model.js#L165-L177
https://github.com/squaremo/amqp.node/blob/e3e10167d3f498f632a5a50dc7fac62b314400c8/lib/channel.js#L480-L485

**Comment by eramosr16** [comment]
I'm having the same issue, this is a must

**Comment by cressie176** [comment]
Hi @akwodkiewicz,

Sorry for what I suspect will sound like a dumb question. Can you explain why the consumer callback would ever need to be awaited please?

Thanks

**Comment by akwodkiewicz** [comment]
Hi @cressie176, sure thing. If the callback is an async function and you don't await it, you create a dangling Promise. When it throws an exception inside (=rejects), this might lead to unexpected behaviour, which is reported by Node as `UnhandledPromiseRejectionWarning`.

**Comment by cressie176** [comment]
Hi @akwodkiewicz,

Thanks for the clarification. I'm sorry, but I still don't understand why the consumer callback would need to be an async function or promise to start with though. Messages will be delivered to the consumer as fast as possible (or until a prefetch is reached), irrespective of whether the consumer callback is a regular function or asynchronous one.

To put it another way, I wouldn't expect other libraries to await any genuine callbacks just in case a developer accidentally supplied an async function, but maybe I'm still missing something?

**Comment by akwodkiewicz** [comment]
Why would you assume that the callback can be only a synchronous function? What about API calls or database queries? Are you suggesting that message consumers' callbacks cannot contain such calls?

**Comment by cressie176** [comment]
Hi @akwodkiewicz,

I'm not assuming the the callback cannot contain asynchronous code, absolutely you might want to make API calls or database queries, however doing so in an awaited asynchronous function, will not prevent subsequent messages being delivered concurrently. Maybe it's more easily explained with an example...

```js
function onMessage(msg) {
  makeApiRequest1()
    .then(() => {
      makeApiRequest2();
    }).catch((err) => {
      handleError(err);
    })
}
```

In the above example a synchronous function, contains two sequential, asynchronous API requests. You could also have used callbacks...

```js
function onMessage(msg) {
  makeApiRequest1((err) => {
    if (err) return handleError(err);
    makeApiRequest2((err) => {
      if (err) return handleError(err);
    })
  })
}
```

Or async/await with an IIFE

```js
function onMessage(msg) {
  (async () => {
    try {
      await makeApiRequest1();
      await makeApiRequest2();
    } catch (err) {
      handleError(err);
    }
  })();
}
```

The point is that because amqplib/RabbitMQ will continue delivering messages as they become available, it would be misleading to make the onMessage function asynchronous whether using an async function, returning a promise or accepting a callback. There is no need to wait for the onMessage function to finish.

Many people (including myself), might not be overly happy with the IIFE syntax, but I still wouldn't advocate changing the amqplib consumer callback API to tolerate an unnecessary async function, as it would give the incorrect impression that waiting for the function to complete was somehow important. I don't think it would help regarding rejections, as there's no way that amqplib would know what to do with the rejection. Should it ack the message? nack it? nack it with requeue? This decision is the responsibility of the consumer, and therefore consumers must be written in a robust way.

**Comment by akwodkiewicz** [comment]
Thank you @cressie176 for this thorough comment, that was very informative. I now agree with the design decision. I hope that other devs will find it helpful as well.

**Comment by MaratKagyu** [comment]
With all due respect [cressie176](https://github.com/cressie176), it doesn't make any sense. What if I have millions of messages in the queue? Should the app do all these Api requests simultaneously (rhetorical question)? Or do I need to implement a queue in my app to make these requests a few at a time? And if so, why use RabbitMQ in the first place?
The pure idea of having queues is to make them work asynchronously. Which means, a worker consumes a message, then does what it does, and reads another one whenever the previous task is finished.

**Comment by cressie176** [comment]
Hi @MaratKagyu,

You've fundamentally misunderstood how amqp and RabbitMQ work. Concurrency / throttling is handled via explicit message acknowledgements and the prefetch mechanism, not by whether your code is synchronous or asynchronous.

i.e. If you set the prefetch to 10, RabbitMQ will only deliver messages to the consumer while there are 10 or fewer unacknowledged messages. Once there are 10 unacknowledged messages, delivery will be paused. When you acknowledge a message, delivery will be resumed until there are 10 unacknowledged messages again.

**Comment by MaratKagyu** [comment]
Thank you, [cressie176](https://github.com/cressie176)
My bad, I didn't know about prefetch, and somehow missed it after hours or googleing.
Adding `await channel.prefetch(1)` completely resolved my problem. Thank you!

**Comment by cressie176** [comment]
@MaratKagyu 

There are so many features with RabbitMQ, it's almost impossible to know about them all. I highly recommend https://www.cloudamqp.com/rabbitmq_ebook.html as a good starting point.

**Comment by Cuhadari-Deniz** [comment]
Hey I just started learning RabbitMQ and ran into this issue.
I've set prefetch to 1 but my worker still receives messages before it finishes processing them.
Is RabbitMQ not the right tool to process a queue one element at a time or is my code flawed?

```typescript
connection.createChannel(async (err, channel) => {
    if (err) {
      console.error(err);
      return;
    }

    channel.assertQueue(queueName, { durable: true });
    channel.prefetch(1);
    console.log(
      `[*] Waiting for messages in ${queueName}. To exit press CTRL+C`
    );

    channel.consume(
      queueName,
      async (msg) => {
        if (!msg) {
          console.log("No message received");
          return;
        }

        // each '.' in the message represents 1 second of work
        var secs = msg.content.toString().split(".").length - 1;

        console.log(" [x] Received %s", msg.content.toString());
        // sleep for n seconds
        await new Promise((resolve) => {
          setTimeout(resolve, secs * 1000);
        });
        console.log(` [x] Done processing ${msg.content.toString()}`);
      },
      {
        noAck: true,
      }
    );
  });
```

Messages sent:
```bash
First message.
Second message..
Third message...
Fourth message....
Fifth message.....
```

Console log of worker:
```bash
[*] Waiting for messages in task_queue. To exit press CTRL+C
 [x] Received First message.
 [x] Received Second message..
 [x] Done processing First message.
 [x] Received Third message...
 [x] Received Fourth message....
 [x] Done processing Second message..
 [x] Received Fifth message.....
 [x] Done processing Third message...
 [x] Done processing Fourth message....
 [x] Done processing Fifth message.....
```

**Comment by Cuhadari-Deniz** [comment]
@cressie176 Thank you!
After removing `{ noAck: true }` and adding `channel.ack(msg);` at the end of my consumer function it works.
