### ISSUE TITLE
How to process messages consequently with async consumer handler function?

### ISSUE THREAD

**Issue by romiras** [squaremo/amqp.node#663]
I'm a beginner in Node.js and in sample code below trying to pull and process messages one by one. So at first I published 3 messages via RabbitMQ UI dashboard: `a1`, `a2`, `a3`, then executed a Node.js consumer in terminal. I expected to see these messages processed one by one but instead this I see they are processed concurrently without awaiting before moving to next message. Am I doing something wrong or it's working this way by design?

It could be issue to process messages under memory constraints since currently we're pulling all messages from queue and trying to process them all at once.
Please correct me if I'm wrong.

``` 
[*] Waiting for messages on queue 'foo'. To exit press CTRL+C.
src/main.ts:31
 [x] Received a1
src/main.ts:40
Processing body: a1
src/main.ts:13
 [x] Received a2
src/main.ts:40
Processing body: a2
src/main.ts:13
 [x] Received a3
src/main.ts:40
Processing body: a3
src/main.ts:13
End processing body: a1
src/main.ts:15
End processing body: a2
src/main.ts:15
End processing body: a3
```

```typescript
import * as lib from 'amqplib';

const amqpUrl = process.env.AMQP_URL || 'amqp://127.0.0.1:5672';
const queue = 'foo';

const sleep = time => {
	return new Promise(resolve => {
		setTimeout(resolve, time);
	});
};

async function callback(body: string) {
	console.log('Processing body:', body);
	await sleep(1000);
	console.log('End processing body:', body);

	return Promise.resolve();
}

(async () => {
	let conn: lib.Connection;
	let channel: lib.Channel;

	try {
		conn = await lib.connect(amqpUrl);
		channel = await conn.createChannel();
	} catch (err) {
		console.error(err);
	}

	console.log(` [*] Waiting for messages on queue '${queue}'. To exit press CTRL+C.`);
	await channel.consume(
		queue,
		async (msg: lib.ConsumeMessage) => {
			if (msg === null) {
				return;
			}

			const body = msg.content.toString();
			console.log(` [x] Received ${body}`);

			try {
				await callback(body);
			} catch (error) {
				console.error(error);
				return channel.nack(msg);
			}
			return channel.ack(msg);
		},
		{ noAck: false },
	);
})();
```

**Comment by romiras** [comment]
I've added `await channel.prefetch(1);` and this solved my issue:

```typescript
	try {
		conn = await lib.connect(amqpUrl);
		channel = await conn.createChannel();
		await channel.prefetch(1); // 1 is a number of messages we want to be processed concurrently.
	} catch (err) {
		console.error(err);
	}
```

**Comment by squaremo** [comment]
There's two things worth noting here. One is `prefetch`, which means "only send this many messages before waiting for acks". Setting it to `1` means RabbitMQ will wait for an ack for each message for sending another.
The other is that you have made the callback `async`, which means that it returns control to the channel without waiting for anything (i.e., the sleep) to happen. If you just put the sleep directly in the consume callback, without making any of it async, you would see what you expect -- the three messages processed, with a pause in-between.

**Comment by romiras** [comment]
@squaremo 
I have await in `await callback(body);` and then `return channel.ack(msg);` . Is it not enough to wait for end of processing of `callback` then 'ack'?
