### ISSUE TITLE
Error: Cannot find module './defs'

### ISSUE THREAD

**Issue by ctavan** [squaremo/amqp.node#69]
When trying to use `0.2.0` I get:

```
module.js:340
    throw err;
          ^
Error: Cannot find module './defs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path/to/project/node_modules/amqplib/lib/connection.js:7:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

And there is indeed no `lib/defs.js`...

**Comment by ericnelson1** [comment]
FWIW - I have the same issue.  We are referencing ^0.5.3 and our deploys are failing with the "cannot find module defs" error.  Looks like 0.5.4 was pushed a couple hours ago.  Fixing to 0.5.3 for now.

**Comment by vncdias** [comment]
Same related from @mukaportes and @ericnelson1 here. Is there some advice to follow?

**Comment by mukaportes** [comment]
> Same related from @mukaportes and @ericnelson1 here. Is there some advice to follow?

We've temporarily added the package to our applications package.json with the version fixed to 0.5.3, the latest released. Even if it's not a direct dependency of the applications, it fixes the bug for now.

**Comment by OmegaPrimeZ3** [comment]
@mukaportes Attempted your solution but did not correct the issue, I believe its due to other packages we use also using it cannot lock down the version within their packages.

**Comment by jaredwa** [comment]
0.5.3 downgrade worked for us - thanks @mukaportes!

**Comment by smbassett** [comment]
I experienced the same issue. The solution by mukaportes fixed the issue - thanks!

**Comment by tjkusnadi** [comment]
having sama issue too, lock on 0.5.3 seems working for me

**Comment by mercteil** [comment]
Can confirm 0.5.4 update seems to carry a bug
`Error: Cannot find module './defs'`

**Comment by marcopaps** [comment]
This is an issue on `0.5.4`. Would like to suggest to re-open this issue @ctavan. Thanks!

**Comment by vinothsrva111** [comment]
having issue with 0.5.4 
0.5.3 downgrade working fine

**Comment by ctavan** [comment]
I guess a new bug report would be more appropriate since even though the symptoms might be the same I’m pretty confident that the underlying reasons are different from my original problems.

Just make sure to link to the new bug report from here so people from the future will find them.

**Comment by squaremo** [comment]
This was a different cause -- the published package really didn't include defs.js, because of a poorly trialed CI pipeline. See #534.

**Comment by squaremo** [comment]
(wrong button, nothing is going quite right for me ..)

**Comment by marcopaps** [comment]
thanks! @squaremo

**Comment by SSANSH** [comment]
+1
