### ISSUE TITLE
callback style require callbacks

### ISSUE THREAD

**Issue by funston** [squaremo/amqp.node#77]
The examples show this:

 ch.assertQueue(q);
    ch.sendToQueue(q, new Buffer('something to do'));

However, is it not required to do:

ch.assertQueue(q,function(err){
});

**Comment by heavi5ide** [comment]
Is it documented anywhere that the RPC calls (e.g. `assertQueue` and `assertExchange`) are serialized and you don't need to explicitly wait for them to return? I found the same example (as first noted in this issue) very confusing, for the same reason. Intuitively it seems that you'd have to wait to find out from the server that the assertQueue succeeded before doing an operation that relies on the queue being there. I think some comments in the examples or some notes/explanation in the docs for the RPC methods might make this auto-serialization behavior clearer. Or maybe I just missed where this is explained elsewhere?

**Comment by squaremo** [comment]
> Is it documented anywhere that the RPC calls (e.g. assertQueue and assertExchange) are serialized and you don't need to explicitly wait for them to return?

I mention it in the section titled "Dealing with failure" (http://squaremo.github.com/amqp.node/channel_api.html#failure), but only in passing.
