### ISSUE TITLE
reuse TCP socket?

### ISSUE THREAD

**Issue by feiyao** [squaremo/amqp.node#78]
If I have amqp.connect(uri) without closing this connection whether or not next call to amqp.connect(uri) will use the same TCP socket?

Per RabbitMQ document we should keep TCP, and open/close Channel on top it. But what I observed amqp.connect will create different TCP socket if I didn't close the connection.

Please clarify.
Thanks

**Comment by fmezas** [comment]
I've got a follow up question on this topic:
is there a recommended approach regarding the use of single vs multiple connections to create channels in a single process?

The two extremes would be:
1. opening a single connection and then using it to create all the channels needed by the process...
2. ...or opening a new connection and using it to create a channel every time we need to create a channel (of course closing channel and connection once done using them)

The only reason why I would consider using approach 2 would be if connections are not safe for concurrent use (given that channels keep a reference to them). A quick look at the source doesn't show anything obviously not safe for concurrent use, but I'm not comfortable with making that assumption on my own.

So, I guess my initial question could be rephrased as 'is it safe to open a single connection per process and use it to open multiple (concurrent) channels?

Thanks

**Comment by cressie176** [comment]
I don't recommend opening / closing a connection each time. Instead creating a single connection per vhost and create channels as needed. There's a small amount of overhead to creating a channel, so you can consider sharing those too.

**Comment by michaelklishin** [comment]
There is a [doc guide for that](http://www.rabbitmq.com/connections.html).

**Comment by fmezas** [comment]
Awesome. @cressie176 and @michaelklishin: thanks for the info
