### ISSUE TITLE
ConfirmChannel#publish / ConfirmChannel#sendToQueue should return a promise ?

### ISSUE THREAD

**Issue by pdelanauze** [squaremo/amqp.node#89]
Right now , (v0.2.1) ConfirmChannel#publish / ConfirmChannel#sendToQueue dont seem to return a promise , they only accept a callback ? Not 100% sure about this , but our current testing is returning true even if no callback is supplied ... If our testing is right , would it be worthwhile to return a promise ?

**Comment by squaremo** [comment]
I'm closing this, since I think I've met the brief of the original issue (with `waitForConfirms`). I don't mind if anyone wants to add more to the discussion though.

**Comment by matt-cook** [comment]
After reading the last post, I'm still unclear. Why can't `sendToQueue` simply return a promise that resolves with the boolean value?

Is this unsafe?
```js
var sendIt = new Promise((fulfill, reject) => {
        Rabbit.channel.sendToQueue(myQueue, myBuffer, {}, (err, res) => {
            if(err){
              reject(err);
            }else{
               fulfill(res);
            }
        });
});
```

**Comment by cyrilchapon** [comment]
@matt-cook and others, expanding on @matt-cook answer. I'm currently using a similar implementation

```
  async send (data, options) {
    this._checkChannel()

    const sendAsPromise = (this.amqp.channel instanceof ConfirmChannel)
      ? new Promise((resolve, reject) => {
        this.amqp.channel.sendToQueue(this.name, data, options,
          (err, ok) => err ? reject(err) : resolve(ok)
        })
      : this.amqp.channel.sendToQueue(this.name, data, options)

    return sendAsPromise
  }
```

Is that **safe** ?

More clearly : Can I consider "the callback being called with no `err`" (on a `ConfirmChannel`) as safe as "the promise resolve with `true`" (on a simple `Channel`) ?
