### ISSUE TITLE
Support for AMQP 1.0?

### ISSUE THREAD

**Issue by noodlefrenzy** [squaremo/amqp.node#99]
Is there any support for AMQP 1.0 in the works?  

I'm a developer at MSFT, _not_ on the Azure team, and we were trying to read from EventHub so need AMQP 1.0.  I'd be willing to help develop this support, but I want to make sure I'm not contending with someone else who might already be doing the work.  Please let me know if you're actively working on it, and if so, what I can do to help.

Thanks!

**Comment by mbroadst** [comment]
@squaremo if you're willing I think the project is ready for addition to the README
